import { access } from 'node:fs/promises';
import worker from '../src/router.js';
const env={ASSETS:{fetch:()=>new Response('',{status:200})},TURNSTILE_SITE_KEY:'1x00000000000000000000AA'};
async function check(path,status,includes=[],init={}){const r=await worker.fetch(new Request(`https://mythborn.co${path}`,init),env,{});if(r.status!==status)throw new Error(`${path} returned ${r.status}; expected ${status}`);const body=await r.text();for(const value of includes)if(!body.includes(value))throw new Error(`${path} missing ${value}`);return{r,body}}
for(const file of ['public/oracle.css','public/oracle.js','src/auth.js','src/account.js'])await access(new URL(`../${file}`,import.meta.url));
await check('/',200,['Günlük Tek Kart','Katina','Astroloji','ÖDEME KAPALI','Google ile devam et','Apple ile devam et','price":"0']);
await check('/gunluk-kart',200,['ÜYELİK GEREKTİRMEZ','data-daily-deck','Bugünün kartı']);
for(const [path,title,type] of [['/tarot','3 Kart Tarot','tarot'],['/ask','Aşk & Geri Dönüş','ask'],['/kariyer','Kariyer & Para','kariyer'],['/otuz-gun','30 Gün Açılımı','otuz-gun'],['/katina','Katina Aşk Falı','katina'],['/astroloji','Astroloji','astroloji']])await check(path,200,[title,'ÜCRETSİZ ÜYELİKLE AÇILIR',`data-member-reading="${type}"`,'data-reading-workspace']);
await check('/ask',200,['İlişki durumun','Odaklandığın soru']);
await check('/kariyer',200,['Odak alanın','İş değişikliği']);
await check('/astroloji',200,['Doğum tarihi','Doğum saati','Doğum yeri']);
await check('/kayit',200,['Ücretsiz hesap oluştur','Google ile devam et','Apple ile devam et','noindex,nofollow']);
await check('/giris',200,['Giriş yap','noindex,nofollow']);
await check('/hesabim',200,['AÇILIM GEÇMİŞİ','Yeni açılım','noindex,nofollow']);
await check('/robots.txt',200,['Disallow: /api/','Sitemap: https://mythborn.co/sitemap.xml']);
const sitemap=await check('/sitemap.xml',200,['https://mythborn.co/gunluk-kart','https://mythborn.co/katina','https://mythborn.co/astroloji']);
if(sitemap.body.includes('/giris')||sitemap.body.includes('/kayit'))throw new Error('Private routes leaked into sitemap');
await check('/llms.txt',200,['ücretsiz Tarot','Ödeme: varsayılan olarak kapalı']);
await check('/api/auth/me',503,['veritabanı']);
await check('/api/webhooks/payment',503,['veritabanı'],{method:'POST'});
await check('/not-found',404,['Bu kapı henüz açılmadı.']);
console.log('Mythborn ücretsiz Tarot, Katina, astroloji, üyelik kapısı, kişiselleştirilmiş açılım, ödeme bayrağı, SEO ve route audit’i geçti.');