import worker from '../src/app-router.js';
const env={ASSETS:{fetch:()=>new Response('',{status:200})},TURNSTILE_SITE_KEY:'1x00000000000000000000AA'};
async function check(path,need=[]){const response=await worker.fetch(new Request(`https://mythborn.co${path}`),env,{});if(response.status!==200)throw new Error(`${path} returned ${response.status}`);const body=await response.text();for(const value of need)if(!body.includes(value))throw new Error(`${path} missing ${value}`);return body}
const routes=['/astrokartografi','/progresyonlar','/solar-return','/lunar-return','/vedik-astroloji','/nakshatra-dasha'];
await check('/advanced-astrology',['GELİŞMİŞ ASTROLOJİ','Astrokartografi','Vedik Astroloji','hreflang="en"','hreflang="el"']);
await check('/en/advanced-astrology',['ADVANCED ASTROLOGY','Astrocartography','Vedic Astrology','lang="en"']);
await check('/gr/advanced-astrology',['ΠΡΟΧΩΡΗΜΕΝΗ ΑΣΤΡΟΛΟΓΙΑ','Αστροχαρτογραφία','Βεδική Αστρολογία','lang="el"']);
for(const route of routes){await check(route,['FAQPage','BreadcrumbList','Article','hreflang="en"','hreflang="el"']);await check(`/en${route}`,['FAQPage','BreadcrumbList','Article','lang="en"']);await check(`/gr${route}`,['FAQPage','BreadcrumbList','Article','lang="el"'])}
const slugs=['saturn-retrosu-2026','12-agustos-2026-gunes-tutulmasi','jupiter-aslanda-2026','uranus-ikizlerde-teknoloji-yapay-zeka','sinastri-nedir','saturn-donusu-rehberi','astrokartografi-nedir','travma-bilincli-astroloji','yapay-zeka-tarot-etik','tarot-ve-astrolojiyi-birlikte-okumak'];
await check('/en/blog',['SKY JOURNAL','Saturn Retrograde 2026','AI Tarot Interpretation']);await check('/gr/blog',['ΟΥΡΑΝΙΟ ΠΕΡΙΟΔΙΚΟ','Ανάδρομος Κρόνος 2026','Ερμηνεία Ταρώ με AI']);
for(const slug of slugs){await check(`/en/blog/${slug}`,['FAQPage','Article','hreflang="tr"']);await check(`/gr/blog/${slug}`,['FAQPage','Article','hreflang="tr"'])}
await check('/tarot-kartlari',['Tarot Kartları Ansiklopedisi','Büyük Arkana','Küçük Arkana']);await check('/en/tarot-kartlari',['Tarot Card Encyclopedia','Major Arcana','Minor Arcana']);await check('/gr/tarot-kartlari',['Εγκυκλοπαίδεια Καρτών Ταρώ','Μεγάλη Αρκάνα','Μικρή Αρκάνα']);
for(const path of ['/tarot-kartlari/deli','/tarot-kartlari/kupa-on','/tarot-kartlari/kilic-kralice']){await check(path,['FAQPage','BreadcrumbList','Işık anlamı']);await check(`/en${path}`,['FAQPage','BreadcrumbList','Light meaning']);await check(`/gr${path}`,['FAQPage','BreadcrumbList','Φωτεινή έννοια'])}
await check('/astroloji-kutuphanesi',['Doğum Haritası Kütüphanesi','12 Burç','12 Ev']);await check('/en/astroloji-kutuphanesi',['Birth Chart Library','12 Signs','12 Houses']);await check('/gr/astroloji-kutuphanesi',['Βιβλιοθήκη Γενέθλιου Χάρτη','12 Ζώδια','12 Οίκοι']);
for(const path of ['/burclar/akrep','/evler/10','/gezegenler/saturn','/acilar/kare','/transitler','/retro-hareketler']){await check(path,['FAQPage','BreadcrumbList','Article']);await check(`/en${path}`,['FAQPage','BreadcrumbList','Article','lang="en"']);await check(`/gr${path}`,['FAQPage','BreadcrumbList','Article','lang="el"'])}
await check('/ruya-sembolleri',['Rüya Sembolleri Ansiklopedisi','Su','Yılan','Deprem']);await check('/en/ruya-sembolleri',['Dream Symbol Encyclopedia','Water','Snake','Earthquake']);await check('/gr/ruya-sembolleri',['Εγκυκλοπαίδεια Συμβόλων Ονείρων','Νερό','Φίδι','Σεισμός']);
for(const path of ['/ruya-sembolleri/su','/ruya-sembolleri/yilan','/ruya-sembolleri/dis']){await check(path,['BreadcrumbList','Temel anlam','Bağlama göre']);await check(`/en${path}`,['BreadcrumbList','Core meaning','In context']);await check(`/gr${path}`,['BreadcrumbList','Βασική έννοια','Ανάλογα με το πλαίσιο'])}
await check('/astroloji-sozlugu',['Astroloji Sözlüğü','Yükselen','Orb','Transit']);await check('/en/astroloji-sozlugu',['Astrology Glossary','Ascendant','Orb','Transit']);await check('/gr/astroloji-sozlugu',['Γλωσσάρι Αστρολογίας','Ωροσκόπος','Ανοχή όψης','Διέλευση']);
for(const path of ['/astroloji-sozlugu/yukselen','/astroloji-sozlugu/orb','/astroloji-sozlugu/solar-return']){await check(path,['DefinedTerm','BreadcrumbList']);await check(`/en${path}`,['DefinedTerm','BreadcrumbList','lang="en"']);await check(`/gr${path}`,['DefinedTerm','BreadcrumbList','lang="el"'])}
const sitemap=await check('/sitemap.xml',['/ruya-sembolleri/deprem','/en/ruya-sembolleri/su','/gr/ruya-sembolleri/yilan','/astroloji-sozlugu/yukselen','/en/astroloji-sozlugu/orb','/gr/astroloji-sozlugu/transit','hreflang="x-default"']);if(!sitemap.includes('xmlns:xhtml'))throw new Error('Localized sitemap namespace missing');
console.log(`Premium multilingual audit passed: ${slugs.length} articles, 78 Tarot cards, 42 birth-chart guides, 51 dream symbols and 25 glossary terms × 3 languages.`);
