const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
import {esField,esUi} from './spanish-astrology-data.js';
const SITE='https://mythborn.co';
const ui={tr:{home:'Doğum Haritası Kütüphanesi',intro:'Burçlar, evler, gezegenler, açılar, transitler ve retro hareketler için üç katmanlı başvuru merkezi.',read:'Rehberi aç',meaning:'Temel anlam',light:'Yapıcı ifade',shadow:'Gölge ifade',practice:'Kendine sor',faq:'Sık sorulanlar',note:'Bu içerik eğitim ve kişisel farkındalık amaçlıdır; bilimsel tanı veya kesin gelecek öngörüsü değildir.'},en:{home:'Birth Chart Library',intro:'A structured reference centre for signs, houses, planets, aspects, transits and retrogrades.',read:'Open guide',meaning:'Core meaning',light:'Constructive expression',shadow:'Shadow expression',practice:'Ask yourself',faq:'Frequently asked questions',note:'This content is for education and personal reflection; it is not scientific diagnosis or certain prediction.'},el:{home:'Βιβλιοθήκη Γενέθλιου Χάρτη',intro:'Δομημένο κέντρο αναφοράς για ζώδια, οίκους, πλανήτες, όψεις, διελεύσεις και ανάδρομες κινήσεις.',read:'Άνοιγμα οδηγού',meaning:'Βασικό νόημα',light:'Δημιουργική έκφραση',shadow:'Σκιώδης έκφραση',practice:'Ρώτησε τον εαυτό σου',faq:'Συχνές ερωτήσεις',note:'Το περιεχόμενο είναι για εκπαίδευση και προσωπικό στοχασμό· δεν αποτελεί επιστημονική διάγνωση ή βέβαιη πρόβλεψη.'},es:esUi};
const signs=[
['koc','Koç','Aries','Κριός','Ateş','Fire','Φωτιά','Öncü','Cardinal','Παρορμητικό','başlatmak, cesaret ve doğrudan hareket','initiation, courage and direct action','έναρξη, θάρρος και άμεση δράση','acelecilik ve yalnız hareket etme eğilimi','impatience and acting alone','βιασύνη και τάση για μοναχική δράση'],
['boga','Boğa','Taurus','Ταύρος','Toprak','Earth','Γη','Sabit','Fixed','Σταθερό','istikrar, değerler ve bedensel güven','stability, values and embodied security','σταθερότητα, αξίες και σωματική ασφάλεια','inat, değişime direnç ve sahiplenme','stubbornness, resistance to change and possessiveness','πείσμα, αντίσταση στην αλλαγή και κτητικότητα'],
['ikizler','İkizler','Gemini','Δίδυμοι','Hava','Air','Αέρας','Değişken','Mutable','Μεταβλητό','merak, dil ve bağlantı kurma','curiosity, language and connection','περιέργεια, γλώσσα και σύνδεση','dağılma, yüzeysellik ve zihinsel aşırı yük','scattering, superficiality and mental overload','διάσπαση, επιφανειακότητα και νοητική υπερφόρτωση'],
['yengec','Yengeç','Cancer','Καρκίνος','Su','Water','Νερό','Öncü','Cardinal','Παρορμητικό','aidiyet, bakım ve duygusal güven','belonging, care and emotional safety','ανήκειν, φροντίδα και συναισθηματική ασφάλεια','alınganlık, içe kapanma ve aşırı koruma','sensitivity, withdrawal and overprotection','ευαισθησία, απόσυρση και υπερπροστασία'],
['aslan','Aslan','Leo','Λέων','Ateş','Fire','Φωτιά','Sabit','Fixed','Σταθερό','yaratıcılık, görünürlük ve kalpten ifade','creativity, visibility and heartfelt expression','δημιουργικότητα, ορατότητα και έκφραση από καρδιάς','gurur, dramatizasyon ve onay ihtiyacı','pride, dramatization and need for approval','υπερηφάνεια, δραματοποίηση και ανάγκη επιβεβαίωσης'],
['basak','Başak','Virgo','Παρθένος','Toprak','Earth','Γη','Değişken','Mutable','Μεταβλητό','ayıklama, hizmet ve işleyen sistemler','discernment, service and workable systems','διάκριση, υπηρεσία και λειτουργικά συστήματα','mükemmeliyetçilik, eleştiri ve kaygı','perfectionism, criticism and anxiety','τελειομανία, κριτική και άγχος'],
['terazi','Terazi','Libra','Ζυγός','Hava','Air','Αέρας','Öncü','Cardinal','Παρορμητικό','denge, ilişki ve adil müzakere','balance, relationship and fair negotiation','ισορροπία, σχέση και δίκαιη διαπραγμάτευση','kararsızlık, hoşnut etme ve çatışmadan kaçınma','indecision, people-pleasing and conflict avoidance','αναποφασιστικότητα, ευχαρίστηση των άλλων και αποφυγή σύγκρουσης'],
['akrep','Akrep','Scorpio','Σκορπιός','Su','Water','Νερό','Sabit','Fixed','Σταθερό','derinlik, dönüşüm ve duygusal dürüstlük','depth, transformation and emotional honesty','βάθος, μεταμόρφωση και συναισθηματική ειλικρίνεια','kontrol, kuşku ve yoğunluğu mutlaklaştırma','control, suspicion and absolutizing intensity','έλεγχος, καχυποψία και απολυτοποίηση της έντασης'],
['yay','Yay','Sagittarius','Τοξότης','Ateş','Fire','Φωτιά','Değişken','Mutable','Μεταβλητό','anlam, keşif ve geniş perspektif','meaning, exploration and broad perspective','νόημα, εξερεύνηση και ευρεία οπτική','abartı, sabırsızlık ve detay atlama','exaggeration, restlessness and skipping detail','υπερβολή, ανησυχία και παράλειψη λεπτομερειών'],
['oglak','Oğlak','Capricorn','Αιγόκερως','Toprak','Earth','Γη','Öncü','Cardinal','Παρορμητικό','sorumluluk, yapı ve uzun vadeli emek','responsibility, structure and long-term effort','ευθύνη, δομή και μακροπρόθεσμη προσπάθεια','katılık, aşırı yüklenme ve başarıyla özdeşleşme','rigidity, overwork and identification with achievement','ακαμψία, υπερκόπωση και ταύτιση με την επίτευξη'],
['kova','Kova','Aquarius','Υδροχόος','Hava','Air','Αέρας','Sabit','Fixed','Σταθερό','özgünlük, topluluk ve sistem değişimi','originality, community and systems change','πρωτοτυπία, κοινότητα και αλλαγή συστημάτων','mesafe, inatçı fikirler ve duygudan kopma','distance, fixed ideas and emotional detachment','απόσταση, άκαμπτες ιδέες και συναισθηματική αποσύνδεση'],
['balik','Balık','Pisces','Ιχθύες','Su','Water','Νερό','Değişken','Mutable','Μεταβλητό','sezgi, şefkat ve sınırlar arası algı','intuition, compassion and porous perception','διαίσθηση, συμπόνια και πορώδης αντίληψη','kaçış, belirsiz sınırlar ve idealizasyon','escape, blurred boundaries and idealization','φυγή, ασαφή όρια και εξιδανίκευση']];
const houses=[['1','Benlik ve başlangıçlar','Self and beginnings','Εαυτός και ξεκινήματα'],['2','Kaynaklar, para ve değerler','Resources, money and values','Πόροι, χρήματα και αξίες'],['3','Öğrenme, iletişim ve yakın çevre','Learning, communication and local environment','Μάθηση, επικοινωνία και κοντινό περιβάλλον'],['4','Kökler, ev ve iç güvenlik','Roots, home and inner security','Ρίζες, σπίτι και εσωτερική ασφάλεια'],['5','Yaratıcılık, aşk ve oyun','Creativity, romance and play','Δημιουργικότητα, έρωτας και παιχνίδι'],['6','Günlük düzen, emek ve sağlık alışkanlıkları','Daily routines, work and health habits','Καθημερινότητα, εργασία και συνήθειες υγείας'],['7','İlişkiler, ortaklık ve yansıtma','Relationships, partnership and projection','Σχέσεις, συνεργασία και προβολή'],['8','Paylaşılan kaynaklar, kriz ve dönüşüm','Shared resources, crisis and transformation','Κοινοί πόροι, κρίση και μεταμόρφωση'],['9','İnançlar, yüksek öğrenim ve uzak ufuklar','Beliefs, higher learning and distant horizons','Πεποιθήσεις, ανώτερη μάθηση και μακρινοί ορίζοντες'],['10','Kariyer, yön ve kamusal rol','Career, direction and public role','Καριέρα, κατεύθυνση και δημόσιος ρόλος'],['11','Topluluk, gelecek ve kolektif hedefler','Community, future and collective goals','Κοινότητα, μέλλον και συλλογικοί στόχοι'],['12','İçe dönüş, bilinçdışı ve kapanışlar','Retreat, unconscious patterns and endings','Εσωστρέφεια, ασυνείδητα μοτίβα και ολοκληρώσεις']];
const planets=[['gunes','Güneş','Sun','Ήλιος','kimlik, canlılık ve bilinçli yön','identity, vitality and conscious direction','ταυτότητα, ζωτικότητα και συνειδητή κατεύθυνση'],['ay','Ay','Moon','Σελήνη','duygusal ihtiyaçlar, alışkanlıklar ve güven','emotional needs, habits and safety','συναισθηματικές ανάγκες, συνήθειες και ασφάλεια'],['merkur','Merkür','Mercury','Ερμής','zihin, dil ve bilgi işleme','mind, language and information processing','νους, γλώσσα και επεξεργασία πληροφοριών'],['venus','Venüs','Venus','Αφροδίτη','değer, ilişki ve çekim','values, relating and attraction','αξίες, σχέσεις και έλξη'],['mars','Mars','Mars','Άρης','istek, eylem ve sınır koyma','desire, action and boundary-setting','επιθυμία, δράση και όρια'],['jupiter','Jüpiter','Jupiter','Δίας','büyüme, anlam ve inanç','growth, meaning and belief','ανάπτυξη, νόημα και πίστη'],['saturn','Satürn','Saturn','Κρόνος','sorumluluk, yapı ve zaman','responsibility, structure and time','ευθύνη, δομή και χρόνος'],['uranus','Uranüs','Uranus','Ουρανός','özgürleşme, değişim ve uyanış','liberation, disruption and awakening','απελευθέρωση, ανατροπή και αφύπνιση'],['neptun','Neptün','Neptune','Ποσειδώνας','hayal, sezgi ve çözülme','imagination, intuition and dissolution','φαντασία, διαίσθηση και διάλυση'],['pluton','Plüton','Pluto','Πλούτωνας','güç, gölge ve dönüşüm','power, shadow and transformation','δύναμη, σκιά και μεταμόρφωση']];
const aspects=[['kavusum','Kavuşum','Conjunction','Σύνοδος','iki işlevin aynı alanda yoğunlaşması','two functions concentrating in the same field','δύο λειτουργίες συγκεντρώνονται στο ίδιο πεδίο'],['karsit','Karşıt','Opposition','Αντίθεση','iki kutup arasında farkındalık ve denge','awareness and balance between two poles','επίγνωση και ισορροπία ανάμεσα σε δύο πόλους'],['kare','Kare','Square','Τετράγωνο','gerilim yoluyla eylem ve gelişim','action and growth through friction','δράση και ανάπτυξη μέσω έντασης'],['ucgen','Üçgen','Trine','Τρίγωνο','doğal akış, yetenek ve kolaylık','natural flow, talent and ease','φυσική ροή, ταλέντο και ευκολία'],['sekstil','Sekstil','Sextile','Εξάγωνο','fırsat, iş birliği ve geliştirilebilir potansiyel','opportunity, cooperation and developable potential','ευκαιρία, συνεργασία και αναπτύξιμο δυναμικό'],['quincunx','150° Quincunx','Quincunx','Χιαστί 150°','uyumsuz ihtiyaçlar arasında sürekli ayar','ongoing adjustment between mismatched needs','συνεχής προσαρμογή ανάμεσα σε ασύμβατες ανάγκες']];
const signDetails={
koc:{dates:['21 Mart–19 Nisan','21 March–19 April','21 Μαρτίου–19 Απριλίου','21 marzo–19 abril'],ruler:['Mars','Mars','Άρης','Marte'],love:['doğrudanlık, heyecan ve birlikte hareket etme ihtiyacı','directness, excitement and the need to move together','αμεσότητα, ενθουσιασμός και ανάγκη κοινής δράσης','franqueza, entusiasmo y necesidad de avanzar juntos'],career:['inisiyatif, hız, rekabet ve ilk adımı atma cesareti','initiative, speed, competition and courage to make the first move','πρωτοβουλία, ταχύτητα, ανταγωνισμός και θάρρος για το πρώτο βήμα','iniciativa, rapidez, competencia y valentía para dar el primer paso'],money:['hızlı karar eğilimini bütçe ve bekleme süresiyle dengelemek','balancing fast decisions with budgets and a cooling-off period','ισορροπία γρήγορων αποφάσεων με προϋπολογισμό και χρόνο αναμονής','equilibrar decisiones rápidas con presupuesto y un tiempo de espera'],communication:['net, kısa ve doğrudan ifade; sabırsızlıkta sertleşebilir','clear, brief and direct expression; impatience can make it sharp','σαφής, σύντομη και άμεση έκφραση· η ανυπομονησία μπορεί να την οξύνει','expresión clara, breve y directa; la impaciencia puede volverla brusca']},
boga:{dates:['20 Nisan–20 Mayıs','20 April–20 May','20 Απριλίου–20 Μαΐου','20 abril–20 mayo'],ruler:['Venüs','Venus','Αφροδίτη','Venus'],love:['güven, sadakat, fiziksel yakınlık ve istikrarlı ritim','trust, loyalty, physical closeness and a steady rhythm','εμπιστοσύνη, πίστη, σωματική εγγύτητα και σταθερός ρυθμός','confianza, lealtad, cercanía física y ritmo estable'],career:['sabır, kalıcılık, kalite ve kaynakları uzun vadeli kullanma','patience, durability, quality and long-term resource use','υπομονή, αντοχή, ποιότητα και μακροπρόθεσμη χρήση πόρων','paciencia, durabilidad, calidad y uso de recursos a largo plazo'],money:['birikim ve somut değer yaratmada güçlü; konfor harcamalarında katılaşabilir','strong at saving and creating tangible value; comfort spending can become rigid','ικανότητα αποταμίευσης και δημιουργίας απτής αξίας· πιθανή προσκόλληση σε δαπάνες άνεσης','fuerte para ahorrar y crear valor tangible; puede aferrarse a gastos de comodidad'],communication:['yavaş ama sağlam karar; fikrini değiştirmeden önce güven ister','slow but firm decisions; needs confidence before changing course','αργές αλλά σταθερές αποφάσεις· χρειάζεται ασφάλεια πριν αλλάξει πορεία','decisiones lentas pero firmes; necesita seguridad antes de cambiar de rumbo']},
ikizler:{dates:['21 Mayıs–20 Haziran','21 May–20 June','21 Μαΐου–20 Ιουνίου','21 mayo–20 junio'],ruler:['Merkür','Mercury','Ερμής','Mercurio'],love:['zihinsel uyum, merak, konuşma ve hareket alanı','mental rapport, curiosity, conversation and room to move','νοητική σύνδεση, περιέργεια, συζήτηση και ελευθερία κίνησης','sintonía mental, curiosidad, conversación y espacio para moverse'],career:['bilgi, yazı, satış, medya, eğitim ve bağlantı kurma','information, writing, sales, media, education and networking','πληροφορία, γραφή, πωλήσεις, μέσα, εκπαίδευση και δικτύωση','información, escritura, ventas, medios, educación y conexiones'],money:['çoklu gelir fikirleri üretir; dağılmamak için takip sistemi gerekir','can generate multiple income ideas; needs tracking systems to avoid scattering','παράγει πολλές ιδέες εισοδήματος· χρειάζεται σύστημα παρακολούθησης για να μην διασπάται','genera múltiples ideas de ingresos; necesita seguimiento para no dispersarse'],communication:['hızlı, esnek ve soru odaklı; bilgi fazlasında yüzeyselleşebilir','quick, flexible and question-led; can skim when overloaded','γρήγορη, ευέλικτη και ερωτηματοκεντρική επικοινωνία· μπορεί να γίνει επιφανειακή','comunicación rápida, flexible y basada en preguntas; puede quedarse en la superficie']},
yengec:{dates:['21 Haziran–22 Temmuz','21 June–22 July','21 Ιουνίου–22 Ιουλίου','21 junio–22 julio'],ruler:['Ay','Moon','Σελήνη','Luna'],love:['duygusal güven, aidiyet, bakım ve mahremiyet','emotional safety, belonging, care and privacy','συναισθηματική ασφάλεια, ανήκειν, φροντίδα και ιδιωτικότητα','seguridad emocional, pertenencia, cuidado y privacidad'],career:['koruyucu liderlik, ekip bağlılığı, sezgisel ihtiyaç okuma ve süreklilik','protective leadership, team loyalty, intuitive needs-reading and continuity','προστατευτική ηγεσία, συνοχή ομάδας, διαισθητική κατανόηση αναγκών και συνέχεια','liderazgo protector, lealtad de equipo, lectura intuitiva de necesidades y continuidad'],money:['güvenlik için birikim eğilimi; duygusal harcamaları ayırmak önemlidir','inclined to save for security; separating emotional spending is useful','τάση αποταμίευσης για ασφάλεια· χρήσιμος ο διαχωρισμός συναισθηματικών δαπανών','tendencia a ahorrar por seguridad; conviene separar el gasto emocional'],communication:['duygusal bağlamı güçlü okur; incindiğinde dolaylılaşabilir','reads emotional context well; can become indirect when hurt','διαβάζει καλά το συναισθηματικό πλαίσιο· μπορεί να γίνει έμμεσος όταν πληγωθεί','lee bien el contexto emocional; puede volverse indirecto cuando se siente herido']},
aslan:{dates:['23 Temmuz–22 Ağustos','23 July–22 August','23 Ιουλίου–22 Αυγούστου','23 julio–22 agosto'],ruler:['Güneş','Sun','Ήλιος','Sol'],love:['sıcaklık, sadakat, takdir ve gurur duyulan ortaklık','warmth, loyalty, appreciation and a partnership to be proud of','ζεστασιά, πίστη, εκτίμηση και σχέση για την οποία υπάρχει υπερηφάνεια','calidez, lealtad, reconocimiento y una relación de la que sentirse orgulloso'],career:['yaratıcılık, liderlik, görünürlük ve insanları motive etme','creativity, leadership, visibility and motivating others','δημιουργικότητα, ηγεσία, ορατότητα και παρακίνηση άλλων','creatividad, liderazgo, visibilidad y capacidad de motivar'],money:['kalite ve prestije harcamayı sever; gösteriş ile değer yaratmayı ayırmak gerekir','enjoys spending on quality and prestige; distinguish display from value creation','αγαπά δαπάνες για ποιότητα και κύρος· χρειάζεται διάκριση επίδειξης από πραγματική αξία','disfruta gastar en calidad y prestigio; conviene distinguir apariencia y valor real'],communication:['özgüvenli, sıcak ve dramatik; eleştiride savunmaya geçebilir','confident, warm and dramatic; may become defensive under criticism','σίγουρη, ζεστή και δραματική επικοινωνία· πιθανή άμυνα στην κριτική','comunicación segura, cálida y expresiva; puede ponerse a la defensiva ante críticas']},
basak:{dates:['23 Ağustos–22 Eylül','23 August–22 September','23 Αυγούστου–22 Σεπτεμβρίου','23 agosto–22 septiembre'],ruler:['Merkür','Mercury','Ερμής','Mercurio'],love:['özen, güvenilirlik, faydalı olmak ve ayrıntılarda sevgi gösterme','care, reliability, usefulness and showing affection through detail','φροντίδα, αξιοπιστία, χρησιμότητα και αγάπη μέσα από λεπτομέρειες','cuidado, fiabilidad, utilidad y afecto expresado en los detalles'],career:['analiz, kalite kontrol, süreç iyileştirme ve uzmanlaşma','analysis, quality control, process improvement and specialisation','ανάλυση, ποιοτικός έλεγχος, βελτίωση διαδικασιών και εξειδίκευση','análisis, control de calidad, mejora de procesos y especialización'],money:['küçük giderleri iyi izler; aşırı kontrol karar yorgunluğu yaratabilir','tracks small expenses well; over-control can create decision fatigue','παρακολουθεί καλά μικρές δαπάνες· ο υπερβολικός έλεγχος κουράζει','controla bien los pequeños gastos; el exceso de control puede agotar'],communication:['kesin, analitik ve düzeltici; eleştiri ile yardım arasındaki tonu ayarlamalıdır','precise, analytical and corrective; tone matters between help and criticism','ακριβής, αναλυτική και διορθωτική· χρειάζεται σωστός τόνος μεταξύ βοήθειας και κριτικής','precisa, analítica y correctiva; importa el tono entre ayuda y crítica']},
terazi:{dates:['23 Eylül–22 Ekim','23 September–22 October','23 Σεπτεμβρίου–22 Οκτωβρίου','23 septiembre–22 octubre'],ruler:['Venüs','Venus','Αφροδίτη','Venus'],love:['karşılıklılık, uyum, estetik ve birlikte karar verme','reciprocity, harmony, aesthetics and shared decision-making','αμοιβαιότητα, αρμονία, αισθητική και κοινές αποφάσεις','reciprocidad, armonía, estética y decisiones compartidas'],career:['müzakere, ilişki yönetimi, tasarım, hukuk ve arabuluculuk','negotiation, relationship management, design, law and mediation','διαπραγμάτευση, διαχείριση σχέσεων, σχεδιασμός, νομικά και διαμεσολάβηση','negociación, gestión de relaciones, diseño, derecho y mediación'],money:['denge ve kalite arar; sosyal harcamalarda sınır koymak gerekebilir','seeks balance and quality; social spending may need boundaries','αναζητά ισορροπία και ποιότητα· ίσως χρειάζονται όρια σε κοινωνικές δαπάνες','busca equilibrio y calidad; puede necesitar límites en gastos sociales'],communication:['diplomatik ve çok yönlü; kararsızlık netliği geciktirebilir','diplomatic and multi-perspective; indecision can delay clarity','διπλωματική και πολυπρισματική· η αναποφασιστικότητα μπορεί να καθυστερήσει τη σαφήνεια','diplomática y multiperspectiva; la indecisión puede retrasar la claridad']},
akrep:{dates:['23 Ekim–21 Kasım','23 October–21 November','23 Οκτωβρίου–21 Νοεμβρίου','23 octubre–21 noviembre'],ruler:['Mars / Plüton','Mars / Pluto','Άρης / Πλούτωνας','Marte / Plutón'],love:['derin güven, mahremiyet, sadakat ve duygusal dürüstlük','deep trust, privacy, loyalty and emotional honesty','βαθιά εμπιστοσύνη, ιδιωτικότητα, πίστη και συναισθηματική ειλικρίνεια','confianza profunda, privacidad, lealtad y honestidad emocional'],career:['araştırma, kriz yönetimi, strateji, finans ve dönüşüm işleri','research, crisis management, strategy, finance and transformation work','έρευνα, διαχείριση κρίσεων, στρατηγική, οικονομικά και μετασχηματισμός','investigación, gestión de crisis, estrategia, finanzas y transformación'],money:['ortak kaynak ve riskleri ciddiye alır; kontrolü paylaşmak zor olabilir','takes shared resources and risk seriously; sharing control can be hard','παίρνει σοβαρά κοινούς πόρους και κίνδυνο· δύσκολο το μοίρασμα ελέγχου','se toma en serio recursos compartidos y riesgo; puede costarle compartir control'],communication:['az ama yoğun konuşur; ima ve kuşku açık iletişimi zorlaştırabilir','speaks selectively but intensely; implication and suspicion can cloud clarity','μιλά επιλεκτικά αλλά έντονα· υπονοούμενα και καχυποψία θολώνουν τη σαφήνεια','habla de forma selectiva e intensa; insinuaciones y sospecha pueden complicar la claridad']},
yay:{dates:['22 Kasım–21 Aralık','22 November–21 December','22 Νοεμβρίου–21 Δεκεμβρίου','22 noviembre–21 diciembre'],ruler:['Jüpiter','Jupiter','Δίας','Júpiter'],love:['özgürlük, ortak macera, dürüstlük ve zihinsel genişleme','freedom, shared adventure, honesty and mental expansion','ελευθερία, κοινή περιπέτεια, ειλικρίνεια και νοητική διεύρυνση','libertad, aventura compartida, honestidad y expansión mental'],career:['öğretme, seyahat, uluslararası işler, yayıncılık ve vizyon','teaching, travel, international work, publishing and vision','διδασκαλία, ταξίδια, διεθνής εργασία, εκδόσεις και όραμα','enseñanza, viajes, trabajo internacional, publicación y visión'],money:['büyüme fırsatlarını görür; iyimserliği bütçeyle dengelemek gerekir','spots growth opportunities; optimism needs a budget check','βλέπει ευκαιρίες ανάπτυξης· η αισιοδοξία χρειάζεται έλεγχο προϋπολογισμού','detecta oportunidades de crecimiento; el optimismo necesita control presupuestario'],communication:['açık, mizahi ve büyük resme odaklı; ayrıntıları atlayabilir','open, humorous and big-picture; may skip detail','ανοιχτή, χιουμοριστική και προσανατολισμένη στη μεγάλη εικόνα· μπορεί να παραλείπει λεπτομέρειες','abierta, humorística y centrada en la visión general; puede saltarse detalles']},
oglak:{dates:['22 Aralık–19 Ocak','22 December–19 January','22 Δεκεμβρίου–19 Ιανουαρίου','22 diciembre–19 enero'],ruler:['Satürn','Saturn','Κρόνος','Saturno'],love:['güvenilirlik, sorumluluk, uzun vadeli niyet ve saygı','reliability, responsibility, long-term intention and respect','αξιοπιστία, ευθύνη, μακροπρόθεσμη πρόθεση και σεβασμός','fiabilidad, responsabilidad, intención a largo plazo y respeto'],career:['yapı kurma, yönetim, strateji, disiplin ve sonuç alma','structure-building, management, strategy, discipline and delivery','δόμηση, διοίκηση, στρατηγική, πειθαρχία και αποτέλεσμα','construcción de estructuras, gestión, estrategia, disciplina y resultados'],money:['uzun vadeli planlamada güçlü; güvenlik için aşırı kısıtlayabilir','strong at long-term planning; may over-restrict for security','δυνατός στον μακροπρόθεσμο σχεδιασμό· μπορεί να περιορίζεται υπερβολικά για ασφάλεια','fuerte en planificación a largo plazo; puede restringirse demasiado por seguridad'],communication:['ölçülü, ciddi ve sonuç odaklı; duygusal tonu geri plana atabilir','measured, serious and outcome-focused; may underplay emotional tone','μετρημένη, σοβαρή και προσανατολισμένη στο αποτέλεσμα· μπορεί να υποτιμά το συναίσθημα','mesurada, seria y orientada a resultados; puede dejar en segundo plano el tono emocional']},
kova:{dates:['20 Ocak–18 Şubat','20 January–18 February','20 Ιανουαρίου–18 Φεβρουαρίου','20 enero–18 febrero'],ruler:['Satürn / Uranüs','Saturn / Uranus','Κρόνος / Ουρανός','Saturno / Urano'],love:['özgürlük, arkadaşlık, zihinsel eşitlik ve bireysel alan','freedom, friendship, intellectual equality and individual space','ελευθερία, φιλία, νοητική ισότητα και προσωπικός χώρος','libertad, amistad, igualdad intelectual y espacio individual'],career:['teknoloji, sistemler, topluluk, yenilik ve gelecek odaklı düşünme','technology, systems, community, innovation and future-oriented thinking','τεχνολογία, συστήματα, κοινότητα, καινοτομία και μελλοντικός προσανατολισμός','tecnología, sistemas, comunidad, innovación y pensamiento de futuro'],money:['alışılmadık gelir modellerine açıktır; fikirleri gerçek verilerle test etmelidir','open to unconventional income models; ideas need real-world testing','ανοιχτός σε ασυνήθιστα μοντέλα εισοδήματος· οι ιδέες χρειάζονται πραγματική δοκιμή','abierto a modelos de ingresos poco convencionales; las ideas necesitan pruebas reales'],communication:['özgün, kavramsal ve objektif; duygusal mesafe hissi yaratabilir','original, conceptual and objective; can feel emotionally distant','πρωτότυπη, εννοιολογική και αντικειμενική· μπορεί να φαίνεται συναισθηματικά απόμακρη','original, conceptual y objetiva; puede parecer emocionalmente distante']},
balik:{dates:['19 Şubat–20 Mart','19 February–20 March','19 Φεβρουαρίου–20 Μαρτίου','19 febrero–20 marzo'],ruler:['Jüpiter / Neptün','Jupiter / Neptune','Δίας / Ποσειδώνας','Júpiter / Neptuno'],love:['empati, romantizm, ruhsal yakınlık ve yumuşaklık','empathy, romance, soulful closeness and tenderness','ενσυναίσθηση, ρομαντισμός, ψυχική εγγύτητα και τρυφερότητα','empatía, romanticismo, cercanía emocional y ternura'],career:['yaratıcılık, sanat, yardım meslekleri, sezgi ve anlam üretimi','creativity, arts, helping professions, intuition and meaning-making','δημιουργικότητα, τέχνες, επαγγέλματα βοήθειας, διαίσθηση και νόημα','creatividad, arte, profesiones de ayuda, intuición y creación de sentido'],money:['sezgisel davranabilir; belirsiz bütçeyi somut sınırlarla desteklemek gerekir','may act intuitively; vague budgets need concrete limits','μπορεί να λειτουργεί διαισθητικά· οι ασαφείς προϋπολογισμοί χρειάζονται σαφή όρια','puede actuar por intuición; los presupuestos vagos necesitan límites concretos'],communication:['sezgisel, şiirsel ve bağlamı hisseden; belirsizlikte netlik kaybolabilir','intuitive, poetic and context-sensitive; clarity can blur under uncertainty','διαισθητική, ποιητική και ευαίσθητη στο πλαίσιο· η σαφήνεια μπορεί να χαθεί','intuitiva, poética y sensible al contexto; la claridad puede difuminarse']}
};
const detailField=(detail,locale,key)=>detail?.[key]?.[locale==='tr'?0:locale==='en'?1:locale==='el'?2:3]||'';

const signGlyphs=['♈','♉','♊','♋','♌','♍','♎','♏','♐','♑','♒','♓'];
const planetGlyphs={gunes:'☉',ay:'☽',merkur:'☿',venus:'♀',mars:'♂',jupiter:'♃',saturn:'♄',uranus:'♅',neptun:'♆',pluton:'♇'};
const aspectGlyphs={kavusum:'☌',karsit:'☍',kare:'□',ucgen:'△',sekstil:'✶',quincunx:'⚻'};
const symbolFor=url=>{const slug=url.split('/').filter(Boolean).at(-1);if(url.startsWith('/burclar/'))return signGlyphs[signs.findIndex(x=>x[0]===slug)]||'✦';if(url.startsWith('/evler/'))return slug;if(url.startsWith('/gezegenler/'))return planetGlyphs[slug]||'✦';if(url.startsWith('/acilar/'))return aspectGlyphs[slug]||'◇';return url==='/transitler'?'↗':'℞'};
const L=(row,locale,i)=>locale==='tr'?row[i]:locale==='en'?row[i+1]:locale==='es'?esField(row,i):row[i+2];
const path=(p,l)=>l==='tr'?p:`/${l}${p}`;
const shell=(locale,title,description,body,canonical,schemas=[])=>`<!doctype html><html lang="${locale==='tr'?'tr-TR':locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — Mythborn</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${SITE}${path(canonical,locale)}"><link rel="alternate" hreflang="tr" href="${SITE}${path(canonical,'tr')}"><link rel="alternate" hreflang="en" href="${SITE}${path(canonical,'en')}"><link rel="alternate" hreflang="el" href="${SITE}${path(canonical,'el')}"><link rel="alternate" hreflang="es" href="${SITE}${path(canonical,'es')}"><link rel="alternate" hreflang="x-default" href="${SITE}${path(canonical,'tr')}"><link rel="stylesheet" href="/app.css"><link rel="stylesheet" href="/oracle.css"><link rel="stylesheet" href="/final.css">${schemas.map(s=>`<script type="application/ld+json">${JSON.stringify(s)}</script>`).join('')}</head><body><div class="shell"><header class="topbar"><a class="brand" href="${path('/',locale)}"><img src="/images/mythborn-emblem.png" alt=""><span>MYTHBORN</span></a><nav class="nav"><a href="${path('/astroloji',locale)}">${locale==='tr'?'Astroloji':locale==='en'?'Astrology':locale==='es'?'Astrología':'Αστρολογία'}</a><a href="${path('/astroloji-kutuphanesi',locale)}">${ui[locale].home}</a><a href="${path('/advanced-astrology',locale)}">${locale==='tr'?'Gelişmiş':locale==='tr'?'Gelişmiş':locale==='en'?'Advanced':locale==='es'?'Avanzada':'Προχωρημένα'}</a><a href="${path('/blog',locale)}">Blog</a></nav></header><main>${body}</main><footer class="footer"><span>© 2026 Mythborn</span><span>${ui[locale].note}</span></footer></div><style>.library-hero{padding:70px 0 32px}.library-hero h1,.library-page h1{font-family:Georgia,serif;font-size:clamp(44px,7vw,78px);line-height:.98;font-weight:400}.library-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;padding-bottom:70px}.library-card{padding:22px;border:1px solid rgba(255,255,255,.12);border-radius:20px;background:rgba(255,255,255,.03)}.library-card h2{font:400 clamp(25px,3vw,36px)/1.05 Georgia,serif}.library-card p,.library-page p{color:#aaa2b0;line-height:1.75}.library-page{width:min(880px,100%);margin:auto;padding:62px 0}.library-page section{padding:28px 0;border-top:1px solid rgba(255,255,255,.11)}.library-page h2{font:400 clamp(28px,4vw,44px)/1.05 Georgia,serif}.library-meta{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.library-meta span{padding:8px 12px;border:1px solid rgba(255,255,255,.12);border-radius:999px;color:#e8c883}.library-groups{display:grid;gap:28px}@media(max-width:850px){.library-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.library-grid{grid-template-columns:1fr}.library-hero,.library-page{padding-top:42px}}</style><script src="/final.js" defer></script><script src="/menu.js" defer></script></body></html>`;
const schemas=(locale,title,description,url,faq)=>[{'@context':'https://schema.org','@type':'Article',headline:title,description,inLanguage:locale==='tr'?'tr-TR':locale,url:`${SITE}${path(url,locale)}`,publisher:{'@type':'Organization',name:'Mythborn'}},{'@context':'https://schema.org','@type':'FAQPage',mainEntity:faq.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Mythborn',item:SITE},{'@type':'ListItem',position:2,name:ui[locale].home,item:`${SITE}${path('/astroloji-kutuphanesi',locale)}`},{'@type':'ListItem',position:3,name:title,item:`${SITE}${path(url,locale)}`}]}];
const genericFaq=(locale,name)=>locale==='tr'?[[`${name} tek başına yeterli mi?`,`Hayır. Yerleşim; burç, ev, açı ve haritanın bütünüyle birlikte okunmalıdır.`],[`${name} kesin kader gösterir mi?`,`Hayır. Astrolojik semboller olasılık, eğilim ve farkındalık dili sunar.`]]:locale==='en'?[[`Is ${name} enough on its own?`,`No. Read it with sign, house, aspects and the chart as a whole.`],[`Does ${name} describe fixed fate?`,`No. Astrological symbols describe tendencies and reflection themes, not certainty.`]]:locale==='es'?[[`¿Basta ${name} por sí solo?`,`No. Debe leerse junto con el signo, la casa, los aspectos y la carta completa.`],[`¿${name} describe un destino fijo?`,`No. Los símbolos astrológicos describen tendencias y temas de reflexión, no certezas.`]]:[[`Αρκεί μόνο το ${name};`,`Όχι. Χρειάζεται να διαβαστεί μαζί με ζώδιο, οίκο, όψεις και ολόκληρο τον χάρτη.`],[`Δείχνει το ${name} σταθερή μοίρα;`,`Όχι. Τα σύμβολα δείχνουν τάσεις και θέματα στοχασμού, όχι βεβαιότητα.`]];
const signFaq=(locale,item,title)=>{
 const d=signDetails[item[0]],dates=detailField(d,locale,'dates'),ruler=detailField(d,locale,'ruler'),love=detailField(d,locale,'love'),career=detailField(d,locale,'career');
 if(locale==='tr')return[
  [title+' burcu hangi tarihler arasında?','Yaklaşık '+dates+'. Sınır günlerinde Güneş’in burç değişim anı doğum yılı ve saate göre farklılaşabilir.'],
  [title+' burcunun yönetici gezegeni nedir?',ruler+'. Yönetici gezegen burcun işleyişini anlamak için sembolik bir anahtar sunar.'],
  [title+' burcu aşkta nasıldır?','İlişkilerde '+love+' temaları belirgindir; Venüs, Ay, Mars ve 7. ev kişisel ilişki tarzını ayrıntılandırır.'],
  [title+' burcu hangi işlerde güçlü olabilir?','Kariyerde '+career+' öne çıkabilir. Meslek seçimi tek başına Güneş burcuna göre yapılmamalıdır.'],
  [title+' yükseleni ile '+title+' Güneş burcu aynı şey mi?','Hayır. Güneş kimlik ve bilinçli yönü; yükselen dış dünyaya yaklaşım, ilk izlenim ve ev sisteminin başlangıcını anlatır.'],
  [title+' burcu tek başına kişiliği açıklar mı?','Hayır. Ay, yükselen, Merkür, Venüs, Mars, evler ve açılarla birlikte bütün harita değerlendirilmelidir.']
 ];
 if(locale==='en')return[
  ['What are the approximate '+title+' dates?','Approximately '+dates+'. On cusp dates, the exact Sun ingress can vary by year and birth time.'],
  ['What planet rules '+title+'?',ruler+'. The ruling planet is a symbolic key to how the sign operates.'],
  ['What is '+title+' like in relationships?','Themes include '+love+'; Venus, Moon, Mars and the 7th house add personal context.'],
  ['What career strengths are associated with '+title+'?',career+' can stand out, but career choice should not be reduced to the Sun sign alone.'],
  ['Is '+title+' rising the same as a '+title+' Sun?','No. The Sun describes identity and conscious direction; the Ascendant describes approach, presentation and the starting point of the house system.'],
  ['Does '+title+' alone explain personality?','No. Read the Moon, Ascendant, Mercury, Venus, Mars, houses and aspects with the chart as a whole.']
 ];
 if(locale==='es')return[
  ['¿Cuáles son las fechas aproximadas de '+title+'?','Aproximadamente '+dates+'. En fechas límite, el ingreso exacto del Sol puede variar según el año y la hora.'],
  ['¿Qué planeta rige '+title+'?',ruler+'. El regente es una clave simbólica para comprender el signo.'],
  ['¿Cómo es '+title+' en el amor?','Destacan '+love+'; Venus, Luna, Marte y la casa 7 añaden contexto personal.'],
  ['¿Qué fortalezas profesionales se asocian con '+title+'?',career+' puede destacar, pero una profesión no debe elegirse solo por el signo solar.'],
  ['¿Ascendente '+title+' es igual a Sol en '+title+'?','No. El Sol describe identidad y dirección consciente; el Ascendente describe enfoque, presentación e inicio de las casas.'],
  ['¿'+title+' explica toda la personalidad?','No. Conviene leer Luna, Ascendente, Mercurio, Venus, Marte, casas y aspectos en conjunto.']
 ];
 return[
  ['Ποιες είναι περίπου οι ημερομηνίες του '+title+';','Περίπου '+dates+'. Στις οριακές ημερομηνίες η ακριβής είσοδος του Ήλιου αλλάζει ανά έτος και ώρα γέννησης.'],
  ['Ποιος πλανήτης κυβερνά το '+title+';',ruler+'. Ο κυβερνήτης είναι συμβολικό κλειδί για τον τρόπο λειτουργίας του ζωδίου.'],
  ['Πώς είναι το '+title+' στις σχέσεις;','Κύρια θέματα: '+love+'. Αφροδίτη, Σελήνη, Άρης και 7ος οίκος προσθέτουν προσωπικό πλαίσιο.'],
  ['Ποια επαγγελματικά δυνατά σημεία συνδέονται με το '+title+';',career+' μπορεί να ξεχωρίζει, αλλά η καριέρα δεν βασίζεται μόνο στο ζώδιο του Ήλιου.'],
  ['Είναι ίδιος ο Ωροσκόπος '+title+' με Ήλιο στο '+title+';','Όχι. Ο Ήλιος αφορά ταυτότητα και συνειδητή κατεύθυνση, ενώ ο Ωροσκόπος προσέγγιση και πρώτη εντύπωση.'],
  ['Αρκεί το '+title+' για να εξηγήσει την προσωπικότητα;','Όχι. Χρειάζονται Σελήνη, Ωροσκόπος, Ερμής, Αφροδίτη, Άρης, οίκοι και όψεις μαζί.']
 ];
};
const signExtra=(locale,item,title,meta)=>{
 const d=signDetails[item[0]],dates=detailField(d,locale,'dates'),ruler=detailField(d,locale,'ruler'),love=detailField(d,locale,'love'),career=detailField(d,locale,'career'),money=detailField(d,locale,'money'),communication=detailField(d,locale,'communication');
 const h=locale==='tr'?{profile:'Hızlı profil',ruler:'Yönetici',love:'Aşk ve ilişkiler',career:'Kariyer ve çalışma biçimi',money:'Para ve kaynak yönetimi',communication:'İletişim tarzı',placements:'Güneş, Ay ve Yükselen farkı',chart:'Doğum haritasında nasıl okunur?',deeper:'Daha derine in',calc:'Doğum haritanı hesapla',year:'2027 yıllık rehberi',syn:'Sinastri hesapla'}:locale==='en'?{profile:'Quick profile',ruler:'Ruler',love:'Love and relationships',career:'Career and work style',money:'Money and resources',communication:'Communication style',placements:'Sun, Moon and Rising',chart:'How to read it in a birth chart',deeper:'Go deeper',calc:'Calculate your birth chart',year:'2027 guide',syn:'Calculate synastry'}:locale==='es'?{profile:'Perfil rápido',ruler:'Regente',love:'Amor y relaciones',career:'Carrera y estilo de trabajo',money:'Dinero y recursos',communication:'Estilo de comunicación',placements:'Sol, Luna y Ascendente',chart:'Cómo leerlo en la carta natal',deeper:'Profundiza',calc:'Calcula tu carta natal',year:'Guía 2027',syn:'Calcula sinastría'}:{profile:'Γρήγορο προφίλ',ruler:'Κυβερνήτης',love:'Αγάπη και σχέσεις',career:'Καριέρα και τρόπος εργασίας',money:'Χρήματα και πόροι',communication:'Τρόπος επικοινωνίας',placements:'Ήλιος, Σελήνη και Ωροσκόπος',chart:'Πώς διαβάζεται στον γενέθλιο χάρτη',deeper:'Πήγαινε βαθύτερα',calc:'Υπολόγισε τον γενέθλιο χάρτη σου',year:'Οδηγός 2027',syn:'Υπολόγισε συναστρία'};
 const placements=locale==='tr'?title+' Güneş burcu kimlik, canlılık ve bilinçli yönü; '+title+' Ay burcu duygusal güvenlik ve alışkanlıkları; '+title+' yükseleni ise hayata yaklaşım, ilk izlenim ve ev sisteminin başlangıcını anlatır. Aynı burç üç farklı konumda oldukça farklı çalışabilir.':locale==='en'?'A '+title+' Sun describes identity, vitality and conscious direction; a '+title+' Moon emotional security and habits; '+title+' rising approach, first impression and the starting point of the house system. The same sign can function differently in each position.':locale==='es'?'Sol en '+title+' describe identidad y dirección consciente; Luna en '+title+', seguridad emocional y hábitos; Ascendente '+title+', enfoque, primera impresión e inicio del sistema de casas. El mismo signo funciona de manera distinta en cada posición.':'Ήλιος στο '+title+': ταυτότητα και συνειδητή κατεύθυνση· Σελήνη στο '+title+': συναισθηματική ασφάλεια και συνήθειες· Ωροσκόπος '+title+': προσέγγιση, πρώτη εντύπωση και αρχή των οίκων.';
 const chart=locale==='tr'?'Haritada '+title+' yalnızca Güneş burcu olarak değil, hangi evde bulunduğu, bu burçta hangi gezegenlerin yer aldığı ve yönetici gezegenin konumu üzerinden de okunur. Tek cümlelik “'+title+' insanı şöyledir” genellemeleri haritanın büyük bölümünü dışarıda bırakır.':locale==='en'?title+' is read not only as a Sun sign but through the house it occupies, planets placed there and the condition of its ruler. One-line personality claims leave out most of the chart.':locale==='es'?title+' no se lee solo como signo solar, sino por la casa que ocupa, los planetas allí y el estado de su regente. Las generalizaciones de una frase dejan fuera gran parte de la carta.':'Το '+title+' διαβάζεται όχι μόνο ως Ήλιος αλλά και μέσω του οίκου, των πλανητών εκεί και της κατάστασης του κυβερνήτη. Οι μονολεκτικές γενικεύσεις αφήνουν έξω το μεγαλύτερο μέρος του χάρτη.';
 const careerNote=locale==='tr'?' Meslek uygunluğu için 2., 6. ve 10. evler, MC, Satürn ve haritanın bütünündeki yetenek göstergeleri birlikte değerlendirilmelidir.':locale==='en'?' For career fit, read the 2nd, 6th and 10th houses, MC, Saturn and the wider talent pattern together.':locale==='es'?' Para orientación profesional conviene leer casas 2, 6 y 10, MC, Saturno y el patrón global de talentos.':' Για επαγγελματική κατεύθυνση χρειάζονται 2ος, 6ος και 10ος οίκος, MC, Κρόνος και συνολικό μοτίβο ταλέντων.';
 const moneyNote=locale==='tr'?' Finansal kararlar astrolojik işaretlere göre değil bütçe, risk, gelir ve gerçek koşullara göre verilmelidir.':locale==='en'?' Financial decisions should rely on budgets, risk, income and real conditions rather than astrological signals.':locale==='es'?' Las decisiones financieras deben basarse en presupuesto, riesgo, ingresos y condiciones reales.':' Οι οικονομικές αποφάσεις πρέπει να βασίζονται σε προϋπολογισμό, κίνδυνο, εισόδημα και πραγματικές συνθήκες.';
 return '<section><h2>'+h.profile+'</h2><div class="library-meta sign-facts"><span>'+esc(dates)+'</span><span>'+h.ruler+': '+esc(ruler)+'</span><span>'+esc(meta[0]||'')+'</span><span>'+esc(meta[1]||'')+'</span></div></section>'+
 '<section><h2>'+h.love+'</h2><p>'+esc(love)+'.</p></section>'+
 '<section><h2>'+h.career+'</h2><p>'+esc(career)+'.'+careerNote+'</p></section>'+
 '<section><h2>'+h.money+'</h2><p>'+esc(money)+'.'+moneyNote+'</p></section>'+
 '<section><h2>'+h.communication+'</h2><p>'+esc(communication)+'.</p></section>'+
 '<section><h2>'+h.placements+'</h2><p>'+esc(placements)+'</p></section>'+
 '<section><h2>'+h.chart+'</h2><p>'+esc(chart)+'</p></section>'+
 '<section class="sign-deep-links"><h2>'+h.deeper+'</h2><div class="article-links"><a href="'+path('/astroloji',locale)+'">'+h.calc+' →</a><a href="'+path('/blog/'+item[0]+'-burcu-2027-yillik-yorum',locale)+'">'+title+' '+h.year+' →</a><a href="'+path('/sinastri',locale)+'">'+h.syn+' →</a></div></section>';
};

export const libraryRoutes=['/astroloji-kutuphanesi',...signs.map(x=>`/burclar/${x[0]}`),...houses.map(x=>`/evler/${x[0]}`),...planets.map(x=>`/gezegenler/${x[0]}`),...aspects.map(x=>`/acilar/${x[0]}`),'/transitler','/retro-hareketler'];
export const astrologySearchItems=locale=>{
 const description=locale==='tr'?'Doğum haritası ve astroloji rehberi.':locale==='en'?'Birth-chart and astrology guide.':locale==='es'?'Guía de carta natal y astrología.':'Οδηγός γενέθλιου χάρτη και αστρολογίας.';
 return[
  ...signs.map(item=>({title:L(item,locale,1),description,category:'astrology',path:`/burclar/${item[0]}`})),
  ...houses.map(item=>({title:`${locale==='tr'?`${item[0]}. Ev`:locale==='en'?`House ${item[0]}`:locale==='es'?`Casa ${item[0]}`:`${item[0]}. Οίκος`} — ${L(item,locale,1)}`,description,category:'astrology',path:`/evler/${item[0]}`})),
  ...planets.map(item=>({title:L(item,locale,1),description:L(item,locale,4),category:'astrology',path:`/gezegenler/${item[0]}`})),
  ...aspects.map(item=>({title:L(item,locale,1),description:L(item,locale,4),category:'astrology',path:`/acilar/${item[0]}`})),
  {title:locale==='tr'?'Transitler':locale==='en'?'Transits':locale==='es'?'Tránsitos':'Διελεύσεις',description,category:'astrology',path:'/transitler'},
  {title:locale==='tr'?'Retro Hareketler':locale==='en'?'Retrograde Motion':locale==='es'?'Movimiento retrógrado':'Ανάδρομη Κίνηση',description,category:'astrology',path:'/retro-hareketler'}
 ]};
export function libraryPage(route,locale='tr'){
 const t=ui[locale];
 if(route==='/astroloji-kutuphanesi'){
  const groups=[[locale==='tr'?'12 Burç':locale==='en'?'12 Signs':locale==='es'?'12 Signos':'12 Ζώδια',signs.map(x=>[L(x,locale,1),`/burclar/${x[0]}`,L(x,locale,10)])],[locale==='tr'?'12 Ev':locale==='en'?'12 Houses':locale==='es'?'12 Casas':'12 Οίκοι',houses.map(x=>[locale==='tr'?`${x[0]}. Ev`:locale==='en'?`House ${x[0]}`:locale==='es'?`Casa ${x[0]}`:`${x[0]}ος Οίκος`,`/evler/${x[0]}`,L(x,locale,1)])],[locale==='tr'?'Gezegenler':locale==='en'?'Planets':locale==='es'?'Planetas':'Πλανήτες',planets.map(x=>[L(x,locale,1),`/gezegenler/${x[0]}`,L(x,locale,4)])],[locale==='tr'?'Açılar ve Zamanlama':locale==='en'?'Aspects and Timing':locale==='es'?'Aspectos y tiempo':'Όψεις και Χρονισμός',[...aspects.map(x=>[L(x,locale,1),`/acilar/${x[0]}`,L(x,locale,4)]),[locale==='tr'?'Transitler':locale==='en'?'Transits':locale==='es'?'Tránsitos':'Διελεύσεις','/transitler',locale==='tr'?'Güncel gökyüzünün doğum haritasıyla teması.':locale==='en'?'How the current sky contacts the birth chart.':locale==='es'?'Cómo el cielo actual entra en contacto con la carta natal.':'Πώς ο τρέχων ουρανός αγγίζει τον γενέθλιο χάρτη.'],[locale==='tr'?'Retro Hareketler':locale==='en'?'Retrogrades':locale==='es'?'Movimientos retrógrados':'Ανάδρομες Κινήσεις','/retro-hareketler',locale==='tr'?'Gözden geçirme, içe dönüş ve yeniden düzenleme döngüleri.':locale==='en'?'Cycles of review, internalization and revision.':locale==='es'?'Ciclos de revisión, interiorización y reajuste.':'Κύκλοι επανεξέτασης, εσωτερίκευσης και αναθεώρησης.']]]];
  const searchLabel=locale==='tr'?'Kütüphanede ara':locale==='en'?'Search the library':locale==='es'?'Buscar en la biblioteca':'Αναζήτηση στη βιβλιοθήκη';
  const body=`<section class="library-hero"><p class="eyebrow">MYTHBORN · ${t.home.toUpperCase()}</p><h1>${t.home}</h1><p class="lead left-lead">${t.intro}</p></section><div class="library-search-tools"><label><span class="sr-only">${searchLabel}</span><input type="search" data-library-search placeholder="${searchLabel}"></label></div><nav class="library-quick-nav" aria-label="${searchLabel}">${groups.map(([h],index)=>`<a href="#library-group-${index+1}">${h}</a>`).join('')}</nav><div class="library-groups">${groups.map(([h,items],index)=>`<section id="library-group-${index+1}"><h2>${h}</h2><div class="library-grid">${items.map(([n,u,d])=>`<article class="library-card" data-library-item><span class="library-card-symbol" aria-hidden="true">${symbolFor(u)}</span><h2>${esc(n)}</h2><p>${esc(d)}</p><a href="${path(u,locale)}">${t.read} →</a></article>`).join('')}</div></section>`).join('')}</div>`;
  return shell(locale,t.home,t.intro,body,route,[{'@context':'https://schema.org','@type':'CollectionPage',name:t.home,description:t.intro,url:`${SITE}${path(route,locale)}`,inLanguage:locale==='tr'?'tr-TR':locale}]);
 }
 let item,type,title,meaning,meta=[];
 if(route.startsWith('/burclar/')){item=signs.find(x=>route.endsWith('/'+x[0]));if(item){type='sign';title=L(item,locale,1);meaning=L(item,locale,10);meta=[L(item,locale,4),L(item,locale,7)]}}
 if(route.startsWith('/evler/')){item=houses.find(x=>route.endsWith('/'+x[0]));if(item){type='house';title=locale==='tr'?`${item[0]}. Ev`:locale==='en'?`House ${item[0]}`:locale==='es'?`Casa ${item[0]}`:`${item[0]}ος Οίκος`;meaning=L(item,locale,1)}}
 if(route.startsWith('/gezegenler/')){item=planets.find(x=>route.endsWith('/'+x[0]));if(item){type='planet';title=L(item,locale,1);meaning=L(item,locale,4)}}
 if(route.startsWith('/acilar/')){item=aspects.find(x=>route.endsWith('/'+x[0]));if(item){type='aspect';title=L(item,locale,1);meaning=L(item,locale,4)}}
 if(route==='/transitler'){title=locale==='tr'?'Transitler':locale==='en'?'Transits':locale==='es'?'Tránsitos':'Διελεύσεις';meaning=locale==='tr'?'Güncel gezegenlerin doğum haritasındaki gezegen, açı ve evlerle kurduğu geçici temaslardır.':locale==='en'?'Temporary contacts between current planets and natal planets, angles and houses.':locale==='es'?'Contactos temporales entre los planetas actuales y los planetas, ángulos y casas natales.':'Προσωρινές επαφές των τρεχόντων πλανητών με γενέθλιους πλανήτες, γωνίες και οίκους.';type='timing'}
 if(route==='/retro-hareketler'){title=locale==='tr'?'Retro Hareketler':locale==='en'?'Retrogrades':locale==='es'?'Movimientos retrógrados':'Ανάδρομες Κινήσεις';meaning=locale==='tr'?'Dünya merkezli bakışta gezegenin gökyüzünde geri gidiyormuş gibi görünmesidir; astrolojide gözden geçirme ve içe yönelimle ilişkilendirilir.':locale==='en'?'The apparent backward motion of a planet from Earth; astrologically associated with review and internalization.':locale==='es'?'El movimiento aparente hacia atrás de un planeta visto desde la Tierra; en astrología se asocia con revisión e interiorización.':'Η φαινομενική οπισθοδρόμηση ενός πλανήτη από τη Γη· αστρολογικά συνδέεται με επανεξέταση και εσωτερίκευση.';type='timing'}
 if(!title)return null;
 const faq=type==='sign'?signFaq(locale,item,title):genericFaq(locale,title);
 let light,shadow,question;
 if(type==='sign'){light=locale==='tr'?`${meaning}; kişinin bu niteliği bilinçli, yaratıcı ve ilişkisel biçimde kullanması.`:locale==='en'?`${meaning}; using this quality consciously, creatively and relationally.`:locale==='es'?`${meaning}; usar esta cualidad de forma consciente, creativa y relacional.`:`${meaning}· συνειδητή, δημιουργική και σχεσιακή χρήση αυτής της ποιότητας.`;shadow=L(item,locale,13);question=locale==='tr'?`Bu burcun güçlü tarafını kullanırken hangi gölgeye kayıyorum?`:locale==='en'?`Which shadow do I slip into while using this sign’s strength?`:locale==='es'?`¿En qué sombra caigo al usar la fortaleza de este signo?`:`Σε ποια σκιά γλιστρώ όταν χρησιμοποιώ τη δύναμη αυτού του ζωδίου;`}
 else {light=locale==='tr'?`${meaning} alanını bilinçli seçim, ölçülülük ve gerçek hayat verileriyle geliştirmek.`:locale==='en'?`Developing ${meaning} through conscious choice, proportion and real-life evidence.`:locale==='es'?`Desarrollar ${meaning} mediante elección consciente, proporción y datos de la vida real.`:`Ανάπτυξη του πεδίου «${meaning}» με συνειδητή επιλογή, μέτρο και πραγματικά δεδομένα.`;shadow=locale==='tr'?'Tek bir yerleşimi mutlaklaştırmak, korku dili kullanmak veya gerçek koşulları yok saymak.':locale==='en'?'Absolutizing one placement, using fear-based language or ignoring real conditions.':locale==='es'?'Absolutizar una sola posición, usar lenguaje basado en el miedo o ignorar las condiciones reales.':'Απολυτοποίηση μίας θέσης, γλώσσα φόβου ή αγνόηση πραγματικών συνθηκών.';question=locale==='tr'?'Bu sembolü bugün hangi somut davranışla daha dengeli yaşayabilirim?':locale==='en'?'What concrete behaviour would express this symbol more constructively today?':locale==='es'?'¿Qué conducta concreta expresaría hoy este símbolo de forma más constructiva?':'Ποια συγκεκριμένη συμπεριφορά θα εξέφραζε πιο δημιουργικά αυτό το σύμβολο σήμερα;'}
 const symbol=symbolFor(route),example=locale==='tr'?`Günlük yaşamda ${meaning} temasını gözlenebilir bir seçimle ifade et; sonucu varsaymak yerine davranış ve bağlamı birlikte değerlendir.`:locale==='en'?`Express ${meaning} through one observable choice in daily life, reading behaviour and context together rather than assuming an outcome.`:locale==='es'?`Expresa ${meaning} mediante una elección observable en la vida diaria, leyendo juntos el comportamiento y el contexto en lugar de asumir un resultado.`:`Έκφρασε το θέμα «${meaning}» με μία παρατηρήσιμη επιλογή στην καθημερινότητα, συνδυάζοντας συμπεριφορά και πλαίσιο.`;
 const body=`<article class="library-page premium-detail"><a href="${path('/astroloji-kutuphanesi',locale)}">← ${t.home}</a><div class="premium-detail-hero"><span class="premium-detail-symbol" aria-hidden="true">${symbol}</span><div><p class="eyebrow">MYTHBORN · ${t.home.toUpperCase()}</p><h1>${esc(title)}</h1>${meta.length?`<div class="library-meta">${meta.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}<p class="article-lead">${esc(meaning)}</p></div></div><div class="premium-detail-body"><section><h2>${t.meaning}</h2><p>${esc(meaning)} ${locale==='tr'?'Haritadaki gerçek işlevi, bulunduğu burç, ev ve yaptığı açılarla birlikte değerlendirilir.':locale==='en'?'Its actual chart function depends on sign, house and aspects.':locale==='es'?'Su función real en la carta depende del signo, la casa y los aspectos.':'Η πραγματική λειτουργία στον χάρτη εξαρτάται από ζώδιο, οίκο και όψεις.'}</p></section>${type==='sign'?signExtra(locale,item,title,meta):''}<section><h2>${t.light}</h2><p>${esc(light)}</p></section><section><h2>${t.shadow}</h2><p>${esc(shadow)}</p></section><section><h2>${t.practice}</h2><p>${esc(question)}</p></section><section><h2>${locale==='tr'?'Pratik örnek':locale==='en'?'Practical example':locale==='es'?'Ejemplo práctico':'Πρακτικό παράδειγμα'}</h2><p>${esc(example)}</p></section><section class="article-faq"><p class="eyebrow">${t.faq.toUpperCase()}</p>${faq.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</section></div><p class="article-note">${t.note}</p></article>`;
 return shell(locale,title,meaning,body,route,schemas(locale,title,meaning,route,faq));
}
