const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const SITE='https://mythborn.co';
const ui={tr:{home:'Doğum Haritası Kütüphanesi',intro:'Burçlar, evler, gezegenler, açılar, transitler ve retro hareketler için üç katmanlı başvuru merkezi.',read:'Rehberi aç',meaning:'Temel anlam',light:'Yapıcı ifade',shadow:'Gölge ifade',practice:'Kendine sor',faq:'Sık sorulanlar',note:'Bu içerik eğitim ve kişisel farkındalık amaçlıdır; bilimsel tanı veya kesin gelecek öngörüsü değildir.'},en:{home:'Birth Chart Library',intro:'A structured reference centre for signs, houses, planets, aspects, transits and retrogrades.',read:'Open guide',meaning:'Core meaning',light:'Constructive expression',shadow:'Shadow expression',practice:'Ask yourself',faq:'Frequently asked questions',note:'This content is for education and personal reflection; it is not scientific diagnosis or certain prediction.'},el:{home:'Βιβλιοθήκη Γενέθλιου Χάρτη',intro:'Δομημένο κέντρο αναφοράς για ζώδια, οίκους, πλανήτες, όψεις, διελεύσεις και ανάδρομες κινήσεις.',read:'Άνοιγμα οδηγού',meaning:'Βασικό νόημα',light:'Δημιουργική έκφραση',shadow:'Σκιώδης έκφραση',practice:'Ρώτησε τον εαυτό σου',faq:'Συχνές ερωτήσεις',note:'Το περιεχόμενο είναι για εκπαίδευση και προσωπικό στοχασμό· δεν αποτελεί επιστημονική διάγνωση ή βέβαιη πρόβλεψη.'}};
const signs=[
['koc','Koç','Aries','Κριός','Ateş','Fire','Φωτιά','Öncü','Cardinal','Παρορμητικό','başlatmak, cesaret ve doğrudan hareket','initiation, courage and direct action','έναρξη, θάρρος και άμεση δράση','acelecilik ve yalnız hareket etme eğilimi','impatience and acting alone','βιασύνη και τάση για μοναχική δράση'],
['boga','Boğa','Taurus','Ταύρος','Toprak','Earth','Γη','Sabit','Fixed','Σταθερό','istikrar, değerler ve bedensel güven','stability, values and embodied security','σταθερότητα, αξίες και σωματική ασφάλεια','inat, değişime direnç ve sahiplenme','stubbornness, resistance to change and possessiveness','πείσμα, αντίσταση στην αλλαγή και κτητικότητα'],
['ikizler','İkizler','Gemini','Δίδυμοι','Hava','Air','Αέρας','Değişken','Mutable','Μεταβλητό','merak, dil ve bağlantı kurma','curiosity, language and connection','περιέργεια, γλώσσα και σύνδεση','dağılma, yüzeysellik ve zihinsel aşırı yük','scattering, superficiality and mental overload','διάσπαση, επιφανειακότητα και νοητική υπερφόρτωση'],
['yengec','Yengeç','Cancer','Καρκίνος','Su','Water','Νερό','Öncü','Cardinal','Παρορμητικό','aidiyet, bakım ve duygusal güven','belonging, care and emotional safety','ανήκειν, φροντίδα και συναισθηματική ασφάλεια','alınganlık, içe kapanma ve aşırı koruma','sensitivity, withdrawal and overprotection','ευαισθησία, απόσυρση και υπερπροστασία'],
['aslan','Aslan','Leo','Λέων','Ateş','Fire','Φωτιά','Sabit','Fixed','Σταθερό','yaratıcılık, görünürlük ve kalpten ifade','creativity, visibility and heartfelt expression','δημιουργικότητα, ορατότητα και έκφραση από καρδιάς','gurur, dramatizasyon ve onay ihtiyacı','pride, dramatization and need for approval','υπερηφάνεια, δραματοποίηση και ανάγκη επιβεβαίωσης'],
['basak','Başak','Virgo','Παρθένος','Toprak','Earth','Γη','Değişken','Mutable','Μεταβλητό','ayıklama, hizmet ve işleyen sistemler','discernment, service and workable systems','διάκριση, υπηρεσία και λειτουργικά συστήματα','mükemmeliyetçilik, eleştiri ve kaygı','perfectionism, criticism and anxiety','τελειομανία, κριτική και άγχος'],
['terazi','Terazi','Libra','Ζυγός','Hava','Air','Αέρας','Öncü','Cardinal','Παρορμητικό','denge, ilişki ve adil müzakere','balance, relationship and fair negotiation','ισορροπία, σχέση και δίκαιη διαπραγμάτευση','kararsızlık, hoşnut etme ve çatışmadan kaçınma','indecision, people-pleasing and conflict avoidance','αναποφασιστικότητα, ευχαρίστηση των άλλων και αποφυγή σύγκρουσης'],
['akrep','Akrep','Scorpio','Σκορπιός','Su','Water','Νερό','Sabit','Fixed','Σταθερό','derinlik, dönüşüm ve duygusal dürüstlük','depth, transformation and emotional honesty','βάθος, μεταμόρφωση και συναισθηματική ειλικρίνεια','kontrol, kuşku ve yoğunluğu mutlaklaştırma','control, suspicion and absolutizing intensity','έλεγχος, καχυποψία και απολυτοποίηση της έντασης'],
['yay','Yay','Sagittarius','Τοξότης','Ateş','Fire','Φωτιά','Değişken','Mutable','Μεταβλητό','anlam, keşif ve geniş perspektif','meaning, exploration and broad perspective','νόημα, εξερεύνηση και ευρεία οπτική','abartı, sabırsızlık ve detay atlama','exaggeration, restlessness and skipping detail','υπερβολή, ανησυχία και παράλειψη λεπτομερειών'],
['oglak','Oğlak','Capricorn','Αιγόκερως','Toprak','Earth','Γη','Öncü','Cardinal','Παρορμητικό','sorumluluk, yapı ve uzun vadeli emek','responsibility, structure and long-term effort','ευθύνη, δομή και μακροπρόθεσμη προσπάθεια','katılık, aşırı yüklenme ve başarıyla özdeşleşme','rigidity, overwork and identification with achievement','ακαμψία, υπερκόπωση και ταύτιση με την επίτευξη'],
['kova','Kova','Aquarius','Υδροχόος','Hava','Air','Αέρας','Sabit','Fixed','Σταθερό','özgünlük, topluluk ve sistem değişimi','originality, community and systems change','πρωτοτυπία, κοινότητα και αλλαγή συστημάτων','mesafe, inatçı fikirler ve duygudan kopma','distance, fixed ideas and emotional detachment','απόσταση, άκαμπτες ιδέες και συναισθηματική αποσύνδεση'],
['balik','Balık','Pisces','Ιχθύες','Su','Water','Νερό','Değişken','Mutable','Μεταβλητό','sezgi, şefkat ve sınırlar arası algı','intuition, compassion and porous perception','διαίσθηση, συμπόνια και πορώδης αντίληψη','kaçış, belirsiz sınırlar ve idealizasyon','escape, blurred boundaries and idealization','φυγή, ασαφή όρια και εξιδανίκευση']];
const houses=[['1','Benlik ve başlangıçlar','Self and beginnings','Εαυτός και ξεκινήματα'],['2','Kaynaklar, para ve değerler','Resources, money and values','Πόροι, χρήματα και αξίες'],['3','Öğrenme, iletişim ve yakın çevre','Learning, communication and local environment','Μάθηση, επικοινωνία και κοντινό περιβάλλον'],['4','Kökler, ev ve iç güvenlik','Roots, home and inner security','Ρίζες, σπίτι και εσωτερική ασφάλεια'],['5','Yaratıcılık, aşk ve oyun','Creativity, romance and play','Δημιουργικότητα, έρωτας και παιχνίδι'],['6','Günlük düzen, emek ve sağlık alışkanlıkları','Daily routines, work and health habits','Καθημερινότητα, εργασία και συνήθειες υγείας'],['7','İlişkiler, ortaklık ve yansıtma','Relationships, partnership and projection','Σχέσεις, συνεργασία και προβολή'],['8','Paylaşılan kaynaklar, kriz ve dönüşüm','Shared resources, crisis and transformation','Κοινοί πόροι, κρίση και μεταμόρφωση'],['9','İnançlar, yüksek öğrenim ve uzak ufuklar','Beliefs, higher learning and distant horizons','Πεποιθήσεις, ανώτερη μάθηση και μακρινοί ορίζοντες'],['10','Kariyer, yön ve kamusal rol','Career, direction and public role','Καριέρα, κατεύθυνση και δημόσιος ρόλος'],['11','Topluluk, gelecek ve kolektif hedefler','Community, future and collective goals','Κοινότητα, μέλλον και συλλογικοί στόχοι'],['12','İçe dönüş, bilinçdışı ve kapanışlar','Retreat, unconscious patterns and endings','Εσωστρέφεια, ασυνείδητα μοτίβα και ολοκληρώσεις']];
const planets=[['gunes','Güneş','Sun','Ήλιος','kimlik, canlılık ve bilinçli yön','identity, vitality and conscious direction','ταυτότητα, ζωτικότητα και συνειδητή κατεύθυνση'],['ay','Ay','Moon','Σελήνη','duygusal ihtiyaçlar, alışkanlıklar ve güven','emotional needs, habits and safety','συναισθηματικές ανάγκες, συνήθειες και ασφάλεια'],['merkur','Merkür','Mercury','Ερμής','zihin, dil ve bilgi işleme','mind, language and information processing','νους, γλώσσα και επεξεργασία πληροφοριών'],['venus','Venüs','Venus','Αφροδίτη','değer, ilişki ve çekim','values, relating and attraction','αξίες, σχέσεις και έλξη'],['mars','Mars','Mars','Άρης','istek, eylem ve sınır koyma','desire, action and boundary-setting','επιθυμία, δράση και όρια'],['jupiter','Jüpiter','Jupiter','Δίας','büyüme, anlam ve inanç','growth, meaning and belief','ανάπτυξη, νόημα και πίστη'],['saturn','Satürn','Saturn','Κρόνος','sorumluluk, yapı ve zaman','responsibility, structure and time','ευθύνη, δομή και χρόνος'],['uranus','Uranüs','Uranus','Ουρανός','özgürleşme, değişim ve uyanış','liberation, disruption and awakening','απελευθέρωση, ανατροπή και αφύπνιση'],['neptun','Neptün','Neptune','Ποσειδώνας','hayal, sezgi ve çözülme','imagination, intuition and dissolution','φαντασία, διαίσθηση και διάλυση'],['pluton','Plüton','Pluto','Πλούτωνας','güç, gölge ve dönüşüm','power, shadow and transformation','δύναμη, σκιά και μεταμόρφωση']];
const aspects=[['kavusum','Kavuşum','Conjunction','Σύνοδος','iki işlevin aynı alanda yoğunlaşması','two functions concentrating in the same field','δύο λειτουργίες συγκεντρώνονται στο ίδιο πεδίο'],['karsit','Karşıt','Opposition','Αντίθεση','iki kutup arasında farkındalık ve denge','awareness and balance between two poles','επίγνωση και ισορροπία ανάμεσα σε δύο πόλους'],['kare','Kare','Square','Τετράγωνο','gerilim yoluyla eylem ve gelişim','action and growth through friction','δράση και ανάπτυξη μέσω έντασης'],['ucgen','Üçgen','Trine','Τρίγωνο','doğal akış, yetenek ve kolaylık','natural flow, talent and ease','φυσική ροή, ταλέντο και ευκολία'],['sekstil','Sekstil','Sextile','Εξάγωνο','fırsat, iş birliği ve geliştirilebilir potansiyel','opportunity, cooperation and developable potential','ευκαιρία, συνεργασία και αναπτύξιμο δυναμικό'],['quincunx','150° Quincunx','Quincunx','Χιαστί 150°','uyumsuz ihtiyaçlar arasında sürekli ayar','ongoing adjustment between mismatched needs','συνεχής προσαρμογή ανάμεσα σε ασύμβατες ανάγκες']];
const L=(row,locale,i)=>locale==='tr'?row[i]:locale==='en'?row[i+1]:row[i+2];
const path=(p,l)=>l==='tr'?p:`/${l}${p}`;
const shell=(locale,title,description,body,canonical,schemas=[])=>`<!doctype html><html lang="${locale==='tr'?'tr-TR':locale}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — Mythborn</title><meta name="description" content="${esc(description)}"><link rel="canonical" href="${SITE}${path(canonical,locale)}"><link rel="alternate" hreflang="tr" href="${SITE}${path(canonical,'tr')}"><link rel="alternate" hreflang="en" href="${SITE}${path(canonical,'en')}"><link rel="alternate" hreflang="el" href="${SITE}${path(canonical,'el')}"><link rel="alternate" hreflang="x-default" href="${SITE}${path(canonical,'tr')}"><link rel="stylesheet" href="/app.css"><link rel="stylesheet" href="/oracle.css"><link rel="stylesheet" href="/final.css">${schemas.map(s=>`<script type="application/ld+json">${JSON.stringify(s)}</script>`).join('')}</head><body><div class="shell"><header class="topbar"><a class="brand" href="${path('/',locale)}"><img src="/images/mythborn-emblem.png" alt=""><span>MYTHBORN</span></a><nav class="nav"><a href="${path('/astroloji',locale)}">${locale==='tr'?'Astroloji':locale==='en'?'Astrology':'Αστρολογία'}</a><a href="${path('/astroloji-kutuphanesi',locale)}">${ui[locale].home}</a><a href="${path('/advanced-astrology',locale)}">${locale==='tr'?'Gelişmiş':locale==='en'?'Advanced':'Προχωρημένα'}</a><a href="${path('/blog',locale)}">Blog</a></nav></header><main>${body}</main><footer class="footer"><span>© 2026 Mythborn</span><span>${ui[locale].note}</span></footer></div><style>.library-hero{padding:70px 0 32px}.library-hero h1,.library-page h1{font-family:Georgia,serif;font-size:clamp(44px,7vw,78px);line-height:.98;font-weight:400}.library-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;padding-bottom:70px}.library-card{padding:22px;border:1px solid rgba(255,255,255,.12);border-radius:20px;background:rgba(255,255,255,.03)}.library-card h2{font:400 clamp(25px,3vw,36px)/1.05 Georgia,serif}.library-card p,.library-page p{color:#aaa2b0;line-height:1.75}.library-page{width:min(880px,100%);margin:auto;padding:62px 0}.library-page section{padding:28px 0;border-top:1px solid rgba(255,255,255,.11)}.library-page h2{font:400 clamp(28px,4vw,44px)/1.05 Georgia,serif}.library-meta{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.library-meta span{padding:8px 12px;border:1px solid rgba(255,255,255,.12);border-radius:999px;color:#e8c883}.library-groups{display:grid;gap:28px}@media(max-width:850px){.library-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.library-grid{grid-template-columns:1fr}.library-hero,.library-page{padding-top:42px}}</style><script src="/final.js" defer></script><script src="/menu.js" defer></script></body></html>`;
const schemas=(locale,title,description,url,faq)=>[{'@context':'https://schema.org','@type':'Article',headline:title,description,inLanguage:locale==='tr'?'tr-TR':locale,url:`${SITE}${path(url,locale)}`,publisher:{'@type':'Organization',name:'Mythborn'}},{'@context':'https://schema.org','@type':'FAQPage',mainEntity:faq.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))},{'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Mythborn',item:SITE},{'@type':'ListItem',position:2,name:ui[locale].home,item:`${SITE}${path('/astroloji-kutuphanesi',locale)}`},{'@type':'ListItem',position:3,name:title,item:`${SITE}${path(url,locale)}`}]}];
const genericFaq=(locale,name)=>locale==='tr'?[[`${name} tek başına yeterli mi?`,`Hayır. Yerleşim; burç, ev, açı ve haritanın bütünüyle birlikte okunmalıdır.`],[`${name} kesin kader gösterir mi?`,`Hayır. Astrolojik semboller olasılık, eğilim ve farkındalık dili sunar.`]]:locale==='en'?[[`Is ${name} enough on its own?`,`No. Read it with sign, house, aspects and the chart as a whole.`],[`Does ${name} describe fixed fate?`,`No. Astrological symbols describe tendencies and reflection themes, not certainty.`]]:[[`Αρκεί μόνο το ${name};`,`Όχι. Χρειάζεται να διαβαστεί μαζί με ζώδιο, οίκο, όψεις και ολόκληρο τον χάρτη.`],[`Δείχνει το ${name} σταθερή μοίρα;`,`Όχι. Τα σύμβολα δείχνουν τάσεις και θέματα στοχασμού, όχι βεβαιότητα.`]];
export const libraryRoutes=['/astroloji-kutuphanesi',...signs.map(x=>`/burclar/${x[0]}`),...houses.map(x=>`/evler/${x[0]}`),...planets.map(x=>`/gezegenler/${x[0]}`),...aspects.map(x=>`/acilar/${x[0]}`),'/transitler','/retro-hareketler'];
export const astrologySearchItems=locale=>{
 const index=locale==='tr'?1:locale==='en'?2:3,description=locale==='tr'?'Doğum haritası ve astroloji rehberi.':locale==='en'?'Birth-chart and astrology guide.':'Οδηγός γενέθλιου χάρτη και αστρολογίας.';
 return[
  ...signs.map(item=>({title:item[index],description,category:'astrology',path:`/burclar/${item[0]}`})),
  ...houses.map(item=>({title:`${item[0]}. ${locale==='tr'?'Ev':locale==='en'?'House':'Οίκος'} — ${item[index]}`,description,category:'astrology',path:`/evler/${item[0]}`})),
  ...planets.map(item=>({title:item[index],description:item[index+3],category:'astrology',path:`/gezegenler/${item[0]}`})),
  ...aspects.map(item=>({title:item[index],description:item[index+3],category:'astrology',path:`/acilar/${item[0]}`})),
  {title:locale==='tr'?'Transitler':locale==='en'?'Transits':'Διελεύσεις',description,category:'astrology',path:'/transitler'},
  {title:locale==='tr'?'Retro Hareketler':locale==='en'?'Retrograde Motion':'Ανάδρομη Κίνηση',description,category:'astrology',path:'/retro-hareketler'}
 ]};
export function libraryPage(route,locale='tr'){
 const t=ui[locale];
 if(route==='/astroloji-kutuphanesi'){
  const groups=[[locale==='tr'?'12 Burç':locale==='en'?'12 Signs':'12 Ζώδια',signs.map(x=>[L(x,locale,1),`/burclar/${x[0]}`,L(x,locale,10)])],[locale==='tr'?'12 Ev':locale==='en'?'12 Houses':'12 Οίκοι',houses.map(x=>[locale==='tr'?`${x[0]}. Ev`:locale==='en'?`House ${x[0]}`:`${x[0]}ος Οίκος`,`/evler/${x[0]}`,L(x,locale,1)])],[locale==='tr'?'Gezegenler':locale==='en'?'Planets':'Πλανήτες',planets.map(x=>[L(x,locale,1),`/gezegenler/${x[0]}`,L(x,locale,4)])],[locale==='tr'?'Açılar ve Zamanlama':locale==='en'?'Aspects and Timing':'Όψεις και Χρονισμός',[...aspects.map(x=>[L(x,locale,1),`/acilar/${x[0]}`,L(x,locale,4)]),[locale==='tr'?'Transitler':locale==='en'?'Transits':'Διελεύσεις','/transitler',locale==='tr'?'Güncel gökyüzünün doğum haritasıyla teması.':locale==='en'?'How the current sky contacts the birth chart.':'Πώς ο τρέχων ουρανός αγγίζει τον γενέθλιο χάρτη.'],[locale==='tr'?'Retro Hareketler':locale==='en'?'Retrogrades':'Ανάδρομες Κινήσεις','/retro-hareketler',locale==='tr'?'Gözden geçirme, içe dönüş ve yeniden düzenleme döngüleri.':locale==='en'?'Cycles of review, internalization and revision.':'Κύκλοι επανεξέτασης, εσωτερίκευσης και αναθεώρησης.']]]];
  const body=`<section class="library-hero"><p class="eyebrow">MYTHBORN · ${t.home.toUpperCase()}</p><h1>${t.home}</h1><p class="lead left-lead">${t.intro}</p></section><div class="library-groups">${groups.map(([h,items])=>`<section><h2>${h}</h2><div class="library-grid">${items.map(([n,u,d])=>`<article class="library-card"><h2>${esc(n)}</h2><p>${esc(d)}</p><a href="${path(u,locale)}">${t.read} →</a></article>`).join('')}</div></section>`).join('')}</div>`;
  return shell(locale,t.home,t.intro,body,route,[{'@context':'https://schema.org','@type':'CollectionPage',name:t.home,description:t.intro,url:`${SITE}${path(route,locale)}`}]);
 }
 let item,type,title,meaning,meta=[];
 if(route.startsWith('/burclar/')){item=signs.find(x=>route.endsWith('/'+x[0]));if(item){type='sign';title=L(item,locale,1);meaning=L(item,locale,10);meta=[L(item,locale,4),L(item,locale,7)]}}
 if(route.startsWith('/evler/')){item=houses.find(x=>route.endsWith('/'+x[0]));if(item){type='house';title=locale==='tr'?`${item[0]}. Ev`:locale==='en'?`House ${item[0]}`:`${item[0]}ος Οίκος`;meaning=L(item,locale,1)}}
 if(route.startsWith('/gezegenler/')){item=planets.find(x=>route.endsWith('/'+x[0]));if(item){type='planet';title=L(item,locale,1);meaning=L(item,locale,4)}}
 if(route.startsWith('/acilar/')){item=aspects.find(x=>route.endsWith('/'+x[0]));if(item){type='aspect';title=L(item,locale,1);meaning=L(item,locale,4)}}
 if(route==='/transitler'){title=locale==='tr'?'Transitler':locale==='en'?'Transits':'Διελεύσεις';meaning=locale==='tr'?'Güncel gezegenlerin doğum haritasındaki gezegen, açı ve evlerle kurduğu geçici temaslardır.':locale==='en'?'Temporary contacts between current planets and natal planets, angles and houses.':'Προσωρινές επαφές των τρεχόντων πλανητών με γενέθλιους πλανήτες, γωνίες και οίκους.';type='timing'}
 if(route==='/retro-hareketler'){title=locale==='tr'?'Retro Hareketler':locale==='en'?'Retrogrades':'Ανάδρομες Κινήσεις';meaning=locale==='tr'?'Dünya merkezli bakışta gezegenin gökyüzünde geri gidiyormuş gibi görünmesidir; astrolojide gözden geçirme ve içe yönelimle ilişkilendirilir.':locale==='en'?'The apparent backward motion of a planet from Earth; astrologically associated with review and internalization.':'Η φαινομενική οπισθοδρόμηση ενός πλανήτη από τη Γη· αστρολογικά συνδέεται με επανεξέταση και εσωτερίκευση.';type='timing'}
 if(!title)return null;
 const faq=genericFaq(locale,title);
 let light,shadow,question;
 if(type==='sign'){light=locale==='tr'?`${meaning}; kişinin bu niteliği bilinçli, yaratıcı ve ilişkisel biçimde kullanması.`:locale==='en'?`${meaning}; using this quality consciously, creatively and relationally.`:`${meaning}· συνειδητή, δημιουργική και σχεσιακή χρήση αυτής της ποιότητας.`;shadow=L(item,locale,13);question=locale==='tr'?`Bu burcun güçlü tarafını kullanırken hangi gölgeye kayıyorum?`:locale==='en'?`Which shadow do I slip into while using this sign’s strength?`:`Σε ποια σκιά γλιστρώ όταν χρησιμοποιώ τη δύναμη αυτού του ζωδίου;`}
 else {light=locale==='tr'?`${meaning} alanını bilinçli seçim, ölçülülük ve gerçek hayat verileriyle geliştirmek.`:locale==='en'?`Developing ${meaning} through conscious choice, proportion and real-life evidence.`:`Ανάπτυξη του πεδίου «${meaning}» με συνειδητή επιλογή, μέτρο και πραγματικά δεδομένα.`;shadow=locale==='tr'?'Tek bir yerleşimi mutlaklaştırmak, korku dili kullanmak veya gerçek koşulları yok saymak.':locale==='en'?'Absolutizing one placement, using fear-based language or ignoring real conditions.':'Απολυτοποίηση μίας θέσης, γλώσσα φόβου ή αγνόηση πραγματικών συνθηκών.';question=locale==='tr'?'Bu sembolü bugün hangi somut davranışla daha dengeli yaşayabilirim?':locale==='en'?'What concrete behaviour would express this symbol more constructively today?':'Ποια συγκεκριμένη συμπεριφορά θα εξέφραζε πιο δημιουργικά αυτό το σύμβολο σήμερα;'}
 const body=`<article class="library-page"><a href="${path('/astroloji-kutuphanesi',locale)}">← ${t.home}</a><p class="eyebrow">MYTHBORN · ${t.home.toUpperCase()}</p><h1>${esc(title)}</h1>${meta.length?`<div class="library-meta">${meta.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}<p class="article-lead">${esc(meaning)}</p><section><h2>${t.meaning}</h2><p>${esc(meaning)} ${locale==='tr'?'Haritadaki gerçek işlevi, bulunduğu burç, ev ve yaptığı açılarla birlikte değerlendirilir.':locale==='en'?'Its actual chart function depends on sign, house and aspects.':'Η πραγματική λειτουργία στον χάρτη εξαρτάται από ζώδιο, οίκο και όψεις.'}</p></section><section><h2>${t.light}</h2><p>${esc(light)}</p></section><section><h2>${t.shadow}</h2><p>${esc(shadow)}</p></section><section><h2>${t.practice}</h2><p>${esc(question)}</p></section><section class="article-faq"><p class="eyebrow">${t.faq.toUpperCase()}</p>${faq.map(([q,a])=>`<details><summary>${esc(q)}</summary><p>${esc(a)}</p></details>`).join('')}</section><p class="article-note">${t.note}</p></article>`;
 return shell(locale,title,meaning,body,route,schemas(locale,title,meaning,route,faq));
}
