import { Body, GeoVector, Ecliptic, SiderealTime } from 'astronomy-engine';

const bodies=[['Güneş',Body.Sun],['Ay',Body.Moon],['Merkür',Body.Mercury],['Venüs',Body.Venus],['Mars',Body.Mars],['Jüpiter',Body.Jupiter],['Satürn',Body.Saturn],['Uranüs',Body.Uranus],['Neptün',Body.Neptune],['Plüton',Body.Pluto]];
const signs=['Koç','Boğa','İkizler','Yengeç','Aslan','Başak','Terazi','Akrep','Yay','Oğlak','Kova','Balık'];
const signElement=['Ateş','Toprak','Hava','Su','Ateş','Toprak','Hava','Su','Ateş','Toprak','Hava','Su'];
const signMode=['Öncü','Sabit','Değişken','Öncü','Sabit','Değişken','Öncü','Sabit','Değişken','Öncü','Sabit','Değişken'];
const aspects=[{name:'Kavuşum',angle:0,orb:8},{name:'Sekstil',angle:60,orb:5},{name:'Kare',angle:90,orb:7},{name:'Üçgen',angle:120,orb:7},{name:'Karşıt',angle:180,orb:8}];
export const normalizeLongitude=n=>((n%360)+360)%360;
const norm=normalizeLongitude,rad=d=>d*Math.PI/180,deg=r=>r*180/Math.PI;
export const zodiacPlacement=longitude=>{const l=norm(longitude),i=Math.floor(l/30);return{sign:signs[i],degree:Number((l-i*30).toFixed(2)),longitude:Number(l.toFixed(4)),element:signElement[i],mode:signMode[i]}};
const placement=zodiacPlacement;
const angularDistance=(a,b)=>{const d=Math.abs(norm(a)-norm(b));return d>180?360-d:d};
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});

async function geocode(place,locale='tr'){const language=locale==='en'?'en':locale==='el'?'el':'tr',queries=[place,place.split(',')[0].trim()].filter((value,index,array)=>value&&array.indexOf(value)===index);for(const query of queries){const response=await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(query)}&count=5&language=${language}&format=json`,{headers:{accept:'application/json'}});if(!response.ok)continue;const results=(await response.json()).results||[],countryHint=place.split(',').slice(1).join(' ').trim().toLocaleLowerCase(language),result=countryHint?results.find(item=>`${item.country||''} ${item.country_code||''}`.toLocaleLowerCase(language).includes(countryHint))||results[0]:results[0];if(result)return{latitude:result.latitude,longitude:result.longitude,timezone:result.timezone,name:[result.name,result.admin1,result.country].filter(Boolean).join(', ')}}throw new Error('Doğum yeri bulunamadı. Şehir ve ülke birlikte yazılmalı.')}
export function zonedParts(date,timeZone){return Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(date).filter(x=>x.type!=='literal').map(x=>[x.type,Number(x.value)]))}
const sameLocalMinute=(parts,target)=>parts.year===target.year&&parts.month===target.month&&parts.day===target.day&&parts.hour===target.hour&&parts.minute===target.minute;
export function localToUtc(dateText,timeText,timeZone){const[y,m,d]=dateText.split('-').map(Number),[h,min]=String(timeText||'12:00').split(':').map(Number),local={year:y,month:m,day:d,hour:h,minute:min||0},target=Date.UTC(y,m-1,d,h,min||0,0);let utc=target;for(let i=0;i<4;i++){const p=zonedParts(new Date(utc),timeZone),represented=Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second||0);utc+=target-represented}const matches=[];for(let delta=-180;delta<=180;delta+=15){const candidate=new Date(utc+delta*60_000);if(sameLocalMinute(zonedParts(candidate,timeZone),local))matches.push(candidate)}if(!matches.length)throw new Error('Bu yerel saat, saat dilimi geçişi nedeniyle mevcut değil.');return matches.sort((a,b)=>a-b)[0]}
function ascendant(date,lat,lon){const theta=rad(norm(SiderealTime(date)*15+lon)),eps=rad(23.4392911),phi=rad(lat);const westernHorizon=deg(Math.atan2(-Math.cos(theta),Math.sin(theta)*Math.cos(eps)+Math.tan(phi)*Math.sin(eps)));return norm(westernHorizon+180)}
function midheaven(date,lon){const theta=rad(norm(SiderealTime(date)*15+lon)),eps=rad(23.4392911);return norm(deg(Math.atan2(Math.sin(theta),Math.cos(theta)*Math.cos(eps))))}
export function calculateChartAngles(date,latitude,longitude){if(!(date instanceof Date)||Number.isNaN(date.getTime()))throw new TypeError('Geçerli bir UTC anı gerekli.');if(!Number.isFinite(latitude)||latitude<=-90||latitude>=90)throw new RangeError('Enlem -90° ile 90° arasında olmalı.');if(!Number.isFinite(longitude)||longitude<-180||longitude>180)throw new RangeError('Boylam -180° ile 180° arasında olmalı.');const asc=ascendant(date,latitude,longitude),mc=midheaven(date,longitude);return{ascendant:asc,descendant:norm(asc+180),midheaven:mc,imumCoeli:norm(mc+180)}}
const houseFor=(longitude,asc)=>Math.floor(norm(longitude-asc)/30)+1;
const planetLongitude=(body,date)=>norm(Ecliptic(GeoVector(body,date,true)).elon);
function buildAspects(planets){const out=[];for(let i=0;i<planets.length;i++)for(let j=i+1;j<planets.length;j++){const distance=angularDistance(planets[i].longitude,planets[j].longitude);for(const aspect of aspects){const delta=Math.abs(distance-aspect.angle);if(delta<=aspect.orb){out.push({from:planets[i].name,to:planets[j].name,type:aspect.name,orb:Number(delta.toFixed(2)),angle:Number(distance.toFixed(2))});break}}}return out.sort((a,b)=>a.orb-b.orb)}
const validateInput=input=>{const birthDate=String(input?.birthDate||''),birthTime=String(input?.birthTime||''),birthPlace=String(input?.birthPlace||'').trim(),timeUnknown=Boolean(input?.timeUnknown);if(!/^\d{4}-\d{2}-\d{2}$/.test(birthDate)||!birthPlace)throw new Error('Doğum tarihi ve doğum yeri zorunludur.');if(!timeUnknown&&!/^\d{2}:\d{2}$/.test(birthTime))throw new Error('Doğum saati girilmeli veya saat bilinmiyor seçilmelidir.');return{birthDate,birthTime,birthPlace,timeUnknown}}
async function buildChart(raw){const input=validateInput(raw),locale=raw?.locale==='en'?'en':raw?.locale==='el'?'el':'tr',location=await geocode(input.birthPlace,locale),instant=localToUtc(input.birthDate,input.timeUnknown?'12:00':input.birthTime,location.timezone);if(Number.isNaN(instant.getTime()))throw new Error('Doğum zamanı hesaplanamadı.');const chartAngles=input.timeUnknown?null:calculateChartAngles(instant,location.latitude,location.longitude),asc=chartAngles?.ascendant??null,mc=chartAngles?.midheaven??null;const planets=bodies.map(([name,body])=>{const p={name,...placement(planetLongitude(body,instant))};if(asc!==null)p.house=houseFor(p.longitude,asc);p.interpretation=asc===null?`${p.name} ${p.sign} burcunda ${p.degree.toFixed(2)}°.`:`${p.name} ${p.sign} burcunda ${p.degree.toFixed(2)}° ve ${p.house}. evde.`;return p});const houses=asc===null?[]:Array.from({length:12},(_,i)=>({house:i+1,cusp:placement(asc+i*30)}));const angles=asc===null?null:{ascendant:placement(chartAngles.ascendant),midheaven:placement(chartAngles.midheaven),descendant:placement(chartAngles.descendant),imumCoeli:placement(chartAngles.imumCoeli),houseSystem:'Eşit Ev'};const sun=planets.find(x=>x.name==='Güneş'),moon=planets.find(x=>x.name==='Ay');return{engine:{name:'Astronomy Engine',accuracy:'yaklaşık ±1 yay-dakikası gezegen konumu',houseSystem:angles?'Eşit Ev':null},birth:{date:input.birthDate,time:input.timeUnknown?null:input.birthTime,timeUnknown:input.timeUnknown,utc:instant.toISOString(),location},summary:{sun:sun.sign,moon:moon.sign,rising:angles?.ascendant.sign||null,dominantElements:Object.entries(planets.reduce((a,p)=>(a[p.element]=(a[p.element]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]).map(([element,count])=>({element,count}))},angles,houses,planets,aspects:buildAspects(planets),note:input.timeUnknown?'Doğum saati bilinmediği için yükselen, MC ve evler hesaplanmadı.':'Yükselen, MC ve evler girilen doğum saati, koordinat ve tarihsel zaman dilimiyle hesaplandı.'}}

function crossAspects(first,second){const out=[];for(const a of first.planets)for(const b of second.planets){const distance=angularDistance(a.longitude,b.longitude);for(const aspect of aspects){const delta=Math.abs(distance-aspect.angle);if(delta<=aspect.orb){out.push({first:a.name,second:b.name,type:aspect.name,orb:Number(delta.toFixed(2)),angle:Number(distance.toFixed(2)),tone:['Üçgen','Sekstil'].includes(aspect.name)?'uyumlu':['Kare','Karşıt'].includes(aspect.name)?'zorlayıcı':'yoğun'});break}}}return out.sort((a,b)=>a.orb-b.orb)}
const pairKey=a=>[a.first,a.second].sort().join('-');
function synastryThemes(items){const groups={duygu:[],iletisim:[],cekim:[],baglilik:[],gelisim:[]};for(const a of items){const key=pairKey(a);if(key.includes('Ay')&&(key.includes('Güneş')||key.includes('Venüs')||key.includes('Ay')))groups.duygu.push(a);if(key.includes('Merkür'))groups.iletisim.push(a);if((key.includes('Venüs')&&key.includes('Mars'))||key==='Venüs-Venüs'||key==='Mars-Mars')groups.cekim.push(a);if(key.includes('Satürn'))groups.baglilik.push(a);if(key.includes('Jüpiter'))groups.gelisim.push(a)}const describe=(title,list,empty)=>({title,count:list.length,leading:list[0]||null,summary:list.length?`${list[0].first}–${list[0].second} ${list[0].type.toLowerCase()} açısı ${list[0].tone} bir ilişki teması oluşturuyor. Toplam ${list.length} belirgin bağ bulundu.`:empty});return[describe('Duygusal uyum',groups.duygu,'Duygusal temaslar daha çok günlük davranış ve iletişim üzerinden kuruluyor.'),describe('İletişim',groups.iletisim,'İletişim kalitesi bilinçli dinleme ve açık soru sormayla güçlenebilir.'),describe('Çekim',groups.cekim,'Çekim yalnız fiziksel değil; ortak merak ve yaşam ritmi üzerinden gelişebilir.'),describe('Bağlılık',groups.baglilik,'Bağlılık ve sorumluluk zaman içinde alınan kararlarla şekillenecek.'),describe('Birlikte büyüme',groups.gelisim,'Ortak öğrenme alanları ilişkiyi genişleten ana kaynak olabilir.')]}

export async function calculateCurrentSky(){try{const instant=new Date(),planets=bodies.map(([name,body])=>({name,...placement(planetLongitude(body,instant))})),currentAspects=buildAspects(planets).slice(0,8),counts=planets.reduce((out,p)=>(out[p.element]=(out[p.element]||0)+1,out),{}),dominantElement=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'Dengeli',sun=planets.find(p=>p.name==='Güneş'),moon=planets.find(p=>p.name==='Ay'),mercury=planets.find(p=>p.name==='Merkür');return json({calculatedAt:instant.toISOString(),engine:{name:'Astronomy Engine',method:'gerçek zamanlı jeosantrik ekliptik boylam'},headline:`Güneş ${sun.sign}, Ay ${moon.sign}: ${dominantElement.toLowerCase()} elementi bugün daha görünür.`,summary:`Günün ana zemini Güneş'in ${sun.sign} burcundaki ${sun.degree}° konumu ile Ay'ın ${moon.sign} burcundaki ${moon.degree}° hareketi arasında kuruluyor. Merkür ${mercury.sign} burcunda.`,dominantElement,planets,aspects:currentAspects,note:'Genel gökyüzü kişisel doğum haritasıyla birlikte okunmalıdır.'})}catch(error){return json({error:error.message||'Güncel gökyüzü hesaplanamadı.'},500)}}
export async function calculateNatalChart(request){let input;try{input=await request.json()}catch{return json({error:'Geçerli doğum bilgileri gönderilmedi.'},400)}try{return json(await buildChart(input))}catch(error){return json({error:error.message||'Doğum haritası hesaplanamadı.'},422)}}
export async function calculateSynastry(request){let input;try{input=await request.json()}catch{return json({error:'İki kişiye ait geçerli doğum bilgileri gönderilmedi.'},400)}try{const[first,second]=await Promise.all([buildChart(input.first),buildChart(input.second)]),links=crossAspects(first,second),harmonious=links.filter(x=>x.tone==='uyumlu').length,challenging=links.filter(x=>x.tone==='zorlayıcı').length,intense=links.filter(x=>x.tone==='yoğun').length,score=Math.max(35,Math.min(95,55+harmonious*3-challenging*1.5+intense));return json({engine:{name:'Astronomy Engine',method:'iki gerçek doğum haritası arasında gezegenler arası açı karşılaştırması'},first:{birth:first.birth,summary:first.summary},second:{birth:second.birth,summary:second.summary},score:Math.round(score),counts:{harmonious,challenging,intense,total:links.length},themes:synastryThemes(links),aspects:links.slice(0,30),note:'Sinastri bir ilişkinin potansiyel dinamiklerini gösterir; ilişkinin geleceğini veya kişilerin davranışlarını kesin olarak belirlemez.'})}catch(error){return json({error:error.message||'Sinastri hesaplanamadı.'},422)}}
