export const articles=[
{slug:'2-agustos-2027-gunes-tutulmasi-aslan',title:'2 Ağustos 2027 Tam Güneş Tutulması: Türkiye’den Görünürlük, Aslan 9°55′ ve Yükselene Göre Etkiler',dek:'2 Ağustos 2027 tam Güneş tutulmasını astronomik görünürlük, güvenli gözlem, 9°55′ Aslan derecesi, doğum haritası ve 12 yükselene göre detaylı biçimde incele.',date:'2026-09-30',tags:['Güneş Tutulması','2 Ağustos 2027','Aslan','Yükselen Burç'],sections:[
['2 Ağustos 2027 tutulması neden bu kadar dikkat çekiyor?','Bu tutulma küresel olarak tam Güneş tutulmasıdır ve maksimum evresi 2 Ağustos 2027’de gerçekleşir. Tamlık hattı güney İspanya, Kuzey Afrika, Mısır ve Arap Yarımadası üzerinden ilerler. Maksimum totalite yaklaşık 6 dakika 23 saniyeye ulaşır; bu süre modern dönemin en dikkat çekici tutulmalarından biri olmasını sağlar. Türkiye tamlık hattında değildir ancak geniş bir bölgede parçalı tutulma görülebilir.'],
['Türkiye’den ve İstanbul’dan nasıl görülecek?','Türkiye’de tutulma parçalı olarak görülecek. İstanbul’da tutulma yaklaşık 11:27’de başlayacak, 12:39 civarında maksimuma ulaşacak ve 13:50 civarında sona erecek. İstanbul için Güneş diskinin yaklaşık yüzde 59’u örtülecek. İzmir ve Antalya gibi daha güneybatı noktalarında örtülme oranı daha yüksek; Türkiye genelinde yerel saat ve oranlar şehre göre değişir.'],
['Güneş tutulmasını güvenli izleme kuralı','Parçalı evrede Güneş’e çıplak gözle bakılmaz. ISO 12312-2 standardına uygun tutulma gözlüğü veya güvenli dolaylı projeksiyon yöntemi kullanılmalıdır. Normal güneş gözlüğü yeterli değildir. Teleskop, dürbün veya kamera kullanılıyorsa uygun Güneş filtresi cihazın önüne takılmalıdır.'],
['Astrolojik derece: 9°55′ Aslan','Tropikal astrolojide tutulma yaklaşık 9°55′ Aslan derecesinde gerçekleşir. Kişisel yorumda yalnız “Aslan tutulması” demek yerine, doğum haritasında 7°–13° sabit burçlarda (Aslan, Kova, Boğa, Akrep) gezegen veya açı noktası bulunup bulunmadığına bakmak daha anlamlıdır. Derece yakınlığı arttıkça sembolik vurgu daha kişisel hale gelir.'],
['Aslan teması nasıl okunur?','Aslan; görünürlük, yaratıcılık, kalpten ifade, sahne, özgüven ve kişisel merkez temalarıyla ilişkilendirilir. Tutulma bu başlıkları “kesin olay” şeklinde değil, hangi alanda daha görünür olmak istediğini ve hangi alanda onay arayışını azaltman gerektiğini sorgulamak için bir çerçeve sunabilir.'],
['Yükselen Koç','Tutulma 5. ev temasını öne çıkarabilir: yaratıcı üretim, aşk, hobiler, sahneye çıkma ve çocuklarla ilgili konular. Burada temel soru “Beni gerçekten canlı hissettiren şeyi ne kadar ciddiye alıyorum?” olabilir. Yeni bir yaratıcı proje başlatmak kadar, sürekli dış onaya göre hareket ettiğin alanları fark etmek de önemlidir.'],
['Yükselen Boğa','4. ev vurgusu; ev, aile, kökler, yaşam alanı ve iç güvenlik başlıklarını gündeme getirebilir. Taşınma, ev düzeni veya aile ilişkileri üzerine düşünceler artabilir. Ancak tutulmayı zorunlu bir taşınma işareti gibi değil, özel alanının sana gerçekten iyi gelip gelmediğini sorgulamak için kullan.'],
['Yükselen İkizler','3. ev; iletişim, yakın çevre, kısa yolculuklar, eğitim ve bilgi üretimiyle bağlantılıdır. Bir konuşma biçimini değiştirmek, yazmaya başlamak veya uzun zamandır söylemediğin bir şeyi daha net ifade etmek öne çıkabilir. İletişimde gösterişten çok açıklık hedeflemek iyi bir tema olabilir.'],
['Yükselen Yengeç','2. ev; gelir, sahip oldukların, özdeğer ve kaynak yönetimiyle ilişkilendirilir. “Değerimi neyle ölçüyorum?” sorusu merkezde olabilir. Yeni gelir fikri, fiyatlandırma veya harcama davranışı üzerine çalışırken yalnız astrolojik tarihe değil gerçek bütçeye ve verilere dayanmak gerekir.'],
['Yükselen Aslan','Tutulma 1. evde gerçekleşebileceği için kimlik, beden algısı, görünürlük ve kişisel yön temaları daha doğrudan hissedilebilir. Yeni bir imaj, kişisel proje veya yaşam tarzı değişikliği düşünülebilir. Ana tema başkalarının seni nasıl gördüğünden çok, kendini nasıl temsil etmek istediğin olabilir.'],
['Yükselen Başak','12. ev; geri çekilme, dinlenme, bilinçdışı kalıplar ve kapanışlarla ilişkilendirilir. Yoğun görünürlük yerine perde arkasında hazırlık yapmak, tükenmişliği fark etmek veya kapanması gereken bir döngüye alan açmak daha anlamlı olabilir. Dinlenmeyi üretkenliğin düşmanı gibi görmemek önemli bir tema olabilir.'],
['Yükselen Terazi','11. ev; arkadaşlıklar, topluluklar, ağlar ve gelecek planlarıyla ilgilidir. Bir çevreden daha görünür olmak veya tam tersine artık seni temsil etmeyen bir gruptan uzaklaşmak gündeme gelebilir. “Kiminle birlikte büyümek istiyorum?” sorusu burada belirleyici olabilir.'],
['Yükselen Akrep','10. ev; kariyer, statü, otorite, hedef ve kamusal görünürlük alanıdır. Yeni sorumluluk, iş değişimi veya görünürlüğün artması teması sembolik olarak öne çıkabilir. Ancak kariyer kararlarını tutulmaya bağlamak yerine performans, fırsat, gelir ve uzun vadeli hedeflerle birlikte değerlendirmek gerekir.'],
['Yükselen Yay','9. ev; yüksek öğrenim, seyahat, yabancılar, yayıncılık ve dünya görüşüyle ilişkilendirilir. Yeni bir eğitim, yurtdışı planı veya fikir sistemini sorgulama teması doğabilir. Buradaki mesele yalnız “uzaklara gitmek” değil, bakış açını genişletecek deneyimi seçmek olabilir.'],
['Yükselen Oğlak','8. ev; ortak para, borç, vergi, miras, mahremiyet ve psikolojik paylaşım konularını gündeme getirebilir. Finansal ortaklıkları ve riskleri gözden geçirmek iyi olabilir. Büyük mali kararlar için astrolojik sembolizm yerine sözleşme, hukuk ve finans verileri esas alınmalıdır.'],
['Yükselen Kova','7. ev; partnerlik, sözleşmeler ve bire bir ilişkiler alanıdır. Bir ilişkinin görünür dinamiği değişebilir veya ortaklıkta rol dağılımı yeniden konuşulabilir. Ama “tutulma ayrılık getirir” gibi kesin hükümler doğru değildir; asıl değer karşılıklılık ve sınırların netleşmesidir.'],
['Yükselen Balık','6. ev; iş rutini, günlük düzen, hizmet, alışkanlıklar ve beden bakımına bağlanır. Çalışma sistemini sadeleştirmek, fazla yükü azaltmak veya yeni rutin kurmak gündeme gelebilir. Sağlıkla ilgili kararlar astrolojik yorumla değil, gerektiğinde sağlık profesyoneliyle verilmelidir.'],
['Haritada hangi derecelere bakılmalı?','Tutulmanın 9°55′ Aslan derecesine yaklaşık 3 derece orb içinde temas eden natal Güneş, Ay, yükselen, MC, Venüs veya Mars daha kişisel bir sembolik vurgu yaratabilir. Daha geniş orb kullanılan ekoller vardır; fakat derece ne kadar yakınsa yorum o kadar spesifik kabul edilir.'],
['Bu tutulmayı günlük hayatta nasıl kullanırsın?','Üç soru yaz: Nerede görünür olmak istiyorum? Nerede yalnız alkış almak için performans gösteriyorum? Önümüzdeki altı ay içinde hangi yaratıcı veya kişisel projeye düzenli zaman ayırabilirim? Böylece tutulmayı soyut kehanet yerine somut bir öz değerlendirme aracına dönüştürürsün.']],
faq:[
['2 Ağustos 2027 Güneş tutulması Türkiye’den görülecek mi?','Evet. Türkiye’de tam değil parçalı Güneş tutulması görülecek. Örtülme oranı şehre göre değişecek.'],
['İstanbul’da tutulma saat kaçta?','İstanbul’da yaklaşık 11:27’de başlar, 12:39’da maksimuma ulaşır ve 13:50 civarında sona erer.'],
['Tutulma hangi burçta ve kaç derecede?','Tropikal astrolojide tutulma yaklaşık 9°55′ Aslan derecesindedir.'],
['En çok hangi burçlar etkilenir?','Astrolojik yorumda yalnız Güneş burcu değil, özellikle 7°–13° Aslan, Kova, Boğa ve Akrep civarındaki natal yerleşimler dikkate alınır.'],
['Tutulmaya çıplak gözle bakılır mı?','Hayır. Parçalı evre boyunca uygun Güneş filtresi veya güvenli dolaylı gözlem yöntemi gerekir.'],
['Tutulma kesin bir olay getirir mi?','Hayır. Astrolojik yorum sembolik bir çerçevedir; kişisel veya dışsal bir olayı garanti etmez.']],
links:[['Doğum haritanı hesapla','/astroloji'],['Bugünün gökyüzünü gör','/bugunun-gokyuzu'],['2027 astroloji takvimi','/blog/2027-astroloji-takvimi-retrolar-tutulmalar'],['Ay takvimi','/ay-takvimi']]},
{slug:'venus-retrosu-2026-yukselene-gore',title:'Venüs Retrosu 2026: 12 Yükselene Göre Aşk, Para ve İlişki Temaları',dek:'3 Ekim–14 Kasım 2026 Venüs retrosunu 12 yükselene göre ev bazında incele; aşk, para, sınırlar, ortaklıklar ve özdeğer başlıklarını detaylandır.',date:'2026-09-30',tags:['Venüs Retrosu','Yükselen Burç','Aşk','2026'],sections:[
['Bu rehberi neden yükselene göre okumak daha anlamlı?','Venüs retrosu için yalnız Güneş burcuna bakmak, transitin hangi yaşam alanını tetiklediğini göstermeyebilir. Yükselen burç ev dağılımını belirlediği için Akrep ve Terazi’nin haritanda hangi alanlara düştüğünü daha iyi gösterir. Doğum saatin bilinmiyorsa bu bölüm yaklaşık bir rehberdir.'],
['Retro takvimi: önce Akrep, sonra Terazi','Venüs 3 Ekim 2026’da 8°29′ Akrep’te retroya girer, 25 Ekim civarında Terazi’ye geri döner ve 14 Kasım’da 22°52′ Terazi’de direkt harekete geçer. Bu nedenle dönemi iki bölümde okumak yararlı olabilir: önce yoğun bağlar ve ortak değerler, sonra karşılıklılık ve denge.'],
['Yükselen Koç','Akrep 8. ev, Terazi 7. ev temalarını çalıştırır. İlk bölümde ortak para, borç, güven ve mahremiyet; ikinci bölümde partnerlik ve sözleşmeler daha görünür olabilir. İlişkide “kim ne kadar veriyor?” sorusunu yalnız duygusal değil maddi ve zamansal açıdan da düşünmek faydalı olabilir.'],
['Yükselen Boğa','Akrep 7. ev, Terazi 6. evdir. İlişki ve ortaklık dinamikleri önce öne çıkabilir; sonra günlük düzen, iş ortamı ve emek dengesi gündeme gelebilir. Bir ilişkide yalnız romantik bağ değil, günlük hayatta birbirinize nasıl alan açtığınız da önemli hale gelir.'],
['Yükselen İkizler','Akrep 6. ev, Terazi 5. evdir. İş düzeni, rutinler ve hizmet teması; ardından flört, yaratıcılık ve keyif alanları devreye girebilir. Sürekli üretmek ile gerçekten zevk almak arasındaki dengeyi sorgulamak bu dönemin verimli tarafı olabilir.'],
['Yükselen Yengeç','Akrep 5. ev, Terazi 4. evdir. Aşk, yaratıcı ifade ve çocuklar; ardından ev, aile ve özel alan gündeme gelebilir. Eski bir aşk temasının geri gelmesi kadar, “romantik hayatım özel alanımı nasıl etkiliyor?” sorusu da önemli olabilir.'],
['Yükselen Aslan','Akrep 4. ev, Terazi 3. evdir. Ev, aile ve kökler üzerinden başlayan sorgulama iletişim, yakın çevre ve karar diline taşınabilir. Aile ilişkilerinde yıllardır söylenmeyen şeyleri daha sakin ve net ifade etmek için bir gözden geçirme dönemi olabilir.'],
['Yükselen Başak','Akrep 3. ev, Terazi 2. evdir. İletişim, sözleşme, eğitim ve yakın çevre; sonra para, fiyatlandırma ve özdeğer konusu öne çıkar. “Ben ne kadar değerliyim?” sorusunu yalnız duygusal değil iş ve gelir düzeyinde de düşünmek gerekebilir.'],
['Yükselen Terazi','Akrep 2. ev, Terazi 1. evdir. Para ve özdeğer sorgusu doğrudan kimlik ve dış görünüş temalarına bağlanabilir. Yeni estetik kararlar veya imaj değişiklikleri gündeme gelse de asıl soru “Kendimi başkalarının beğenisine göre mi tanımlıyorum?” olabilir.'],
['Yükselen Akrep','Akrep 1. ev, Terazi 12. evdir. İlk bölüm daha kişisel: imaj, çekicilik, değerler ve ilişkide kendini sunma biçimi. İkinci bölüm daha içe dönük olabilir; kapanmamış ilişkiler, gizli beklentiler ve dinlenme ihtiyacı gündeme gelebilir.'],
['Yükselen Yay','Akrep 12. ev, Terazi 11. evdir. Eski duygusal kalıplar ve perde arkası meseleler; ardından arkadaşlıklar ve sosyal çevre gündeme gelebilir. Bir ilişkiyi sürdürmenin maliyetini değil, bir çevreye ait olmanın duygusal maliyetini de düşünmek gerekebilir.'],
['Yükselen Oğlak','Akrep 11. ev, Terazi 10. evdir. Arkadaşlıklar, ekipler ve uzun vadeli hedefler; sonra kariyer, statü ve görünürlük alanı öne çıkar. Profesyonel ilişkilerde sempati ile karşılıklı faydayı ayırmak, kariyer hedeflerini başkalarının onayından bağımsızlaştırmak önemli olabilir.'],
['Yükselen Kova','Akrep 10. ev, Terazi 9. evdir. Kariyer ve otoriteyle başlayan sorgulama eğitim, seyahat, hukuk, yayıncılık veya dünya görüşüne taşınabilir. Bir hedefin seni gerçekten büyütüp büyütmediğini ya da yalnız prestij sağladığını ayırt etmek değerli olabilir.'],
['Yükselen Balık','Akrep 9. ev, Terazi 8. evdir. İnançlar, eğitim ve uzaklar; ardından ortak para, güven ve mahremiyet temaları gelir. Özellikle ilişkilerde “aynı hayata mı bakıyoruz?” ve “kaynakları nasıl paylaşıyoruz?” soruları birbirine bağlanabilir.'],
['Eski sevgili teması neden bu kadar konuşuluyor?','Venüs retrosu popüler kültürde sık sık eski sevgililerin geri dönmesiyle ilişkilendirilir. Gerçekte retro dönemleri geçmiş ilişki kalıplarını düşünmeyi kolaylaştıran sembolik bir çerçeve sunar; belirli bir kişinin geri döneceğini garanti etmez. Geri dönüş olursa asıl soru “Neden bitti ve gerçekten ne değişti?” olmalıdır.'],
['Para ve alışveriş tarafı','Venüs yalnız ilişkiyle değil, değer ve harcama davranışıyla da ilişkilendirilir. Büyük estetik harcamalar, lüks tüketim veya fiyatlandırma kararlarında “beklemek zorundasın” kuralı yoktur. Ancak karşılaştırma yapmak, iade koşullarını okumak ve duygusal harcama dürtüsünü fark etmek yararlı olabilir.'],
['İlişkide kullanabileceğin 5 soru','1) Bu ilişkide neyi vermekten yoruldum? 2) Ne istememe rağmen açıkça söylemiyorum? 3) Para ve zaman paylaşımı adil mi? 4) Çekim ile güveni birbirine karıştırıyor muyum? 5) Bu ilişkiyi bugün sıfırdan seçer miydim? Bu sorular retro olsun olmasın ilişki kalitesini değerlendirmek için kullanışlıdır.']],
faq:[
['Venüs retrosu 2026 ne zaman?','3 Ekim 2026’da Akrep’te başlar ve 14 Kasım 2026’da Terazi’de sona erer.'],
['Venüs retrosunda eski sevgili döner mi?','Dönebilir ama retro bunu garanti etmez. Geçmiş ilişkilerin yeniden düşünülmesi daha sık konuşulan sembolik temadır.'],
['Yükselen burca göre okumak neden önemli?','Yükselen burç, Akrep ve Terazi’nin hangi evlere düştüğünü gösterir; böylece transitin hangi yaşam alanında sembolik olarak çalıştığı daha net görülebilir.'],
['Venüs retrosunda estetik yaptırılır mı?','Kesin bir astrolojik yasak yoktur. Tıbbi veya kalıcı işlemlerde güvenlik, uzman görüşü, risk ve beklentiler astrolojiden daha önemlidir.'],
['Venüs retrosunda ayrılık olur mu?','Bir retro tek başına ayrılık nedeni değildir. İlişkinin gerçek dinamikleri, iletişim, sınırlar ve karşılıklı kararlar belirleyicidir.']],
links:[['Venüs retrosu ana rehberi','/blog/venus-retrosu-2026-akrep-terazi'],['Sinastri hesapla','/sinastri'],['Doğum haritasını hesapla','/astroloji'],['Bugünün gökyüzü','/bugunun-gokyuzu']]},
{slug:'mars-retrosu-2027-basak-aslan',title:'Mars Retrosu 2027 Ne Zaman? Başak–Aslan Dönemi ve Etkileri',dek:'10 Ocak–1 Nisan 2027 Mars retrosunun Başak ve Aslan burçlarındaki seyrini; enerji, motivasyon, çatışma ve strateji temalarıyla doğum haritası bağlamında incele.',date:'2026-09-30',tags:['Mars Retrosu','2027','Başak','Aslan'],sections:[['Mars retrosu 2027 ne zaman?','Mars 10 Ocak 2027’de yaklaşık 10°26′ Başak’ta retro harekete başlıyor ve 1 Nisan 2027’de yaklaşık 20°56′ Aslan’da direkt harekete dönüyor. Retro öncesi gölge dönem 5 Kasım 2026’da başlıyor; Mars retro sırasında 21 Şubat civarında yeniden Aslan’a geçiyor ve gölge bölgeden Haziran 2027 başında tamamen çıkıyor.'],['Başak’tan Aslan’a geri dönüş ne anlatır?','Astrolojik sembolizmde Mars; hareket, irade, rekabet, öfke ve eylem kapasitesiyle ilişkilendirilir. Başak bölümü yöntem, iş akışı, verimlilik ve ayrıntı; Aslan bölümü ise görünürlük, yaratıcılık ve kişisel ifade temalarını öne çıkarabilir. Retro hareket bunların bilimsel bir nedeni değildir; sembolik bir zamanlama çerçevesidir.'],['Bu dönemde neye dikkat edilir?','Aynı sorunu daha fazla güç harcayarak çözmeye çalışmak yerine yöntemi gözden geçirmek daha işlevsel olabilir. Enerji tüketen projeleri, gereksiz rekabeti, tekrar eden çatışmaları ve sürdürülemeyen rutinleri yeniden değerlendirmek için kullanılabilir.'],['Doğum haritasında nasıl kişiselleştirilir?','Başak ve Aslan’ın haritanda düştüğü evlere; natal Mars, Güneş, yükselen ve açılarına bak. Sadece Güneş burcuna göre “en çok etkilenecek burçlar” listesi çıkarmak kişisel harita bağlamını kaçırır.']],faq:[['Mars retrosu 2027 ne zaman?','Mars 10 Ocak 2027’de retroya girer ve 1 Nisan 2027’de direkt harekete döner.'],['Mars retrosu hangi burçlarda olacak?','Retro Başak’ta başlar ve Mars geriye doğru hareket ederken Aslan’a döner.'],['Mars retrosunda yeni işe başlanır mı?','Kesin bir yasak yoktur. Hedef, kaynak, zamanlama ve enerji kapasitesini iyi kontrol etmek retro takviminden daha önemlidir.'],['Mars retrosu hangi burçları etkiler?','Başak ve Aslan vurgusu güçlü haritalarda daha görünür hissedilebilir; kişisel yorum için evler ve natal açılar birlikte değerlendirilmelidir.']],links:[['Doğum haritanı hesapla','/astroloji'],['Bugünün gökyüzünü gör','/bugunun-gokyuzu'],['Kariyer Tarot açılımı','/kariyer']]},
{slug:'2027-astroloji-takvimi-retrolar-tutulmalar',title:'2027 Astroloji Takvimi: Retrolar, Tutulmalar ve Önemli Gökyüzü Tarihleri',dek:'2027’nin Merkür ve Mars retrolarını, Güneş ve Ay tutulmalarını ve yıl boyunca takip edilecek başlıca gökyüzü dönemlerini tek sayfada güncel takvim olarak izle.',date:'2026-09-30',tags:['2027 Astroloji','Astroloji Takvimi','Tutulmalar','Retrolar'],sections:[['2027’nin en çok aranacak gökyüzü tarihleri','2027 yılı; yılın ilk çeyreğindeki Mars retrosu, üç Merkür retrosu ve iki dikkat çekici Güneş tutulmasıyla öne çıkıyor. Yıllık takvimi tek bir “iyi/kötü dönem” listesi yerine planlama, kontrol ve kişisel harita bağlamı için referans olarak kullanmak daha sağlıklıdır.'],['2027 Merkür ve Mars retro tarihleri','Mars 10 Ocak–1 Nisan 2027 arasında Başak’tan Aslan’a geri hareket ediyor. Merkür ise 9 Şubat–3 Mart, 10 Haziran–4 Temmuz ve 7–28 Ekim 2027 dönemlerinde retro harekette olacak. İstasyon saatleri saat dilimine göre tarih sınırında küçük farklılıklar gösterebilir.'],['2027 Güneş tutulmaları','6 Şubat 2027’de halkalı Güneş tutulması gerçekleşecek. 2 Ağustos 2027’de ise tam Güneş tutulması İspanya’nın güneyi, Kuzey Afrika, Mısır, Suudi Arabistan ve Yemen hattında tam; Avrupa, Afrika, Orta Doğu ve çevre bölgelerin geniş kısmında parçalı olarak görülebilecek. Astronomik gözlem ile astrolojik sembolizmi birbirinden ayırmak önemlidir.'],['2027 Ay tutulmaları','NASA 20–21 Şubat ve 16–17 Ağustos 2027 tarihlerinde yarı gölgeli Ay tutulmalarını listeliyor. Bazı astronomi takvimleri 18–19 Temmuz civarında çok sığ bir ek olay da listeler; görünürlük ve sınıflandırma ayrıntıları kaynak sistemine göre ayrıca kontrol edilmelidir.'],['Bu takvim nasıl kullanılır?','Yıllık tarihleri kaydet, ardından her olayın doğum haritandaki ev ve derece temasını ayrıca değerlendir. İş, sağlık, para veya ilişki kararlarını yalnız astrolojik takvime bağlama; gerçek koşullar, veri ve uzmanlık gereken alanlarda uygun profesyonel kaynaklar her zaman önceliklidir.']],faq:[['2027’de Merkür retrosu kaç kez olacak?','2027’de üç Merkür retrosu vardır: Şubat–Mart, Haziran–Temmuz ve Ekim dönemlerinde.'],['2027’de Mars retrosu var mı?','Evet. Mars 10 Ocak–1 Nisan 2027 arasında retro harekette olacak.'],['2027’de tam Güneş tutulması ne zaman?','2 Ağustos 2027’de tam Güneş tutulması gerçekleşecek.'],['2027’de kaç Güneş tutulması var?','2027’de iki Güneş tutulması vardır: 6 Şubat halkalı ve 2 Ağustos tam Güneş tutulması.']],links:[['Bugünün gökyüzü','/bugunun-gokyuzu'],['Doğum haritasını hesapla','/astroloji'],['Ay takvimi','/ay-takvimi']]},
{slug:'venus-retrosu-2026-akrep-terazi',title:'Venüs Retrosu 2026 Ne Zaman? Akrep–Terazi Dönemi ve Etkileri',dek:'3 Ekim–14 Kasım 2026 Venüs retrosunun Akrep ve Terazi burçlarındaki seyrini; ilişki, değerler, para ve doğum haritası bağlamında abartısız ve uygulanabilir biçimde incele.',date:'2026-09-30',tags:['Venüs Retrosu','2026','Akrep','Terazi'],sections:[['Venüs retrosu 2026 ne zaman?','Venüs 3 Ekim 2026’da 8°29′ Akrep’te retro harekete başlıyor, 25 Ekim’de yeniden Terazi’ye geçiyor ve 14 Kasım 2026’da 22°52′ Terazi’de direkt harekete dönüyor. Retro hareket astronomik olarak gezegenin gerçekten geriye gitmesi değil, Dünya’dan bakıldığında oluşan görünür hareket değişimidir.'],['Akrep ve Terazi teması nasıl okunur?','Astrolojik sembolizmde Venüs; ilişki, yakınlık, değer, estetik ve kaynaklarla ilişkilendirilir. Akrep bölümü yoğun bağlar, güven ve ortak kaynaklar; Terazi bölümü ise denge, karşılıklılık ve ilişki dinamikleri üzerinden okunabilir. Bu semboller tek başına ayrılık, barışma veya finansal sonuç garantisi vermez.'],['Doğum haritasında nereye bakılır?','Önce Akrep ve Terazi’nin doğum haritanda hangi evlere düştüğüne bak. Ardından natal Venüs, Ay, Mars ve ilişki eksenine yapılan yakın açıları değerlendir. Yalnız Güneş burcuna göre “en çok etkilenecek burçlar” listesi çıkarmak kişisel harita bilgisini fazlasıyla basitleştirir.'],['Bu dönemi nasıl kullanabilirsin?','Harcamaları, abonelikleri, ilişki sınırlarını ve uzun süredir ertelenen değer konuşmalarını gözden geçirmek için iyi bir kontrol listesi oluşturabilirsin. Büyük kararları yalnız retro olduğu için ertelemek yerine veriyi, koşulları ve kendi sınırlarını birlikte değerlendir.']],faq:[['Venüs retrosu 2026 ne zaman?','Venüs 3 Ekim 2026’da Akrep’te retroya girer ve 14 Kasım 2026’da Terazi’de direkt harekete döner.'],['Venüs retrosunda eski sevgili geri döner mi?','Retro dönemleri geçmiş ilişki temalarını yeniden düşündürebilir; ancak bir kişinin geri döneceğini astrolojik olarak garanti etmek mümkün değildir.'],['Venüs retrosunda evlenmek veya ilişkiye başlamak yanlış mı?','Hayır. Tek başına bir retro dönemini karar yasağı gibi kullanmak yerine ilişkinin gerçek koşullarını, iletişimi ve ortak beklentileri değerlendirmek daha anlamlıdır.'],['Venüs retrosu hangi burçları etkiler?','Akrep ve Terazi vurgusu güçlü haritalarda tema daha görünür olabilir; yine de kişisel etki için yükselen, evler ve natal gezegenlerle yapılan açılar birlikte incelenmelidir.']],links:[['Doğum haritanı hesapla','/astroloji'],['Sinastri hesapla','/sinastri'],['Bugünün gökyüzü','/bugunun-gokyuzu']]},
{slug:'merkur-retrosu-2026-ekim-kasim-akrep',title:'Merkür Retrosu 2026 Ne Zaman? 24 Ekim–13 Kasım Akrep Retrosu',dek:'24 Ekim–13 Kasım 2026 Merkür retrosunun Akrep burcundaki tarihlerini, gölge dönemini, iletişim ve karar temalarını doğum haritası bağlamında oku.',date:'2026-09-30',tags:['Merkür Retrosu','2026','Akrep','Astroloji'],sections:[['Merkür retrosu 2026 ne zaman?','Merkür 24 Ekim 2026’da 20°59′ Akrep’te retro harekete başlıyor ve 13 Kasım 2026’da 5°02′ Akrep’te direkt harekete dönüyor. Retro öncesi gölge dönemi 4 Ekim’de başlıyor; Merkür 30 Kasım’da aynı derece aralığını tamamen geride bırakıyor.'],['Akrep burcunda Merkür retrosu ne anlatır?','Merkür iletişim, bilgi işleme, yazışmalar, planlama ve sözleşmelerle ilişkilendirilir. Akrep sembolizmi ise mahremiyet, güven, ortak kaynaklar ve görünmeyen motivasyonlar üzerinde durur. Bu nedenle dönemi “her şey bozulacak” diye değil, ayrıntıyı yeniden kontrol etme ve eksik bilgiyi tamamlama zamanı olarak okumak daha işlevseldir.'],['Pratik kontrol listesi','Önemli dosyaların yedeğini al, sözleşme ve ödeme koşullarını ikinci kez oku, kritik mesajları göndermeden önce alıcı ve ekleri kontrol et. Yanlış anlaşılma ihtimalini azaltmak için varsayım yerine açık soru kullan. Bunlar astrolojiden bağımsız olarak da iyi iletişim ve veri güvenliği alışkanlıklarıdır.'],['Doğum haritasında nasıl kişiselleştirilir?','Akrep’in haritanda düştüğü ev, gözden geçirme temasının hangi yaşam alanında görünür olabileceğine dair sembolik bir çerçeve sunar. Natal Merkür, Mars, Ay ve yükselenle yapılan yakın açılar yorumu kişiselleştirir; yalnız Güneş burcuna göre kesin sonuç çıkarmak yeterli değildir.']],faq:[['Merkür retrosu 2026 ne zaman?','2026’nın son Merkür retrosu 24 Ekim’de başlar ve 13 Kasım’da sona erer. Gölge dönemi 4 Ekim–30 Kasım arasındadır.'],['Merkür retrosunda ne yapılmaz?','Kesin bir yasak listesi yoktur. Önemli işlemlerde belge, tarih, alıcı, ödeme ve yedekleme kontrollerini artırmak daha yararlıdır.'],['Merkür retrosu hangi burçları etkiler?','Akrep vurgusu güçlü haritalarda daha görünür hissedilebilir; kişisel yorum için ev yerleşimi ve natal açılar gerekir.'],['Merkür retrosunda sözleşme imzalanır mı?','Gerekliyse imzalanabilir. Şartları dikkatle okumak, belirsiz maddeleri netleştirmek ve gerektiğinde uzman görüşü almak retro takviminden daha önemlidir.']],links:[['Doğum haritasını hesapla','/astroloji'],['Bugünün gökyüzünü gör','/bugunun-gokyuzu'],['3 kart Tarot açılımı','/tarot']]},
{slug:'eylul-2026-astroloji-ve-gezegen-gecisleri',title:'Eylül 2026 Astroloji ve Gezegen Geçişleri Rehberi',dek:'Başak yeni ayı, Jüpiter-Satürn kare açısı ve Terazi ekinoksu ile eylül ayının göksel döngüleri ve burç analizleri.',date:'2026-08-23',tags:['Astroloji','Eylül 2026','Gökyüzü Gündemi','Transitler'],sections:[['Başak Burcunda Yeni Ay ve Zihinsel Arınma (1-7 Eylül)','Eylül ayının ilk haftasında Başak burcunda gerçekleşecek yeni ay, günlük rutinlerimizde, iş süreçlerimizde ve zihinsel organizasyonumuzda düzen kurma ihtiyacımızı artırıyor.'],['Jüpiter - Satürn Kare Açısı ve Finansal Astroloji (8-15 Eylül)','Ayın ortasında kesinleşecek Jüpiter-Satürn sert açısı, büyüme arzumuz ile sorumluluklarımız arasında köprü kurmamızı gerektiriyor.'],['Ekinoksu ve Terazi Burcunda Güneş Tutulması (16-23 Eylül)','Sonbahar ekinoksu ile birlikte dengenin ve ilişkilerin temsilcisi Terazi burcuna geçiş yapıyoruz.'],['Merkür\'ün Terazi Burcuna Geçişi (24-30 Eylül)','Ayın son haftasında iletişim gezegeni Merkür\'ün Terazi burcuna geçişiyle diplomasi ve uzlaşma ön plana çıkıyor.']],faq:[['Başak yeni ayı hangi burçları etkiler?','Başak, İkizler, Yay ve Balık burçları bu yeni aydan doğrudan etki alabilir.'],['Eylül 2026’daki ekinoks ne zaman?','Sonbahar ekinoksu 22-23 Eylül tarihlerinde gerçekleşmektedir.']],links:[['Astroloji hesapla','/astroloji'],['Bugünün gökyüzü','/bugunun-gokyuzu']]},
{slug:'saturn-retrosu-2026',title:'Satürn Retrosu 2026: Sınırlar, Sorumluluklar ve Yeniden Yapılanma',dek:'Satürn retrosunu korku diliyle değil; geciken işler, sınırlar, dayanıklılık ve uzun vadeli yapı kurma temalarıyla oku.',date:'2026-07-28',tags:['Satürn','Retro','2026'],sections:[['Satürn retrosu ne anlatır?','Astrolojik dilde Satürn; zaman, sınır, sorumluluk ve yapı temalarıyla ilişkilendirilir. Retro dönemleri yeni bir yük eklemekten çok, zaten taşıdığın yükün sürdürülebilir olup olmadığını görmeye çağırır.'],['Haritada nereden okunur?','Yalnız Güneş burcuna bakmak yerine Satürn’ün geçtiği ev, natal Satürn’le yaptığı açılar ve yükselen burç birlikte değerlendirilmelidir. Kariyer, ilişki, para veya sağlık gibi alanlara kesin hüküm verilmez; somut hayat koşullarıyla birlikte okunur.'],['Pratik çalışma','Bitmemiş bir sorumluluğu seç. Onu küçült, takvime bağla ve ilerlemeyi haftalık ölç. Satürn temasını soyut kaygı yerine uygulanabilir sisteme dönüştür.']],faq:[['Satürn retrosu kötü müdür?','Hayır. Gecikme ve gözden geçirme temalarını öne çıkaran sembolik bir dönemdir.'],['En çok kimler etkilenir?','Natal haritasında Satürn, yükselen, Güneş veya Ay ile yakın temas alanlar daha görünür hissedebilir.']],links:[['Doğum haritanı hesapla','/astroloji'],['Bugünün gökyüzünü gör','/bugunun-gokyuzu']]},
{slug:'12-agustos-2026-gunes-tutulmasi',title:'12 Ağustos 2026 Güneş Tutulması: Gökyüzü Olayı ve Astrolojik Okuma',dek:'NASA’nın doğruladığı 12 Ağustos 2026 tam Güneş tutulmasını astronomi ile astrolojiyi birbirine karıştırmadan incele.',date:'2026-07-28',tags:['Tutulma','Güneş','2026'],sections:[['Astronomik gerçek','12 Ağustos 2026’daki tam Güneş tutulması Grönland, İzlanda, İspanya, Rusya ve Portekiz’in küçük bir bölümünde tam; Avrupa, Afrika ve Kuzey Amerika’nın geniş kesimlerinde parçalı görülecek. Güvenli gözlem için uygun Güneş filtreleri gerekir.'],['Astrolojik sembolizm','Astrolojide Güneş tutulmaları görünürlük, yön ve başlangıç temalarıyla yorumlanır. Ancak kişisel etki, tutulmanın natal haritadaki ev ve açılarına göre değerlendirilmelidir.'],['Güvenli okuma','Tutulmayı kesin olay kehaneti gibi sunmak yerine, önündeki altı aylık dönemde hangi yaşam alanında yeni bir niyet veya kapanış gerektiğini düşünmek daha sağlıklıdır.']],faq:[['Tutulmaya çıplak gözle bakılır mı?','Hayır. Tamlık anı dışındaki tüm evrelerde uygun Güneş gözlüğü veya dolaylı gözlem yöntemi gerekir.'],['Herkesi aynı mı etkiler?','Astrolojik yorumda hayır; haritadaki derece ve ev yerleşimleri önemlidir.']],links:[['Doğum haritası','/astroloji'],['Ay takvimi','/ay-takvimi']]},
{slug:'jupiter-aslanda-2026',title:'Jüpiter Aslan’da 2026: Görünürlük, Yaratıcılık ve Büyüme',dek:'Jüpiter Aslan dönemini yalnız “şans” sözüyle değil; görünürlük, yaratıcı risk ve büyümeyi taşıyabilecek yapı üzerinden değerlendir.',date:'2026-07-28',tags:['Jüpiter','Aslan','Transit'],sections:[['Ana tema','Jüpiter genişleme, Aslan ise ifade, sahne, yaratıcılık ve liderlik sembolleriyle ilişkilendirilir. Bu birleşim görünür olma isteğini artırabilir.'],['Gölge taraf','Aşırı özgüven, gösteriş için harcama ve sürdürülemeyen büyük vaatler büyümenin gölge yüzüdür. Fırsat kadar kapasite de ölçülmelidir.'],['Haritanda nerede?','Aslan’ın düştüğü ev, büyümenin hangi yaşam alanında hissedileceğini gösterir. Natal Güneş, Venüs ve Jüpiter açıları yorumu kişiselleştirir.']],faq:[['Jüpiter her zaman şans getirir mi?','Jüpiter büyütür; iyi yönetilen fırsatı da, ölçüsüzlüğü de genişletebilir.'],['Sadece Aslan burçları mı etkilenir?','Hayır. Her haritada Aslan’ın yönettiği bir alan vardır.']],links:[['Haritamı çıkar','/astroloji'],['Haftalık burç','/haftalik-burc']]},
{slug:'uranus-ikizlerde-teknoloji-yapay-zeka',title:'Uranüs İkizler’de: Yapay Zekâ, İletişim ve Yeni Zihin Alışkanlıkları',dek:'Uranüs İkizler temasını teknoloji kehaneti olarak değil; bilgi akışı, öğrenme ve dijital davranışların dönüşümü olarak oku.',date:'2026-07-28',tags:['Uranüs','İkizler','Yapay Zekâ'],sections:[['Neden gündemde?','Uranüs değişim ve kopuş, İkizler ise dil, ağlar, öğrenme ve ulaşım sembolleriyle ilişkilendirilir. Bu nedenle transit; yapay zekâ, medya ve eğitim tartışmalarıyla sıkça bağdaştırılıyor.'],['Kişisel düzey','Bilgi tüketme biçimini, dikkat süreni ve çevrimiçi kimliğini sorgulamak bu dönemin en somut çalışması olabilir.'],['Eleştirel yaklaşım','Astrolojik sembolizm teknolojik gelişmeleri bilimsel olarak öngörmez. Yine de değişime verdiğin tepkiyi düşünmek için bir anlatı çerçevesi sunabilir.']],faq:[['Bu transit teknoloji çöküşü demek mi?','Hayır. Böyle kesin bir sonuç çıkarılamaz.'],['Haritada neye bakılır?','İkizler’in düştüğü ev ve Merkür/Uranüs açıları incelenir.']],links:[['Bugünün gökyüzü','/bugunun-gokyuzu'],['Doğum haritası','/astroloji']]},
{slug:'sinastri-nedir',title:'Sinastri Nedir? Aşk Uyumu Neden Yalnızca Güneş Burcu Değildir?',dek:'İki gerçek doğum haritasında Ay, Venüs, Mars, Merkür ve Satürn bağlantılarının nasıl okunduğunu öğren.',date:'2026-07-28',tags:['Sinastri','İlişki','Uyum'],sections:[['Sinastri mantığı','Sinastri iki kişinin gezegen konumlarını üst üste karşılaştırır. Tek bir uyum yüzdesinden çok, farklı ilişki alanlarını ayrı ayrı görünür kılar.'],['Önemli göstergeler','Ay duygusal güveni, Merkür iletişimi, Venüs sevgi dilini, Mars çekim ve çatışma ritmini, Satürn ise bağlılık ve sınır temasını anlatır.'],['Sağlıklı kullanım','Zorlayıcı açı “kötü ilişki”, uyumlu açı da “garanti ilişki” demek değildir. Sonuçlar davranış, değerler ve gerçek ilişki koşullarıyla birlikte okunmalıdır.']],faq:[['Doğum saati şart mı?','Ay ve gezegenler için tarih yeterli olabilir; yükselen ve evler için saat önemlidir.'],['Uyum puanı kesin midir?','Hayır, sembolik bir özet niteliğindedir.']],links:[['Gerçek sinastri hesapla','/sinastri'],['Burç uyumu','/burc-uyumu']]},
{slug:'saturn-donusu-rehberi',title:'Satürn Dönüşü Nedir? 27–30 Yaş Dönüşüm Rehberi',dek:'Satürn dönüşünü kriz etiketiyle değil; yetişkinlik, sorumluluk ve uzun vadeli yön seçimi üzerinden değerlendir.',date:'2026-07-28',tags:['Satürn Dönüşü','Yaş Döngüsü','Kariyer'],sections:[['Satürn dönüşü nedir?','Satürn yaklaşık 29 yılda natal konumuna döner. Astrolojide bu dönem kariyer, ilişki, yaşam düzeni ve sorumluluk kararlarıyla ilişkilendirilir.'],['Neden yoğun hissedilir?','Bu yaşlar zaten eğitim, iş, aile ve kimlik açısından büyük geçişlere denk gelir. Astrolojik anlatı, bu gerçek gelişim dönemini anlamlandırmak için kullanılabilir.'],['Nasıl hazırlanılır?','Sürdürmek istediğin üç yapı ile bırakman gereken üç yükü yaz. Kararlarını korku yerine değer, zaman ve kaynak hesabıyla ver.']],faq:[['Herkes aynı yaşta mı yaşar?','Tam tarih natal Satürn derecesine göre değişir.'],['İkinci Satürn dönüşü var mı?','Evet, yaklaşık 58–60 yaş civarında ikinci döngü görülür.']],links:[['Doğum haritası','/astroloji'],['Kariyer açılımı','/kariyer']]},
{slug:'astrokartografi-nedir',title:'Astrokartografi Nedir? Yer, Seyahat ve Harita Çizgileri',dek:'Astrokartografi haritasındaki gezegen çizgilerini taşınma garantisi değil, yer deneyimini düşünme aracı olarak oku.',date:'2026-07-28',tags:['Astrokartografi','Seyahat','Relokasyon'],sections:[['Temel prensip','Astrokartografi doğum anında gezegenlerin yükseldiği, battığı veya tepe/dip noktalarında bulunduğu coğrafi hatları haritalar.'],['Çizgiler nasıl okunur?','Güneş görünürlük, Venüs ilişki ve estetik, Mars hareket, Satürn sorumluluk, Jüpiter genişleme temalarıyla yorumlanır. Etki tek çizgiyle değil, yakınlık ve relokasyon haritasıyla değerlendirilir.'],['Karar verirken','Taşınma kararı vize, iş, gelir, güvenlik, iklim ve sosyal ağ gibi gerçek verilerle verilmelidir. Astroloji bunların yerini alamaz.']],faq:[['Bir çizgide yaşamak zorunlu mu?','Hayır; çizgiler sembolik yoğunluk alanlarıdır.'],['Doğum saati önemli mi?','Evet, açı çizgileri için doğru saat kritik önemdedir.']],links:[['Doğum haritası','/astroloji'],['Bugünün gökyüzü','/bugunun-gokyuzu']]},
{slug:'travma-bilincli-astroloji',title:'Travma-Bilinçli Astroloji: Haritayı Korkutmadan Okumak',dek:'Astrolojik dili tanı, kader veya travma teşhisine dönüştürmeden; güvenlik, seçim hakkı ve sınırlar üzerinden kullan.',date:'2026-07-28',tags:['Travma-Bilinçli','Farkındalık','Etik'],sections:[['Temel ilke','Travma-bilinçli yaklaşım güvenlik, şeffaflık, iş birliği ve seçim hakkını öncelemeyi amaçlar. Astrolojide bu, kesin ve korkutucu hükümlerden kaçınmak anlamına gelir.'],['Kullanılmaması gereken dil','“Haritan bozuk”, “Bu açı travma demek” veya “İlişkin kesin bitecek” gibi ifadeler hem yanıltıcı hem de zarar verici olabilir.'],['Daha güvenli soru','“Bu sembol sende hangi deneyimi çağrıştırıyor?” sorusu, kullanıcıya kendi bağlamını ve sınırını koruma alanı verir.']],faq:[['Astroloji terapi midir?','Hayır. Terapi, tanı veya tedavinin yerini tutmaz.'],['Yoğun hissedersem ne yapmalıyım?','Çalışmayı durdur, bedensel olarak güvenli bir alana dön ve gerekirse yetkin bir uzmandan destek al.']],links:[['Güvenli farkındalık alanı','/travma-bilincli-astroloji'],['Rüya yorumları','/ruya-yorumlari']]},
{slug:'yapay-zeka-tarot-etik',title:'Yapay Zekâ ile Tarot Yorumu: Fırsatlar, Sınırlar ve Etik',dek:'AI destekli Tarot yorumunda kişiselleştirme ile aşırı kesinlik arasındaki çizgiyi nasıl koruyacağımızı incele.',date:'2026-07-28',tags:['Yapay Zekâ','Tarot','Etik'],sections:[['AI neyi iyi yapar?','Semboller arasında tema kurabilir, farklı bakış açıları üretebilir ve kullanıcının sorusunu yapılandırmasına yardım edebilir.'],['Nerede sınır gerekir?','Sağlık, hukuk, finans, ölüm veya kesin gelecek iddialarında AI güvenilir otorite gibi davranmamalıdır. Kullanıcının kaygısını artıran dil kullanılmamalıdır.'],['Mythborn standardı','Yorumlar sembolik, seçenek odaklı ve eyleme çevrilebilir sorularla sunulur. Kullanıcının karar hakkı korunur.']],faq:[['AI geleceği bilir mi?','Hayır. Üretilen yorumlar sembolik dil ve olasılık çerçevesidir.'],['Kişisel veri girmeli miyim?','Hassas sağlık, finans veya kimlik bilgilerini paylaşmamak en güvenli yaklaşımdır.']],links:[['Günlük kart','/gunluk-kart'],['3 kart Tarot','/tarot']]},
{slug:'tarot-ve-astrolojiyi-birlikte-okumak',title:'Tarot ve Astrolojiyi Birlikte Okumak: Transitlere Göre Açılım',dek:'Gökyüzü temasını Tarot sorusuna dönüştür; iki sistemi birbirini doğrulayan kehanetler değil, farklı sembol katmanları olarak kullan.',date:'2026-07-28',tags:['Tarot','Astroloji','Transit'],sections:[['İki ayrı dil','Astroloji zaman ve döngüleri, Tarot ise sorunun o andaki psikolojik ve sembolik katmanlarını görünür kılabilir.'],['Soru nasıl kurulur?','“Bu retroda ne olacak?” yerine “Bu dönemde hangi iletişim alışkanlığımı gözden geçirmeliyim?” gibi seçim alanı bırakan sorular sor.'],['Çelişki olduğunda','Kartlar ve transitler farklı temalar verirse birini iptal etmeye çalışma. Farklı zaman ölçeklerini ve bakış açılarını not et.']],faq:[['Tarot astrolojiyi doğrular mı?','Hayır. İki sistem birbirinden bağımsız sembolik araçlardır.'],['Her transit için açılım yapılır mı?','Gerekmez; yalnız gerçekten düşündüğün bir konu varsa kullan.']],links:[['Bugünün gökyüzü','/bugunun-gokyuzu'],['Tarot açılımı','/tarot']]},
{slug:'dogum-saatini-bilmiyorum',title:'Doğum Saatimi Bilmiyorum: Haritamda Neler Hesaplanabilir?',dek:'Doğum saati bilinmediğinde hangi astrolojik katmanların güvenilir kaldığını, hangilerinin neden gösterilmediğini açıkça anlatan yöntem rehberi.',date:'2026-08-14',tags:['Doğum Haritası','Doğum Saati','Yöntem'],sections:[['Saat neden önemlidir?','Doğum saati yükselen burç, evler ve MC gibi zamana duyarlı noktaları belirler. Saat bilinmiyorsa bu katmanları tahmin ederek kesin sonuç vermek yerine belirsizliği açıkça korumak gerekir.'],['Neler yine de okunabilir?','Doğum tarihiyle Güneş, çoğu gezegenin burç konumu ve bazı gezegenler arası açılar hesaplanabilir. Ay burcu sınırdaysa saat aralığı sonucu değiştirebileceğinden dikkatli yorum gerekir.'],['Güvenli çalışma yöntemi','Önce saat bilinmiyor seçeneğini kullan, yalnız güvenilir tarih-temelli sonuçları incele ve yükselen ya da ev yerleşimi isteyen yorumları kesin hüküm gibi alma. Daha sonra resmi kayıtla saat bulunduğunda haritayı yeniden hesapla.']],faq:[['Doğum saati olmadan yükselenimi bulabilir miyim?','Güvenilir biçimde hayır. Yükselen yaklaşık iki saatte bir değişebildiği için saat bilinmiyorsa tahmin üretmek doğru değildir.'],['Doğum saati olmadan doğum haritası işe yarar mı?','Evet; tarih-temelli gezegen konumları ve bazı açılar incelenebilir, ancak evler, MC ve yükselen gösterilmemelidir.'],['Saatimi sonradan bulursam ne yapmalıyım?','Haritayı yeni saat ve doğum yeriyle yeniden hesapla; önceki saat bilinmiyor yorumlarını yeni sonuçlarla karıştırma.']],links:[['Doğum haritasını hesapla','/astroloji'],['Bugünün gökyüzü','/bugunun-gokyuzu']]},
{slug:'sinastri-nasil-okunur',title:'Sinastri Nasıl Okunur? Duygu, İletişim, Çekim ve Bağlılık',dek:'İki doğum haritasını tek bir uyum puanına indirmeden Ay, Merkür, Venüs, Mars ve Satürn temaslarını bağlam içinde okuma rehberi.',date:'2026-08-14',tags:['Sinastri','İlişki Astrolojisi','Yöntem'],sections:[['Önce veri kalitesini kontrol et','İki kişinin doğum tarihi, yeri ve mümkünse saati doğru olmalıdır. Saat bilinmiyorsa yükselen, evler ve açıların bazı bağlamları sınırlı kalır; bu durum sonuçta görünür olmalıdır.'],['İlişkinin farklı işlevlerini ayır','Ay duygusal güveni, Merkür iletişimi, Venüs yakınlık ve değerleri, Mars çekim ve çatışma ritmini, Satürn ise sorumluluk ve sınırları incelemek için ayrı mercekler sunar.'],['Uyum puanı neden yetmez?','Bir açı tek başına ilişki kalitesini belirlemez. Kolay açılar garanti, zorlayıcı açılar da başarısızlık demek değildir; davranış, değerler, rıza ve gerçek koşullar her zaman yorumun üstündedir.']],faq:[['Sinastride ilk olarak neye bakılır?','Önce veri kalitesine, sonra Ay, Merkür, Venüs, Mars ve Satürn temaslarına; ardından açıların haritanın bütünü içindeki rolüne bakılır.'],['Doğum saati sinastri için şart mı?','Açı ve gezegen karşılaştırmaları için her zaman şart değildir; ancak yükselen, evler ve açıların kişisel bağlamı için önemlidir.'],['Zorlayıcı sinastri açısı kötü ilişki mi demektir?','Hayır. Zorlayıcı açı bir gerilim veya çalışma alanı gösterebilir; ilişki hakkında hüküm vermek için davranış ve gerçek yaşam bağlamı gerekir.']],links:[['Sinastri hesapla','/sinastri'],['Burç uyumu','/burc-uyumu'],['Doğum haritası','/astroloji']]},
{slug:'uc-kart-tarot-nasil-okunur',title:'3 Kart Tarot Nasıl Okunur? Kartları Bağlam İçinde Birleştirme',dek:'Geçmiş-şimdi-gelecek kalıbını tek doğru saymadan üç kartı soru, sıra, tekrar eden semboller ve seçim alanıyla birlikte yorumla.',date:'2026-08-14',tags:['Tarot','3 Kart Açılımı','Yöntem'],sections:[['Soruyu daralt','“Ne olacak?” gibi kontrol edilemez bir soru yerine “Bu konuda hangi dinamiği fark etmeliyim?” veya “Bir sonraki adımımı netleştirmek için neyi gözden geçirmeliyim?” gibi açık ve eyleme dönük bir soru kur.'],['Kartları ayrı değil, cümle gibi oku','Üç kartı tek tek kehanet olarak yorumlamak yerine pozisyonları, ortak renkleri, tekrar eden sayıları ve kartlar arasındaki gerilimi birlikte incele. Geçmiş-şimdi-gelecek yalnızca seçeneklerden biridir.'],['Kesinlik sınırını koru','Tarot geleceği doğrulanmış biçimde bilmez. Yorum, kararın yerine geçmez; sana seçenekleri, duyguları ve gözden kaçan soruları fark etmek için sembolik bir çerçeve sunar.']],faq:[['3 kart Tarot’ta pozisyonlar nasıl seçilir?','Geçmiş-şimdi-gelecek kullanılabilir; fakat durum-seçenek-sonraki adım veya duygu-engel-kaynak gibi soruya uygun pozisyonlar da daha anlamlı olabilir.'],['Kartları ters çevirmek şart mı?','Hayır. Ters kartlar zorunlu bir kural değildir; önemli olan seçtiğin yöntemi baştan belirleyip tutarlı uygulamaktır.'],['Aynı soruyu tekrar tekrar sormalı mıyım?','Genellikle hayır. Tekrar tekrar açılım yapmak belirsizliği azaltmak yerine kaygıyı ve onay aramayı artırabilir; önceki yorumu gerçek yaşam gözlemiyle değerlendir.']],links:[['3 kart Tarot açılımı','/tarot'],['78 kart Tarot ansiklopedisi','/tarot-kartlari'],['Günlük kart','/gunluk-kart']]}
];



const zodiac2027Profiles=[
  {slug:'koc',name:'Koç',focus:'inisiyatif, cesaret ve yön değiştirme',love:'ilişkide hız ile karşılıklılık arasındaki denge',career:'liderlik, yeni sorumluluklar ve görünürlük',money:'dürtüsel harcama yerine kaynak planı',eclipse:'yaratıcılık, aşk ve kişisel ifade',retro:'Mars retrosunda enerjiyi dağıtan işleri azaltmak'},
  {slug:'boga',name:'Boğa',focus:'istikrar, değerler ve güvenli büyüme',love:'güven, sadakat ve ortak yaşam düzeni',career:'kalıcı yapı kurmak ve gelir modelini sağlamlaştırmak',money:'fiyatlandırma, birikim ve gereksiz sabit giderler',eclipse:'ev, aile ve yaşam alanı',retro:'esneklik gerektiren planlarda inadı azaltmak'},
  {slug:'ikizler',name:'İkizler',focus:'iletişim, öğrenme ve çevik karar verme',love:'açık iletişim ve zihinsel yakınlık',career:'yazma, eğitim, satış, medya ve çoklu projeler',money:'gelir kanallarını çeşitlendirirken odağı korumak',eclipse:'iletişim, eğitim ve yakın çevre',retro:'aynı anda çok fazla projeye enerji dağıtmamak'},
  {slug:'yengec',name:'Yengeç',focus:'güvenlik, aidiyet ve duygusal sınırlar',love:'duygusal güven ile aşırı korumacılığı ayırmak',career:'istikrarlı çalışma düzeni ve sürdürülebilir tempo',money:'özdeğer ile gelir kararlarını birbirinden ayırmak',eclipse:'para, özdeğer ve sahip oldukların',retro:'duygusal tepkiyle alınan kararları yeniden kontrol etmek'},
  {slug:'aslan',name:'Aslan',focus:'görünürlük, yaratıcılık ve kişisel yön',love:'ilgi görmek ile gerçek yakınlığı ayırmak',career:'kişisel marka, liderlik ve sahneye çıkmak',money:'gösteriş harcamaları yerine yaratıcı yatırımlar',eclipse:'kimlik, beden algısı ve yeni kişisel dönem',retro:'performans baskısını azaltıp enerjiyi yeniden toplamak'},
  {slug:'basak',name:'Başak',focus:'sistem, iyileştirme ve uygulanabilir düzen',love:'eleştiri yerine net ihtiyaç ifade etmek',career:'iş akışı, uzmanlık ve verimlilik',money:'küçük kayıpları, abonelikleri ve tekrar eden giderleri temizlemek',eclipse:'dinlenme, kapanış ve perde arkası hazırlık',retro:'mükemmeliyetçilik nedeniyle tükenmeyi önlemek'},
  {slug:'terazi',name:'Terazi',focus:'denge, ortaklık ve stratejik seçim',love:'karşılıklılık, sınır ve ortak kararlar',career:'iş birlikleri, müşteri ilişkileri ve görünür ağlar',money:'ortak harcamalar ile kişisel bütçeyi ayırmak',eclipse:'arkadaşlıklar, topluluklar ve gelecek planları',retro:'herkesi memnun etmeye çalışırken enerjiyi kaybetmemek'},
  {slug:'akrep',name:'Akrep',focus:'derinleşme, strateji ve dönüşüm',love:'güven, mahremiyet ve kontrol ihtiyacını ayırt etmek',career:'otorite, uzmanlık ve yüksek sorumluluk',money:'borç, ortak kaynak ve risk yönetimi',eclipse:'kariyer, statü ve kamusal görünürlük',retro:'gizli güç mücadelelerine enerji harcamamak'},
  {slug:'yay',name:'Yay',focus:'büyüme, öğrenme ve ufku genişletme',love:'özgürlük ile bağlılığı aynı anda taşıyabilmek',career:'uluslararası işler, eğitim, yayıncılık ve yeni pazarlar',money:'büyüme hevesiyle kapasitenin önüne geçmemek',eclipse:'seyahat, yüksek öğrenim ve dünya görüşü',retro:'plansız riskleri ve aşırı dağınık hedefleri azaltmak'},
  {slug:'oglak',name:'Oğlak',focus:'uzun vadeli yapı, sorumluluk ve sonuç',love:'duygusal mesafe ile sağlıklı sınırı ayırmak',career:'yetki, sistem kurma ve uzun vadeli pozisyon',money:'borç, yatırım ve ortak finansman',eclipse:'ortak para, mahremiyet ve psikolojik derinlik',retro:'sadece görev odaklı yaşarken motivasyonu tüketmemek'},
  {slug:'kova',name:'Kova',focus:'yenilik, bağımsızlık ve topluluk',love:'özgür alan ile duygusal erişilebilirlik arasında denge',career:'teknoloji, ağlar ve farklılaşan fikirler',money:'yenilikçi gelir modellerini gerçekçi veriyle test etmek',eclipse:'ilişkiler, ortaklıklar ve sözleşmeler',retro:'entelektüel mesafeyi iletişim kopukluğuna çevirmemek'},
  {slug:'balik',name:'Balık',focus:'sezgi, yaratıcılık ve sınır netliği',love:'idealizasyon ile gerçek davranışı ayırmak',career:'yaratıcı işler, hizmet ve anlam odaklı çalışma',money:'belirsiz harcamalara ve dağınık bütçeye sınır koymak',eclipse:'iş rutini, günlük düzen ve beden bakımı',retro:'enerji sızıntılarını fark edip ritmi sadeleştirmek'}
];

const zodiac2027Articles=zodiac2027Profiles.map((z,index)=>({
  slug:`${z.slug}-burcu-2027-yillik-yorum`,
  title:`${z.name} Burcu 2027: Aşk, Kariyer, Para, Retro ve Tutulma Rehberi`,
  dek:`${z.name} burcu için 2027'yi tek cümlelik kehanetlerle değil; aşk, kariyer, para, retro dönemleri, tutulmalar ve uygulanabilir yıllık plan üzerinden detaylı incele.`,
  date:'2026-09-30',
  tags:[z.name,'2027 Burç Yorumu','Yıllık Astroloji','2027'],
  sections:[
    ['2027 ana teması',`2027’de ${z.name} için ana çalışma alanı ${z.focus}. Yılı “iyi” veya “kötü” diye etiketlemek yerine hangi alışkanlığın büyümeyi desteklediğini, hangisinin ise enerji tükettiğini görmek daha kullanışlıdır. Transitler tek başına olay yaratmaz; kişisel doğum haritası, yaşam koşulları ve alınan kararlar yorumu belirgin biçimde değiştirir.`],
    ['Aşk ve ilişkiler',`${z.name} için ilişkilerde öne çıkan konu ${z.love}. Venüs retrosu 3 Ekim–14 Kasım 2026’da başlayan değerlendirme döngüsünün etkilerini 2027’nin ilk bölümüne taşıyabilir; geçmiş ilişki kalıplarını yeniden düşünmek mümkün olsa da belirli bir kişinin geri döneceğine veya bir ilişkinin biteceğine dair garanti yoktur. İlişkide davranış, açık iletişim ve sınırlar astrolojik sembollerden daha belirleyicidir.`],
    ['Kariyer ve iş',`Kariyer tarafında ${z.career} öne çıkabilir. Mars’ın 10 Ocak–1 Nisan 2027 arasındaki retrosu, enerjiyi daha fazla harcamak yerine çalışma yöntemini yeniden düzenlemek için kullanılabilir. Özellikle görev dağılımı, zaman yönetimi ve sürdürülemeyen hedefler gözden geçirildiğinde yılın ikinci bölümünde daha net bir yön oluşabilir.`],
    ['Para ve kaynaklar',`Finansal odakta ${z.money}. 2027’de astrolojik zamanlamayı yatırım sinyali gibi kullanmak yerine bütçe, nakit akışı, borç, sözleşme ve riskleri gerçek verilerle takip etmek gerekir. Retro dönemleri harcamaları ve taahhütleri ikinci kez kontrol etmek için yalnızca bir hatırlatıcı olarak kullanılabilir.`],
    ['2 Ağustos 2027 Güneş tutulması',`2 Ağustos 2027’de yaklaşık 9°55′ Aslan’da gerçekleşen tam Güneş tutulması, ${z.name} için sembolik olarak ${z.eclipse} alanını öne çıkarabilir. Kişisel etkiyi anlamak için yalnız Güneş burcuna değil, haritada 7°–13° Aslan, Kova, Boğa ve Akrep civarında gezegen veya açı noktası olup olmadığına bakmak daha anlamlıdır.`],
    ['Mars retrosunda dikkat',`Mars retrosunun ${z.name} açısından temel dersi ${z.retro}. 10 Ocak–1 Nisan döneminde çatışmayı büyütmek, aynı yöntemi daha fazla zorlamak veya kapasitenin üzerinde yük almak yerine stratejiyi yeniden kurmak daha verimli olabilir. Fiziksel sağlıkla ilgili kararlar için astroloji yerine tıbbi değerlendirme esas alınmalıdır.`],
    ['Merkür retrosu dönemleri',`2027’de üç Merkür retrosu bulunuyor: Şubat–Mart, Haziran–Temmuz ve Ekim dönemleri. ${z.name} için bu zamanlarda iletişim, sözleşme, ödeme, seyahat planı ve dijital dosyalarda kontrol listesi kullanmak yararlı olabilir. “Hiçbir şey imzalanmaz” gibi kesin yasaklar yerine metinleri ikinci kez okumak, yedek almak ve varsayım yerine soru sormak daha rasyoneldir.`],
    ['Yılın ilk yarısı',`Ocak–Nisan arası enerji yönetimi ve mevcut planların yeniden yapılandırılması öne çıkar. İlk yarıda hızdan çok dayanıklılığa odaklanmak, ${z.name} için yılın geri kalanını daha sağlam zemine oturtabilir. Mayıs ve Haziran, revize edilen planları test etmek için daha uygun bir geçiş alanı gibi kullanılabilir.`],
    ['Yılın ikinci yarısı',`Temmuzdan sonra görünürlük ve dış dünyaya açılma isteği artabilir. Ağustos tutulması çevresinde büyük kararları tek bir güne bağlamak yerine birkaç haftalık gözlem alanı bırakmak yararlıdır. Ekim ve Kasımda iletişim ve planlama başlıkları tekrar gözden geçirilirken yıl sonunda hangi yapıların 2028’e taşınacağı daha net hale gelebilir.`],
    ['2027 için uygulanabilir plan',`Yılın başında üç başlık seç: sürdürmek istediğin bir yapı, bırakmak istediğin bir yük ve büyütmek istediğin bir alan. Her çeyrek sonunda bunları gerçek sonuçlarla karşılaştır. Böylece ${z.name} 2027 yorumunu soyut bir tahmin yerine davranış, kaynak ve karar takibi için kullanılabilir bir çerçeveye dönüştürmüş olursun.`]
  ],
  faq:[
    [`${z.name} burcu 2027’de nasıl bir yıl geçirecek?`,`Ana tema ${z.focus}; ancak kişisel deneyim doğum haritasındaki yükselen, evler ve natal açılara göre değişir.`],
    [`${z.name} için 2027 aşk hayatı nasıl?`,`İlişki tarafında ${z.love} öne çıkan sembolik temadır. Kesin ilişki sonucu verilemez.`],
    [`${z.name} için 2027 kariyer açısından nasıl?`,`${z.career} üzerinde çalışmak yıl boyunca daha anlamlı olabilir; iş kararlarında gerçek fırsat ve koşullar önceliklidir.`],
    [`${z.name} 2027 Güneş tutulmasından nasıl etkilenir?`,`2 Ağustos tutulması sembolik olarak ${z.eclipse} alanını vurgulayabilir. Kişisel etki için doğum haritasındaki derece ve ev yerleşimleri gerekir.`],
    [`2027’de ${z.name} için dikkat edilmesi gereken retro hangisi?`,`Mars retrosu enerji ve strateji açısından özellikle dikkat çekicidir; Merkür retroları ise iletişim ve planlama kontrolleri için kullanılabilir.`]
  ],
  links:[
    ['2027 astroloji takvimi','/blog/2027-astroloji-takvimi-retrolar-tutulmalar'],
    ['Doğum haritanı hesapla','/astroloji'],
    ['2 Ağustos 2027 tutulması','/blog/2-agustos-2027-gunes-tutulmasi-aslan'],
    ['Bugünün gökyüzü','/bugunun-gokyuzu']
  ]
}));

articles.push(...zodiac2027Articles);



const blogHubGroups=[
  ['2027 Rehberleri',a=>a.slug.includes('2027')],
  ['Retrolar',a=>a.slug.includes('retro')],
  ['Tutulmalar',a=>a.slug.includes('tutul')],
  ['İlişki Astrolojisi',a=>a.slug.includes('sinastri')||a.slug.includes('venus')||a.tags.some(t=>/aşk|ilişki/i.test(t))]
];
const renderBlogHub=()=>{
  const seen=new Set();
  const groups=blogHubGroups.map(([title,test])=>{
    const items=articles.filter(a=>test(a)&&!seen.has(a.slug)).slice(0,6);
    items.forEach(a=>seen.add(a.slug));
    if(!items.length)return '';
    return `<section class="blog-topic-group"><div class="blog-topic-head"><p class="eyebrow">MYTHBORN · ${title.toUpperCase()}</p><h2>${title}</h2></div><div class="blog-topic-grid">${items.map(a=>`<a class="blog-topic-card" href="/blog/${a.slug}"><small>${a.tags.slice(0,2).join(' · ')}</small><strong>${esc(a.title)}</strong><span>Rehberi aç →</span></a>`).join('')}</div></section>`;
  }).join('');
  const latest=articles.filter(a=>!seen.has(a.slug)).slice(0,12);
  return `<section class="blog-hub">${groups}<section class="blog-topic-group"><div class="blog-topic-head"><p class="eyebrow">SON EKLENENLER</p><h2>Diğer rehberler</h2></div><div class="blog-grid">${latest.map(a=>`<article class="blog-card"><small>${a.tags.join(' · ')}</small><h2>${esc(a.title)}</h2><p>${esc(a.dek)}</p><a href="/blog/${a.slug}">Yazıyı oku →</a></article>`).join('')}</div></section></section>`;
};

export const blogRoutes=['/blog',...articles.map(a=>`/blog/${a.slug}`)];
export const blogMeta=Object.fromEntries([['/blog',['Astroloji, Tarot ve Gökyüzü Blogu','2027 astroloji takvimi, Mars ve Merkür retroları, tutulmalar, sinastri, doğum haritası ve Tarot rehberleri.']],...articles.map(a=>[`/blog/${a.slug}`,[a.title,a.dek]])]);
export const blogDates=Object.fromEntries(articles.map(a=>[`/blog/${a.slug}`,a.date]));
export const blogFaqs=Object.fromEntries(articles.map(a=>[`/blog/${a.slug}`,a.faq]));
export function blogPage(path){
  if(path==='/blog') return shell('Mythborn Blog','Astroloji ve Tarot rehberleri','<section class="blog-hero"><p class="eyebrow">GÖKYÜZÜ GÜNDEMİ · DERİN REHBERLER</p><h1>Bugünün merakını, yarının arşivine dönüştür.</h1><p class="lead left-lead">Güncel gökyüzü olayları, ilişki astrolojisi, etik ve kişisel farkındalık üzerine özgün uzun form içerikler.</p></section>'+renderBlogHub());
  const a=articles.find(x=>path==='/blog/'+x.slug);
  if(!a) return null;
  return shell(a.title,a.dek,'<article class="article"><a href="/blog">← Tüm yazılar</a><p class="article-tags">' + a.tags.join(' · ') + '</p><h1>' + esc(a.title) + '</h1><p class="article-meta">MYTHBORN EDITORIAL DESK · ' + a.date + '</p><p class="article-lead">' + esc(a.dek) + '</p><div class="article-body">' + a.sections.map(([h,p])=>`<section><h2>${esc(h)}</h2><p>${esc(p)}</p></section>`).join('') + '<section class="article-faq"><p class="eyebrow">SIK SORULANLAR</p><h2>Konuyla ilgili kısa yanıtlar.</h2>' + a.faq.map(([q,r])=>`<details><summary>${esc(q)}</summary><p>${esc(r)}</p></details>`).join('') + '</section><div class="article-links">' + a.links.map(([t,u])=>`<a href="${u}">${esc(t)} →</a>`).join('') + '</div><p class="article-note">Bu içerik eğlence, eğitim ve kişisel farkındalık amaçlıdır. Astroloji bilimsel bir tanı veya tedavi yerine geçmez.</p></article>');
}
