const localePath=(locale,path)=>`${locale==='tr'?'':locale==='en'?'/en':'/gr'}${path==='/'?'':path}`||'/';
const link=(locale,path,label,kind='btn btn-ghost')=>`<a class="${kind}" href="${localePath(locale,path)}">${label}</a>`;

const copy={
  tr:{
    meta:{
      '/':['Mythborn — Tarot, Astroloji ve Sembolik Farkındalık','Gerçek astronomik veriler, günlük Tarot ve haftalık burç yorumlarıyla ücretsiz kişisel farkındalık platformu.'],
      '/gunluk-kart':['Günlük Tarot Kartı','Üye olmadan ücretsiz günlük Tarot kartını aç ve günün mesajını gör.'],
      '/haftalik-burc':['Haftalık Burç Yorumları','12 burç için haftalık enerji, aşk, kariyer, para ve farkındalık rehberi.'],
      '/astroloji':['Doğum Haritası ve Astroloji','Gerçek astronomik verilerle ücretsiz doğum haritası hesapla.']
    },
    home:{eyebrow:'MYTHBORN · GÖKYÜZÜ VE SEMBOL MERKEZİ',title:'Gökyüzünü oku.',em:'Kendini keşfet.',lead:'Gerçek astronomik verilerle doğum haritası ve sinastri; günlük Tarot, haftalık burç, rüya yorumları ve kadim gökyüzü gelenekleri tek merkezde.',sky:'Bugünün gökyüzünü gör',chart:'Doğum haritamı çıkar',daily:'Günlük kartımı aç',free:'TÜM DENEYİMLER ÜCRETSİZ',loading:'Gökyüzü hesaplanıyor…',loadingCopy:'Güneş, Ay ve günün belirgin açıları hazırlanıyor.',today:'BUGÜNÜN GÖKYÜZÜ',discover:'Keşfet →',sections:[
      ['BUGÜN MYTHBORN’DA','Her gün geri dönmek için dört güçlü neden.','Güncel, hızlı ve gerçekten çalışan deneyimler.',[['CANLI VERİ','Bugünün Gökyüzü','Gerçek zamanlı gezegen konumları ve majör açılar.','/bugunun-gokyuzu'],['HER HAFTA','Haftalık Burç','12 burç için aşk, kariyer, para ve enerji.','/haftalik-burc'],['HER GÜN','Günlük Tarot','Üye olmadan günün tek kartını aç.','/gunluk-kart'],['AY DÖNGÜSÜ','Ay Takvimi','Ay fazı, aydınlanma ve döngü teması.','/ay-takvimi']]],
      ['ÖNE ÇIKANLAR','Seçilmiş Mythborn deneyimleri.','Kişisel haritadan iki gerçek haritanın karşılaştırmasına uzanan keşif yolları.',[['GERÇEK HESAPLAMA','Doğum Haritası','Güneş, Ay, Yükselen, evler, gezegenler ve açılar.','/astroloji'],['İKİ HARİTA','Sinastri','Duygu, iletişim, çekim ve bağlılığı gerçek açılarla karşılaştır.','/sinastri'],['SEMBOLLER','Rüya Yorumları','Duygu ve sembolleri yapılandırılmış biçimde incele.','/ruya-yorumlari'],['AŞK','Katina','Duygusal bağlar ve ilişki dinamikleri.','/katina']]],
      ['KADİM GÖKYÜZÜ','Tarih, kültür ve sembol.','Tarihsel sistemleri kaynak ve yöntem şeffaflığıyla keşfet.',[['MAYA','Maya Zaman Döngüleri','Tzolk’in, Haab, Takvim Turu ve Uzun Sayım.','/maya-zaman-donguleri'],['MEZOPOTAMYA','Sümer, Babil ve Asur','Alametlerden zodyağa uzanan tarih.','/mezopotamya-astrolojisi'],['DOĞA RİTİMLERİ','Doğa ve Gökyüzü','Mevsim, yön, Ay ve yerel doğa döngüleri.','/doga-gokyuzu-donguleri'],['GÜVENLİ FARKINDALIK','Travma-Bilinçli Astroloji','Güvenlik, sınır ve seçim odaklı öz-refleksiyon.','/travma-bilincli-astroloji']]]
    ],memberEye:'KİŞİSEL MERKEZ',memberTitle:'Haritanı ve açılımlarını tek hesapta sakla.',memberCopy:'Ücretsiz hesabınla kişisel deneyimlerine her cihazdan eriş.',join:'Ücretsiz hesap oluştur',login:'Giriş yap'},
    daily:{eye:'ÜYELİK GEREKTİRMEZ',title:'Bugünün kartı seni bekliyor.',lead:'Kart destesine dokun. Aynı gün içinde açtığın kart değişmez.',aria:'Günlük Tarot kartını aç',result:'BUGÜNÜN KARTI',more:'Diğer ücretsiz açılımları aç'},
    weekly:{eye:'12 BURÇ · HER HAFTA YENİ',title:'Bu hafta gökyüzü senin burcuna ne söylüyor?',lead:'Burcunu seç; haftanın enerjisini, aşk, kariyer ve para gündemini, dikkat noktasını, güçlü gününü ve haftalık tavsiyeni gör.',updated:'Son güncelleme',about:'Bu rehber nasıl hazırlanır?',aboutCards:[['Haftanın ritmi','Yorumlar haftanın ortak gökyüzü temalarını her burcun elementi ve niteliğiyle birlikte ele alır.'],['Sembolik rehber','Metinler kesin gelecek iddiası taşımaz; düşünme ve karar süreçlerine eşlik eder.'],['Her hafta yenilenir','Tarih aralığı pazartesiden pazara gösterilir ve seçimin paylaşılabilir URL’de korunur.']]},
    auth:{email:'E-posta',password:'Şifre',consent:'Kullanım koşullarını ve KVKK metnini okudum.',loginEye:'TEKRAR HOŞ GELDİN',joinEye:'TAMAMEN ÜCRETSİZ',loginTitle:'Hesabına giriş yap.',joinTitle:'Tüm açılımları aç.',login:'Giriş yap',join:'Ücretsiz hesap oluştur'},
    common:{gate:'ÜCRETSİZ ÜYELİKLE AÇILIR',checking:'Üyelik durumu kontrol ediliyor…',join:'Ücretsiz üye ol',existing:'Zaten üyeyim'}
  },
  en:{
    meta:{
      '/':['Mythborn — Tarot, Astrology and Symbolic Reflection','A free platform for real astronomical data, daily Tarot and weekly horoscope guidance.'],
      '/gunluk-kart':['Daily Tarot Card','Draw your free daily Tarot card without an account and explore today’s message.'],
      '/haftalik-burc':['Weekly Horoscopes','Weekly energy, love, career, money and reflection guidance for all 12 zodiac signs.'],
      '/astroloji':['Birth Chart and Astrology','Calculate a free birth chart with real astronomical data.']
    },
    home:{eyebrow:'MYTHBORN · SKY AND SYMBOL CENTRE',title:'Read the sky.',em:'Discover yourself.',lead:'Birth charts and synastry based on real astronomical data, daily Tarot, weekly horoscopes, dream interpretation and ancient sky traditions—all in one place.',sky:'See today’s sky',chart:'Calculate my birth chart',daily:'Draw my daily card',free:'ALL EXPERIENCES ARE FREE',loading:'Calculating the sky…',loadingCopy:'Preparing the Sun, Moon and today’s major aspects.',today:'TODAY’S SKY',discover:'Explore →',sections:[
      ['TODAY ON MYTHBORN','Four meaningful reasons to return every day.','Current, focused experiences that genuinely work.',[['LIVE DATA','Today’s Sky','Real-time planetary positions and major aspects.','/bugunun-gokyuzu'],['EVERY WEEK','Weekly Horoscope','Love, career, money and energy for all 12 signs.','/haftalik-burc'],['EVERY DAY','Daily Tarot','Draw one card for the day without an account.','/gunluk-kart'],['LUNAR CYCLE','Moon Calendar','Moon phase, illumination and cycle themes.','/ay-takvimi']]],
      ['FEATURED','Selected Mythborn experiences.','From a personal chart to the comparison of two real charts.',[['REAL CALCULATION','Birth Chart','Sun, Moon, Rising, houses, planets and aspects.','/astroloji'],['TWO CHARTS','Synastry','Compare emotion, communication, attraction and commitment through real aspects.','/sinastri'],['SYMBOLS','Dream Interpretation','Explore emotions and symbols in a structured way.','/ruya-yorumlari'],['LOVE','Katina','Emotional bonds and relationship dynamics.','/katina']]],
      ['ANCIENT SKY','History, culture and symbol.','Explore historical systems with transparent sources and methods.',[['MAYA','Maya Time Cycles','Tzolk’in, Haab, the Calendar Round and Long Count.','/maya-zaman-donguleri'],['MESOPOTAMIA','Sumer, Babylon and Assyria','From celestial omens to the zodiac.','/mezopotamya-astrolojisi'],['NATURAL RHYTHMS','Nature and Sky','Seasons, directions, the Moon and local natural cycles.','/doga-gokyuzu-donguleri'],['SAFE REFLECTION','Trauma-Informed Astrology','Reflection centred on safety, boundaries and choice.','/travma-bilincli-astroloji']]]
    ],memberEye:'PERSONAL CENTRE',memberTitle:'Keep your chart and readings in one account.',memberCopy:'Access your personal experiences from any device with a free account.',join:'Create a free account',login:'Sign in'},
    daily:{eye:'NO ACCOUNT REQUIRED',title:'Today’s card is waiting for you.',lead:'Tap the deck. The card you draw remains the same throughout the day.',aria:'Reveal today’s Tarot card',result:'TODAY’S CARD',more:'Unlock more free readings'},
    weekly:{eye:'12 SIGNS · UPDATED WEEKLY',title:'What does the sky suggest for your sign this week?',lead:'Choose your sign to explore the week’s energy, love, career and money themes, what to watch, your power day and practical advice.',updated:'Last updated',about:'How this guide is prepared',aboutCards:[['The week’s rhythm','Guidance combines the week’s shared sky themes with the element and modality of each sign.'],['Symbolic guidance','The text does not claim certainty about the future; it supports reflection and considered choices.'],['Refreshed weekly','The date range runs Monday to Sunday, and your selected sign remains in a shareable URL.']]},
    auth:{email:'Email',password:'Password',consent:'I have read the Terms of Use and the Turkish data protection notice.',loginEye:'WELCOME BACK',joinEye:'COMPLETELY FREE',loginTitle:'Sign in to your account.',joinTitle:'Unlock every reading.',login:'Sign in',join:'Create free account'},
    common:{gate:'UNLOCKED WITH FREE MEMBERSHIP',checking:'Checking membership status…',join:'Join free',existing:'I already have an account'}
  },
  el:{
    meta:{
      '/':['Mythborn — Ταρώ, Αστρολογία και Συμβολικός Στοχασμός','Δωρεάν πλατφόρμα με πραγματικά αστρονομικά δεδομένα, ημερήσιο Ταρώ και εβδομαδιαίες αστρολογικές τάσεις.'],
      '/gunluk-kart':['Ημερήσια Κάρτα Ταρώ','Τράβηξε δωρεάν την ημερήσια κάρτα Ταρώ χωρίς λογαριασμό και ανακάλυψε το μήνυμα της ημέρας.'],
      '/haftalik-burc':['Εβδομαδιαίο Ωροσκόπιο','Εβδομαδιαία καθοδήγηση για ενέργεια, αγάπη, καριέρα και χρήματα για τα 12 ζώδια.'],
      '/astroloji':['Γενέθλιος Χάρτης και Αστρολογία','Υπολόγισε δωρεάν τον γενέθλιο χάρτη σου με πραγματικά αστρονομικά δεδομένα.']
    },
    home:{eyebrow:'MYTHBORN · ΚΕΝΤΡΟ ΟΥΡΑΝΟΥ ΚΑΙ ΣΥΜΒΟΛΩΝ',title:'Διάβασε τον ουρανό.',em:'Ανακάλυψε τον εαυτό σου.',lead:'Γενέθλιοι χάρτες και συναστρία με πραγματικά αστρονομικά δεδομένα, ημερήσιο Ταρώ, εβδομαδιαία ωροσκόπια, ερμηνεία ονείρων και αρχαίες ουράνιες παραδόσεις σε ένα μέρος.',sky:'Δες τον σημερινό ουρανό',chart:'Υπολόγισε τον γενέθλιο χάρτη',daily:'Τράβηξε την ημερήσια κάρτα',free:'ΟΛΕΣ ΟΙ ΕΜΠΕΙΡΙΕΣ ΕΙΝΑΙ ΔΩΡΕΑΝ',loading:'Υπολογισμός ουρανού…',loadingCopy:'Υπολογίζονται ο Ήλιος, η Σελήνη και οι κύριες όψεις της ημέρας.',today:'Ο ΣΗΜΕΡΙΝΟΣ ΟΥΡΑΝΟΣ',discover:'Εξερεύνηση →',sections:[
      ['ΣΗΜΕΡΑ ΣΤΟ MYTHBORN','Τέσσερις ουσιαστικοί λόγοι να επιστρέφεις καθημερινά.','Επίκαιρες, εστιασμένες εμπειρίες που λειτουργούν πραγματικά.',[['ΖΩΝΤΑΝΑ ΔΕΔΟΜΕΝΑ','Ο Σημερινός Ουρανός','Θέσεις πλανητών και κύριες όψεις σε πραγματικό χρόνο.','/bugunun-gokyuzu'],['ΚΑΘΕ ΕΒΔΟΜΑΔΑ','Εβδομαδιαίο Ωροσκόπιο','Αγάπη, καριέρα, χρήματα και ενέργεια για τα 12 ζώδια.','/haftalik-burc'],['ΚΑΘΕ ΜΕΡΑ','Ημερήσιο Ταρώ','Τράβηξε την κάρτα της ημέρας χωρίς λογαριασμό.','/gunluk-kart'],['ΣΕΛΗΝΙΑΚΟΣ ΚΥΚΛΟΣ','Σεληνιακό Ημερολόγιο','Φάση, φωτισμός και θέματα του σεληνιακού κύκλου.','/ay-takvimi']]],
      ['ΕΠΙΛΕΓΜΕΝΑ','Επιλεγμένες εμπειρίες του Mythborn.','Από τον προσωπικό χάρτη έως τη σύγκριση δύο πραγματικών χαρτών.',[['ΠΡΑΓΜΑΤΙΚΟΣ ΥΠΟΛΟΓΙΣΜΟΣ','Γενέθλιος Χάρτης','Ήλιος, Σελήνη, Ωροσκόπος, οίκοι, πλανήτες και όψεις.','/astroloji'],['ΔΥΟ ΧΑΡΤΕΣ','Συναστρία','Σύγκρινε συναίσθημα, επικοινωνία, έλξη και δέσμευση μέσα από πραγματικές όψεις.','/sinastri'],['ΣΥΜΒΟΛΑ','Ερμηνεία Ονείρων','Εξερεύνησε συναισθήματα και σύμβολα με δομημένο τρόπο.','/ruya-yorumlari'],['ΑΓΑΠΗ','Κατίνα','Συναισθηματικοί δεσμοί και δυναμικές σχέσεων.','/katina']]],
      ['ΑΡΧΑΙΟΣ ΟΥΡΑΝΟΣ','Ιστορία, πολιτισμός και σύμβολο.','Εξερεύνησε ιστορικά συστήματα με διαφανείς πηγές και μεθόδους.',[['ΜΑΓΙΑ','Κύκλοι Χρόνου των Μάγια','Tzolk’in, Haab, Ημερολογιακός Γύρος και Μακρά Αρίθμηση.','/maya-zaman-donguleri'],['ΜΕΣΟΠΟΤΑΜΙΑ','Σουμέριοι, Βαβυλώνιοι και Ασσύριοι','Από τους ουράνιους οιωνούς στον ζωδιακό.','/mezopotamya-astrolojisi'],['ΡΥΘΜΟΙ ΤΗΣ ΦΥΣΗΣ','Φύση και Ουρανός','Εποχές, κατευθύνσεις, Σελήνη και τοπικοί φυσικοί κύκλοι.','/doga-gokyuzu-donguleri'],['ΑΣΦΑΛΗΣ ΣΤΟΧΑΣΜΟΣ','Αστρολογία με Επίγνωση Τραύματος','Στοχασμός με επίκεντρο την ασφάλεια, τα όρια και την επιλογή.','/travma-bilincli-astroloji']]]
    ],memberEye:'ΠΡΟΣΩΠΙΚΟ ΚΕΝΤΡΟ',memberTitle:'Φύλαξε τον χάρτη και τις αναγνώσεις σου σε έναν λογαριασμό.',memberCopy:'Πρόσβαση στις προσωπικές εμπειρίες σου από κάθε συσκευή με δωρεάν λογαριασμό.',join:'Δημιουργία δωρεάν λογαριασμού',login:'Σύνδεση'},
    daily:{eye:'ΧΩΡΙΣ ΛΟΓΑΡΙΑΣΜΟ',title:'Η σημερινή κάρτα σε περιμένει.',lead:'Άγγιξε την τράπουλα. Η κάρτα που θα τραβήξεις παραμένει ίδια όλη την ημέρα.',aria:'Αποκάλυψη της σημερινής κάρτας Ταρώ',result:'Η ΣΗΜΕΡΙΝΗ ΚΑΡΤΑ',more:'Ξεκλείδωσε περισσότερες δωρεάν αναγνώσεις'},
    weekly:{eye:'12 ΖΩΔΙΑ · ΚΑΘΕ ΕΒΔΟΜΑΔΑ',title:'Τι προτείνει ο ουρανός για το ζώδιό σου αυτή την εβδομάδα;',lead:'Επίλεξε το ζώδιό σου για την ενέργεια, την αγάπη, την καριέρα και τα χρήματα, τι χρειάζεται προσοχή, τη δυνατή ημέρα και μία πρακτική συμβουλή.',updated:'Τελευταία ενημέρωση',about:'Πώς προετοιμάζεται αυτός ο οδηγός',aboutCards:[['Ο ρυθμός της εβδομάδας','Η καθοδήγηση συνδυάζει τα κοινά ουράνια θέματα με το στοιχείο και την ποιότητα κάθε ζωδίου.'],['Συμβολική καθοδήγηση','Το κείμενο δεν προβάλλει βεβαιότητες για το μέλλον· υποστηρίζει τον στοχασμό και τις συνειδητές επιλογές.'],['Ανανέωση κάθε εβδομάδα','Το διάστημα καλύπτει Δευτέρα έως Κυριακή και η επιλογή σου διατηρείται σε URL που μπορείς να μοιραστείς.']]},
    auth:{email:'Email',password:'Κωδικός πρόσβασης',consent:'Έχω διαβάσει τους Όρους Χρήσης και την ενημέρωση προστασίας δεδομένων της Τουρκίας.',loginEye:'ΚΑΛΩΣ ΗΡΘΕΣ ΞΑΝΑ',joinEye:'ΕΝΤΕΛΩΣ ΔΩΡΕΑΝ',loginTitle:'Συνδέσου στον λογαριασμό σου.',joinTitle:'Ξεκλείδωσε όλες τις αναγνώσεις.',login:'Σύνδεση',join:'Δημιουργία δωρεάν λογαριασμού'},
    common:{gate:'ΞΕΚΛΕΙΔΩΝΕΙ ΜΕ ΔΩΡΕΑΝ ΕΓΓΡΑΦΗ',checking:'Έλεγχος κατάστασης λογαριασμού…',join:'Δωρεάν εγγραφή',existing:'Έχω ήδη λογαριασμό'}
  }
};

function cards(locale,items,discover){
  return `<div class="showcase-grid">${items.map(([tag,name,text,path])=>`<a class="showcase-card" href="${localePath(locale,path)}"><small>${tag}</small><h3>${name}</h3><p>${text}</p><span>${discover}</span></a>`).join('')}</div>`;
}
function home(locale){
  const t=copy[locale].home;
  const [today,featured,ancient]=t.sections;
  const todayItems=today[3],featuredItems=featured[3],ancientItems=ancient[3];
  const todayRail=todayItems.slice(1).map(([tag,name,description,path])=>`<a href="${localePath(locale,path)}"><small>${tag}</small><strong>${name}</strong><span>${description}</span></a>`).join('');
  const featuredList=featuredItems.map(([,name,description,path])=>`<a href="${localePath(locale,path)}"><div><strong>${name}</strong><p>${description}</p></div><span aria-hidden="true">→</span></a>`).join('');
  const ancientNotes=ancientItems.slice(1).map(([tag,name,description,path],index)=>`<a href="${localePath(locale,path)}"><b aria-hidden="true">${['☿','☽','♄'][index]}</b><div><strong>${name}</strong><span>${description}</span></div></a>`).join('');
  return `<main class="localized-home" data-server-home>
    <section class="oracle-hero premium-home-hero">
      <div><p class="eyebrow">${t.eyebrow}</p><h1>${t.title}<em>${t.em}</em></h1><p class="lead">${t.lead}</p><div class="actions">${link(locale,'/gunluk-kart',t.daily,'btn btn-primary')}${link(locale,'/bugunun-gokyuzu',t.sky,'btn btn-secondary')}${link(locale,'/astroloji',t.chart,'btn btn-tertiary')}</div></div>
      <aside class="hero-sky-card" data-home-sky aria-busy="true"><div class="sky-skeleton" aria-hidden="true"><div class="sky-skeleton-wheel"></div></div></aside>
    </section>
    <section class="section home-today" aria-labelledby="home-today-title"><div class="home-today-layout"><a class="home-today-primary" href="${localePath(locale,'/gunluk-kart')}"><span class="today-symbol" aria-hidden="true">✦</span><p class="eyebrow">${today[0]}</p><h2 id="home-today-title">${todayItems[2][1]}</h2><p>${todayItems[2][2]}</p><span>${t.discover}</span></a><div class="home-today-rail">${todayRail}</div></div></section>
    <section class="section home-featured"><div class="featured-layout"><div class="featured-intro"><p class="eyebrow">${featured[0]}</p><h2>${featured[1]}</h2><p>${featured[2]}</p></div><nav class="featured-list" aria-label="${featured[0]}">${featuredList}</nav></div></section>
    <section class="section home-ancient"><div class="ancient-editorial"><div class="ancient-editorial-main"><span class="ancient-glyph" aria-hidden="true">☉</span><p class="eyebrow">${ancient[0]}</p><h2>${ancient[1]}</h2><p>${ancient[2]}</p><a class="btn btn-ghost" href="${localePath(locale,ancientItems[0][3])}">${ancientItems[0][1]} →</a></div><div class="ancient-notes">${ancientNotes}</div></div></section>
    <section class="section home-membership"><div><p class="eyebrow">${t.memberEye}</p><h2>${t.memberTitle}</h2><p>${t.memberCopy}</p></div><div class="actions">${link(locale,'/kayit',t.join,'btn btn-primary')}${link(locale,'/giris',t.login)}</div></section>
  </main>`;
}
function daily(locale){
  const t=copy[locale].daily;
  return `<main><section class="section"><div class="daily-stage"><p class="eyebrow">${t.eye}</p><h1>${t.title}</h1><p class="lead">${t.lead}</p><button class="tarot-deck" type="button" data-daily-deck aria-expanded="false" aria-label="${t.aria}"><span class="tarot-card"></span></button><div class="reading-result" data-reading-result aria-live="polite"><p class="eyebrow">${t.result}</p><h3 data-card-name></h3><div data-card-text></div><div class="actions">${link(locale,'/kayit',t.more,'btn btn-primary')}</div></div></div></section></main>`;
}
const readingData={
  tarot:{tr:['3 Kart Tarot','Geçmiş, şimdi ve yakın geleceğin enerjisini üç kartla yorumla.'],en:['3-Card Tarot','Explore the energy of the past, present and near future through three cards.'],el:['Ταρώ 3 Καρτών','Εξερεύνησε την ενέργεια του παρελθόντος, του παρόντος και του κοντινού μέλλοντος με τρεις κάρτες.']},
  ask:{tr:['Aşk & Geri Dönüş','İlişkinin mevcut enerjisi, iletişim ihtimali ve olası yönü için açılımını başlat.'],en:['Love & Reconnection','Explore the current relationship energy, the potential for communication and a possible direction.'],el:['Αγάπη & Επανασύνδεση','Εξερεύνησε την παρούσα ενέργεια της σχέσης, την πιθανότητα επικοινωνίας και μία πιθανή κατεύθυνση.']},
  kariyer:{tr:['Kariyer & Para','Fırsatlarını, önündeki engeli ve atman gereken ilk adımı gör.'],en:['Career & Money','Explore your opportunities, the obstacle ahead and a grounded first step.'],el:['Καριέρα & Χρήματα','Εξερεύνησε τις ευκαιρίες, το εμπόδιο μπροστά σου και ένα πρακτικό πρώτο βήμα.']},
  'otuz-gun':{tr:['30 Gün Açılımı','Önündeki dört haftanın ana temalarını ve kritik günlerini keşfet.'],en:['30-Day Reading','Explore the central themes and significant moments of the next four weeks.'],el:['Άνοιγμα 30 Ημερών','Εξερεύνησε τα βασικά θέματα και τις σημαντικές στιγμές των επόμενων τεσσάρων εβδομάδων.']},
  katina:{tr:['Katina Aşk Falı','Duygusal bağları ve ilişkinin dinamiklerini Katina kartlarıyla yorumla.'],en:['Katina Love Reading','Explore emotional bonds and relationship dynamics through Katina cards.'],el:['Ερωτική Ανάγνωση Κατίνα','Εξερεύνησε τους συναισθηματικούς δεσμούς και τη δυναμική της σχέσης μέσα από τις κάρτες Κατίνα.']}
};
function prompt(locale,type){
  if(type==='ask'||type==='katina'){
    const x=locale==='tr'?['İlişki durumun','Belirsiz','Ayrıyız','İletişim var','Birlikteyiz','Odaklandığın soru','Bu bağın yönü ne?']:locale==='en'?['Relationship status','Unclear','Separated','In contact','Together','Your focus question','What direction is this bond taking?']:['Κατάσταση σχέσης','Ασαφής','Σε χωρισμό','Υπάρχει επικοινωνία','Μαζί','Ερώτημα εστίασης','Ποια κατεύθυνση παίρνει αυτός ο δεσμός;'];
    return `<div class="reading-inputs" data-reading-inputs><label>${x[0]}<select name="relationship"><option value="unclear">${x[1]}</option><option value="separated">${x[2]}</option><option value="contact">${x[3]}</option><option value="together">${x[4]}</option></select></label><label>${x[5]}<input type="text" name="question" maxlength="120" placeholder="${x[6]}"></label></div>`;
  }
  if(type==='kariyer'){
    const x=locale==='tr'?['Odak alanın','İş değişikliği','Para','Yeni girişim','Karar aşaması']:locale==='en'?['Area of focus','Career change','Money','New venture','Decision point']:['Πεδίο εστίασης','Αλλαγή εργασίας','Χρήματα','Νέο εγχείρημα','Σημείο απόφασης'];
    return `<div class="reading-inputs" data-reading-inputs><label>${x[0]}<select name="focus"><option value="career">${x[1]}</option><option value="money">${x[2]}</option><option value="venture">${x[3]}</option><option value="decision">${x[4]}</option></select></label></div>`;
  }
  return '';
}
function gated(locale,type){
  const [title,lead]=readingData[type][locale],t=copy[locale].common;
  return `<main><section class="section"><div class="membership-gate" data-member-reading="${type}"><p class="eyebrow">${t.gate}</p><h1>${title}</h1><p class="lead">${lead}</p><p class="form-message" data-reading-message aria-live="polite">${t.checking}</p><div class="actions" data-guest-actions>${link(locale,`/kayit?devam=/${type}`,t.join,'btn btn-primary')}${link(locale,`/giris?devam=/${type}`,t.existing)}</div><div class="reading-workspace" data-reading-workspace hidden>${prompt(locale,type)}<button class="tarot-deck" type="button" data-member-deck aria-expanded="false" aria-label="${title}"><span class="tarot-card"></span></button><div class="reading-result" data-member-result aria-live="polite"></div></div></div></section></main>`;
}
function weekly(locale){
  const t=copy[locale].weekly;
  return `<main><section class="section weekly-hero"><p class="eyebrow">${t.eye}</p><h1>${t.title}</h1><p class="lead left-lead">${t.lead}</p><div class="weekly-meta"><strong data-weekly-range></strong><span>${t.updated}: <time data-weekly-updated></time></span></div><div class="zodiac-grid" data-weekly-zodiac></div><div class="weekly-result" data-weekly-result hidden aria-live="polite"></div></section><section class="section weekly-method"><p class="eyebrow">MYTHBORN</p><h2>${t.about}</h2><div class="weekly-method-grid">${t.aboutCards.map(([h,p])=>`<article><h3>${h}</h3><p>${p}</p></article>`).join('')}</div></section></main>`;
}
function astrology(locale){
  const t={
    tr:{eye:'MYTHBORN ASTROLOJİ',title:'Doğduğun anın gökyüzü haritasını keşfet.',lead:'Güneş, Ay, Yükselen, gezegen yerleşimleri, 12 ev ve temel açıları gerçek astronomik verilerle tek merkezde yorumla.',gate:'ÜCRETSİZ DOĞUM HARİTASI',formTitle:'Doğum bilgilerini gir.',formLead:'Doğum saati yükselen burç ve evler için önemlidir. Bilmiyorsan yalnızca güvenilir tarih temelli katmanlar gösterilir.',date:'Doğum tarihi',time:'Doğum saati',place:'Doğum yeri',placeholder:'İstanbul, Türkiye',unknown:'Doğum saatimi bilmiyorum',submit:'Doğum haritamı yorumla',centre:'ASTROLOJİ MERKEZİ',featuresTitle:'Tek burç yorumu değil, bütünsel profil.',features:[['☉','Güneş Burcu','Kimlik, yaşam enerjisi ve temel motivasyon.'],['☽','Ay Burcu','Duygusal ihtiyaçlar, güven ve iç dünya.'],['ASC','Yükselen','Dış dünyaya yaklaşım ve haritanın başlangıç noktası.'],['12','Evler','Aşk, para, aile, kariyer, sağlık ve dönüşüm alanları.'],['✦','Gezegenler','Merkür’den Plüton’a karakter ve yaşam temaları.'],['△','Açılar','Gezegenlerin destek ve gerilim ilişkileri.']]},
    en:{eye:'MYTHBORN ASTROLOGY',title:'Explore the sky at the moment you were born.',lead:'Interpret your Sun, Moon, Rising sign, planetary placements, 12 houses and major aspects in one place using real astronomical data.',gate:'FREE BIRTH CHART',formTitle:'Enter your birth details.',formLead:'Birth time is important for the Rising sign and houses. If it is unknown, only reliable date-based layers will be shown.',date:'Date of birth',time:'Time of birth',place:'Place of birth',placeholder:'London, United Kingdom',unknown:'I do not know my birth time',submit:'Calculate my birth chart',centre:'ASTROLOGY CENTRE',featuresTitle:'A complete profile, not a single-sign reading.',features:[['☉','Sun Sign','Identity, vitality and central motivation.'],['☽','Moon Sign','Emotional needs, security and inner life.'],['ASC','Rising Sign','Your approach to the world and the chart’s starting point.'],['12','Houses','Life areas including love, money, home, work and transformation.'],['✦','Planets','Character and life themes from Mercury to Pluto.'],['△','Aspects','Supportive and challenging relationships between planets.']]},
    el:{eye:'MYTHBORN ΑΣΤΡΟΛΟΓΙΑ',title:'Εξερεύνησε τον ουρανό τη στιγμή που γεννήθηκες.',lead:'Ερμήνευσε Ήλιο, Σελήνη, Ωροσκόπο, πλανητικές θέσεις, 12 οίκους και κύριες όψεις με πραγματικά αστρονομικά δεδομένα.',gate:'ΔΩΡΕΑΝ ΓΕΝΕΘΛΙΟΣ ΧΑΡΤΗΣ',formTitle:'Συμπλήρωσε τα στοιχεία γέννησης.',formLead:'Η ώρα γέννησης είναι σημαντική για τον Ωροσκόπο και τους οίκους. Αν δεν είναι γνωστή, εμφανίζονται μόνο αξιόπιστα στοιχεία βάσει ημερομηνίας.',date:'Ημερομηνία γέννησης',time:'Ώρα γέννησης',place:'Τόπος γέννησης',placeholder:'Αθήνα, Ελλάδα',unknown:'Δεν γνωρίζω την ώρα γέννησης',submit:'Υπολογισμός γενέθλιου χάρτη',centre:'ΚΕΝΤΡΟ ΑΣΤΡΟΛΟΓΙΑΣ',featuresTitle:'Ολοκληρωμένο προφίλ, όχι μόνο ένα ζώδιο.',features:[['☉','Ζώδιο Ήλιου','Ταυτότητα, ζωτικότητα και βασικό κίνητρο.'],['☽','Ζώδιο Σελήνης','Συναισθηματικές ανάγκες, ασφάλεια και εσωτερικός κόσμος.'],['ASC','Ωροσκόπος','Η προσέγγιση προς τον κόσμο και η αρχή του χάρτη.'],['12','Οίκοι','Τομείς ζωής όπως αγάπη, χρήματα, σπίτι, εργασία και μεταμόρφωση.'],['✦','Πλανήτες','Χαρακτήρας και θέματα ζωής από τον Ερμή έως τον Πλούτωνα.'],['△','Όψεις','Υποστηρικτικές και απαιτητικές σχέσεις ανάμεσα στους πλανήτες.']]}
  }[locale],c=copy[locale].common;
  return `<main class="astrology-page"><section class="section astrology-hero"><p class="eyebrow">${t.eye}</p><h1>${t.title}</h1><p class="lead left-lead">${t.lead}</p><div class="astro-pill-row">${t.features.map(([,name])=>`<span>${name}</span>`).join('')}</div></section><section class="section"><div class="membership-gate" data-member-reading="astroloji"><p class="eyebrow">${t.gate}</p><h2>${t.formTitle}</h2><p class="lead">${t.formLead}</p><p class="form-message" data-reading-message aria-live="polite">${c.checking}</p><div class="actions" data-guest-actions>${link(locale,'/kayit?devam=/astroloji',c.join,'btn btn-primary')}${link(locale,'/giris?devam=/astroloji',c.existing)}</div><div class="reading-workspace" data-reading-workspace hidden><div class="reading-inputs astro-inputs" data-reading-inputs><label>${t.date}<input type="date" name="birthDate" required></label><label>${t.time}<input type="time" name="birthTime"></label><label>${t.place}<input type="text" name="birthPlace" maxlength="100" placeholder="${t.placeholder}"></label><label class="time-unknown"><input type="checkbox" name="timeUnknown" value="yes"> ${t.unknown}</label></div><button class="btn btn-primary astro-submit" type="button" data-member-deck aria-expanded="false">${t.submit}</button><div class="reading-result" data-member-result aria-live="polite"></div></div></div></section><section class="section"><p class="eyebrow">${t.centre}</p><h2>${t.featuresTitle}</h2><div class="astro-feature-grid">${t.features.map(([symbol,name,description])=>`<article><strong>${symbol}</strong><h3>${name}</h3><p>${description}</p></article>`).join('')}</div></section></main>`;
}
function auth(locale,mode){
  const t=copy[locale].auth,isLogin=mode==='giris';
  const extra=locale==='tr'
    ?{promise:'Kişisel alanın, kayıtlı açılımların ve haritan tek güvenli hesapta.',forgot:'Şifremi unuttum',reset:'Yenileme bağlantısı gönder',sent:'E-posta kayıtlıysa yenileme bağlantısı gönderildi.',switch:isLogin?'Hesabın yok mu? Ücretsiz katıl':'Zaten hesabın var mı? Giriş yap'}
    :locale==='en'
      ?{promise:'Your personal space, saved readings and chart in one secure account.',forgot:'Forgot password?',reset:'Send reset link',sent:'If the address is registered, a reset link has been sent.',switch:isLogin?'New to Mythborn? Join free':'Already have an account? Sign in'}
      :{promise:'Ο προσωπικός σου χώρος, οι αποθηκευμένες αναγνώσεις και ο χάρτης σου σε έναν ασφαλή λογαριασμό.',forgot:'Ξέχασες τον κωδικό;',reset:'Αποστολή συνδέσμου επαναφοράς',sent:'Αν η διεύθυνση είναι καταχωρισμένη, στάλθηκε σύνδεσμος επαναφοράς.',switch:isLogin?'Νέος στο Mythborn; Δωρεάν εγγραφή':'Έχεις ήδη λογαριασμό; Σύνδεση'};
  const passwordToggle=locale==='tr'?'Şifreyi göster':locale==='en'?'Show password':'Εμφάνιση κωδικού';
  return `<main class="auth-page"><section class="section auth-section"><div class="auth-layout"><aside class="auth-intro"><p class="eyebrow">MYTHBORN</p><h1>${isLogin?t.loginTitle:t.joinTitle}</h1><p>${extra.promise}</p><span aria-hidden="true">☾</span></aside><div class="membership-gate auth-gate"><p class="eyebrow">${isLogin?t.loginEye:t.joinEye}</p><form class="auth-form" data-auth-form="${mode}"><label>${t.email}<input required name="email" type="email" autocomplete="email"></label><label>${t.password}<span class="password-field"><input required name="password" type="password" minlength="10" autocomplete="${isLogin?'current-password':'new-password'}"><button class="password-toggle" type="button" aria-label="${passwordToggle}" aria-pressed="false" data-password-toggle>◉</button></span></label>${isLogin?'':`<label class="consent"><input required type="checkbox"> ${t.consent}</label>`}<p class="form-message" data-form-message aria-live="polite"></p><button class="btn btn-primary" type="submit">${isLogin?t.login:t.join}</button></form>${isLogin?`<details class="password-reset"><summary>${extra.forgot}</summary><form data-password-reset><label>${t.email}<input required name="email" type="email" autocomplete="email"></label><button class="btn btn-ghost" type="submit">${extra.reset}</button><p aria-live="polite" data-reset-message data-success="${extra.sent}"></p></form></details>`:''}<a class="auth-switch" href="${localePath(locale,isLogin?'/kayit':'/giris')}">${extra.switch}</a></div></div></section></main>`;
}
function account(locale){
  const t={
    tr:{eye:'ÜYE ALANI',title:'Hesabım',profile:'PROFİL',checking:'Kontrol ediliyor…',status:'Ücretsiz üyelik',chart:'Doğum haritam',logout:'Çıkış yap',history:'GEÇMİŞ',empty:'Kaydedilmiş açılımların burada görünecek.'},
    en:{eye:'MEMBER AREA',title:'My Account',profile:'PROFILE',checking:'Checking…',status:'Free membership',chart:'My birth chart',logout:'Sign out',history:'HISTORY',empty:'Your saved readings will appear here.'},
    el:{eye:'ΧΩΡΟΣ ΜΕΛΩΝ',title:'Ο Λογαριασμός μου',profile:'ΠΡΟΦΙΛ',checking:'Έλεγχος…',status:'Δωρεάν εγγραφή',chart:'Ο γενέθλιος χάρτης μου',logout:'Αποσύνδεση',history:'ΙΣΤΟΡΙΚΟ',empty:'Οι αποθηκευμένες αναγνώσεις σου θα εμφανίζονται εδώ.'}
  }[locale];
  return `<main><section class="section" data-account><p class="eyebrow">${t.eye}</p><h2>${t.title}</h2><div class="grid account-grid"><article class="card"><small>${t.profile}</small><h3 data-account-email>${t.checking}</h3><p data-account-status>${t.status}</p><div class="actions">${link(locale,'/astroloji',t.chart,'btn btn-primary')}<button class="btn btn-ghost" type="button" data-logout>${t.logout}</button></div></article><article class="card"><small>${t.history}</small><div data-result-history><p>${t.empty}</p></div></article></div></section></main>`;
}

export function corePage(locale,path){
  if(path==='/')return home(locale);
  if(path==='/gunluk-kart')return daily(locale);
  if(path==='/haftalik-burc')return weekly(locale);
  if(path==='/astroloji')return astrology(locale);
  if(path==='/giris'||path==='/kayit')return auth(locale,path.slice(1));
  if(path==='/hesabim')return account(locale);
  if(readingData[path.slice(1)])return gated(locale,path.slice(1));
  return null;
}
export function coreMeta(locale,path){
  const known=copy[locale].meta[path];
  if(known)return {title:known[0],description:known[1]};
  if(readingData[path.slice(1)]){
    const [title,description]=readingData[path.slice(1)][locale];
    return {title:`${title} — Mythborn`,description};
  }
  const utility={
    tr:{'/giris':['Giriş — Mythborn','Mythborn hesabına güvenli biçimde giriş yap.'],'/kayit':['Ücretsiz Kayıt — Mythborn','Ücretsiz Mythborn hesabını oluştur.'],'/hesabim':['Hesabım — Mythborn','Kişisel Mythborn hesabını ve kayıtlı açılımlarını yönet.']},
    en:{'/giris':['Sign In — Mythborn','Sign in securely to your Mythborn account.'],'/kayit':['Join Free — Mythborn','Create your free Mythborn account.'],'/hesabim':['My Account — Mythborn','Manage your Mythborn account and saved readings.']},
    el:{'/giris':['Σύνδεση — Mythborn','Συνδέσου με ασφάλεια στον λογαριασμό Mythborn.'],'/kayit':['Δωρεάν Εγγραφή — Mythborn','Δημιούργησε δωρεάν λογαριασμό Mythborn.'],'/hesabim':['Ο Λογαριασμός μου — Mythborn','Διαχειρίσου τον λογαριασμό και τις αποθηκευμένες αναγνώσεις σου.']}
  }[locale][path];
  if(utility)return {title:utility[0],description:utility[1]};
  return null;
}
export {copy,localePath};
