const prefix=locale=>locale==='en'?'/en':locale==='el'?'/gr':'';
const path=(locale,value)=>`${prefix(locale)}${value}`;
const esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const locales={
  tr:{
    sky:['GERÇEK ZAMANLI ASTROLOJİ','Bugünün Gökyüzü','Güneş, Ay ve gezegenlerin güncel burç konumlarını ve günün belirgin majör açılarını gör.','Güncel gezegen konumları hesaplanıyor…'],
    synastry:['İKİ GERÇEK DOĞUM HARİTASI','Sinastri — İlişki Haritası','İki kişinin gezegen konumlarını gerçek açılar üzerinden duygu, iletişim, çekim ve bağlılık temalarıyla karşılaştır.'],
    moon:['AYIN DÖNGÜSÜ','Ay Takvimi','Bugünkü yaklaşık Ay fazını, aydınlanmayı ve mevcut döngünün temasını gör.','Ay verisi hazırlanıyor…'],
    dream:['RÜYANIN SEMBOLİK HARİTASI','Rüya Yorumları','Rüyayı duygu tonu, kişiler, mekân, tekrar eden örüntü ve uyanık yaşam bağlamıyla birlikte incele.'],
    numerology:['İSİM VE DOĞUM TARİHİ','Numeroloji','Doğum tarihinden yaşam yolu sayını, adından ifade sayını hesapla.'],
    compatibility:['İLİŞKİ DİNAMİĞİ','Burç Uyumu','İki burcun element ve niteliklerini sembolik ilişki dinamikleri olarak karşılaştır.'],
    ancient:['TARİH, KÜLTÜR VE SEMBOL','Kadim Gökyüzü Gelenekleri','Maya zaman döngülerini, Mezopotamya gökyüzü kayıtlarını ve doğa merkezli farkındalığı farklı kültürleri tek sisteme indirgemeden keşfet.'],
    form:{date:'Doğum tarihi',time:'Doğum saati',place:'Doğum yeri',unknown:'Doğum saati bilinmiyor',first:'Birinci kişi',second:'İkinci kişi',calculate:'Sinastriyi hesapla',name:'Ad soyad',numbers:'Sayılarımı hesapla',dream:'Rüyanı ayrıntılı anlat',emotion:'Uyandığında baskın duygu',context:'Son dönemde seni meşgul eden konu',interpret:'Rüyamı incele',yourSign:'Senin burcun',otherSign:'Diğer kişinin burcu',compare:'Uyumu keşfet'}
  },
  en:{
    sky:['REAL-TIME ASTROLOGY','Today’s Sky','See the current zodiac positions of the Sun, Moon and planets, together with the day’s strongest major aspects.','Calculating current planetary positions…'],
    synastry:['TWO REAL BIRTH CHARTS','Synastry — Relationship Chart','Compare two people’s planetary positions through real aspects for emotion, communication, attraction and commitment.'],
    moon:['THE LUNAR CYCLE','Moon Calendar','See today’s approximate Moon phase, illumination and the theme of the current cycle.','Preparing lunar data…'],
    dream:['A SYMBOLIC MAP OF THE DREAM','Dream Interpretation','Explore the dream through its emotional tone, people, place, recurring pattern and current waking-life context.'],
    numerology:['NAME AND DATE OF BIRTH','Numerology','Calculate a life-path number from your birth date and an expression number from your name.'],
    compatibility:['RELATIONSHIP DYNAMICS','Zodiac Compatibility','Compare the elements and modalities of two signs as symbolic relationship dynamics.'],
    ancient:['HISTORY, CULTURE AND SYMBOL','Ancient Sky Traditions','Explore Maya time cycles, Mesopotamian sky traditions and nature-centred reflection without collapsing distinct cultures into one modern system.'],
    form:{date:'Date of birth',time:'Time of birth',place:'Place of birth',unknown:'Birth time unknown',first:'First person',second:'Second person',calculate:'Calculate synastry',name:'Full name',numbers:'Calculate my numbers',dream:'Describe your dream in detail',emotion:'Dominant feeling on waking',context:'What has occupied you recently?',interpret:'Explore my dream',yourSign:'Your sign',otherSign:'Other person’s sign',compare:'Explore compatibility'}
  },
  el:{
    sky:['ΑΣΤΡΟΛΟΓΙΑ ΣΕ ΠΡΑΓΜΑΤΙΚΟ ΧΡΟΝΟ','Ο Σημερινός Ουρανός','Δες τις τρέχουσες ζωδιακές θέσεις Ήλιου, Σελήνης και πλανητών μαζί με τις ισχυρότερες κύριες όψεις της ημέρας.','Υπολογίζονται οι τρέχουσες πλανητικές θέσεις…'],
    synastry:['ΔΥΟ ΠΡΑΓΜΑΤΙΚΟΙ ΓΕΝΕΘΛΙΟΙ ΧΑΡΤΕΣ','Συναστρία — Χάρτης Σχέσης','Σύγκρινε τις πλανητικές θέσεις δύο ανθρώπων μέσα από πραγματικές όψεις για συναίσθημα, επικοινωνία, έλξη και δέσμευση.'],
    moon:['Ο ΣΕΛΗΝΙΑΚΟΣ ΚΥΚΛΟΣ','Σεληνιακό Ημερολόγιο','Δες τη σημερινή κατά προσέγγιση φάση της Σελήνης, τον φωτισμό και το θέμα του κύκλου.','Προετοιμάζονται τα σεληνιακά δεδομένα…'],
    dream:['ΣΥΜΒΟΛΙΚΟΣ ΧΑΡΤΗΣ ΤΟΥ ΟΝΕΙΡΟΥ','Ερμηνεία Ονείρων','Εξερεύνησε το όνειρο μέσα από το συναίσθημα, τα πρόσωπα, τον τόπο, την επανάληψη και το πλαίσιο της καθημερινής ζωής.'],
    numerology:['ΟΝΟΜΑ ΚΑΙ ΗΜΕΡΟΜΗΝΙΑ ΓΕΝΝΗΣΗΣ','Αριθμολογία','Υπολόγισε τον αριθμό διαδρομής ζωής από την ημερομηνία γέννησης και τον αριθμό έκφρασης από το όνομα.'],
    compatibility:['ΔΥΝΑΜΙΚΗ ΣΧΕΣΗΣ','Συμβατότητα Ζωδίων','Σύγκρινε τα στοιχεία και τις ποιότητες δύο ζωδίων ως συμβολικές δυναμικές σχέσης.'],
    ancient:['ΙΣΤΟΡΙΑ, ΠΟΛΙΤΙΣΜΟΣ ΚΑΙ ΣΥΜΒΟΛΟ','Αρχαίες Ουράνιες Παραδόσεις','Εξερεύνησε τους κύκλους χρόνου των Μάγια, τις μεσοποταμιακές ουράνιες παραδόσεις και τον στοχασμό στη φύση, χωρίς συγχώνευση διαφορετικών πολιτισμών.'],
    form:{date:'Ημερομηνία γέννησης',time:'Ώρα γέννησης',place:'Τόπος γέννησης',unknown:'Άγνωστη ώρα γέννησης',first:'Πρώτο άτομο',second:'Δεύτερο άτομο',calculate:'Υπολογισμός συναστρίας',name:'Ονοματεπώνυμο',numbers:'Υπολογισμός αριθμών',dream:'Περιέγραψε το όνειρο αναλυτικά',emotion:'Κυρίαρχο συναίσθημα στο ξύπνημα',context:'Τι σε απασχολεί τελευταία;',interpret:'Εξερεύνηση ονείρου',yourSign:'Το ζώδιό σου',otherSign:'Το άλλο ζώδιο',compare:'Εξερεύνηση συμβατότητας'}
  }
};
const wrap=(content,body)=>`<main><section class="section discovery-hero"><p class="eyebrow">${content[0]}</p><h1>${content[1]}</h1><p class="lead left-lead">${content[2]}</p>${body}</section></main>`;
const person=(f,p,name,title)=>`<fieldset><legend>${title}</legend><div class="synastry-fields"><label>${f.date}<input required type="date" name="${name}BirthDate"></label><label>${f.time}<input type="time" name="${name}BirthTime"></label><label>${f.place}<input required name="${name}BirthPlace" maxlength="100" placeholder="${p}"></label><label class="check-label"><input type="checkbox" name="${name}TimeUnknown"> ${f.unknown}</label></div></fieldset>`;
const ancientCards={
  tr:[['MAYA','Maya Zaman Döngüleri','Tzolk’in, Haab, Takvim Turu ve Uzun Sayımın tarihsel işlevlerini öğren.','/maya-zaman-donguleri'],['MEZOPOTAMYA','Sümer, Babil ve Asur','Göksel alametlerden yıldız listelerine, matematiksel zodyaktan kişisel horoskoplara uzanan gelişimi incele.','/mezopotamya-astrolojisi'],['DOĞA RİTİMLERİ','Doğa ve Gökyüzü','Mevsim, yön, Ay ve yerel döngüleri tek bir evrensel gelenek iddiası kurmadan gözlemle.','/doga-gokyuzu-donguleri'],['GÜVENLİ FARKINDALIK','Travma-Bilinçli Astroloji','Tanı ve kader dili yerine seçim, sınır ve güvenliği önceleyen öz-refleksiyon.','/travma-bilincli-astroloji']],
  en:[['MAYA','Maya Time Cycles','Tzolk’in, Haab, the Calendar Round and Long Count in historical context.','/maya-zaman-donguleri'],['MESOPOTAMIA','Sumer, Babylon and Assyria','From celestial omen records to the mathematical zodiac and personal horoscopes.','/mezopotamya-astrolojisi'],['NATURAL RHYTHMS','Nature and Sky','Seasons, directions, the Moon and local cycles without claiming one universal tradition.','/doga-gokyuzu-donguleri'],['SAFE REFLECTION','Trauma-Informed Astrology','Choice, boundaries and safety instead of diagnosis or deterministic claims.','/travma-bilincli-astroloji']],
  el:[['ΜΑΓΙΑ','Κύκλοι Χρόνου των Μάγια','Tzolk’in, Haab, Ημερολογιακός Γύρος και Μακρά Αρίθμηση στο ιστορικό τους πλαίσιο.','/maya-zaman-donguleri'],['ΜΕΣΟΠΟΤΑΜΙΑ','Σουμέριοι, Βαβυλώνιοι και Ασσύριοι','Από τα αρχεία ουράνιων οιωνών στον μαθηματικό ζωδιακό και τα προσωπικά ωροσκόπια.','/mezopotamya-astrolojisi'],['ΦΥΣΙΚΟΙ ΡΥΘΜΟΙ','Φύση και Ουρανός','Εποχές, κατευθύνσεις, Σελήνη και τοπικοί κύκλοι χωρίς ισχυρισμό μίας καθολικής παράδοσης.','/doga-gokyuzu-donguleri'],['ΑΣΦΑΛΗΣ ΣΤΟΧΑΣΜΟΣ','Αστρολογία με Επίγνωση Τραύματος','Επιλογή, όρια και ασφάλεια αντί για διάγνωση ή ντετερμινιστικούς ισχυρισμούς.','/travma-bilincli-astroloji']]
};
const ancientDepth={
  tr:[['Maya zaman çerçeveleri','Tzolk’in, Haab, Takvim Turu ve Uzun Sayım farklı ritüel, toplumsal ve tarihsel işlevler taşır. Bunları Batı tipi kişilik burcuna indirgemek tarihsel ayrımları siler.'],['Mezopotamya kayıtları','Sümer, Babil ve Asur malzemeleri farklı dönemlere aittir. Alamet dizileri, yıldız listeleri ve daha geç horoskoplar tek ve değişmez bir sistem değil, uzun bir gelişim gösterir.'],['Ay, mevsim ve yer','Ay gözlemi ve mevsim ritimleri gerçek iklim, tarım ve toplumsal pratik içinde anlam kazanır; sembol tarihsel bağlamından koparılmamalıdır.'],['Ortak gökyüzü, farklı kültürler','Güneş, Ay ve görünür gezegenleri gözlemek kültürlerin aynı anlam, ritüel veya kozmolojiye sahip olduğu anlamına gelmez.'],['Etik modern farkındalık','Tarihsel gökyüzü geleneklerini yaşayan kültürleri sahiplenmek, tanı koymak veya kesin sonuç vaat etmek için değil, daha dikkatli sorular sormak için kullan.']],
  en:[['Maya time frameworks','Tzolk’in, Haab, the Calendar Round and the Long Count served different ritual, civic and historical functions. They should not be collapsed into a Western-style personality zodiac.'],['Mesopotamian records','Sumerian, Babylonian and Assyrian materials belong to different periods. Omen series, star catalogues and later mathematical horoscopes document a long development rather than one fixed system.'],['Moon, season and place','Lunar observation and seasonal rhythms gain meaning through real local climate, agriculture and social practice; symbols should remain connected to their historical setting.'],['Shared sky, distinct cultures','Cultures may all observe the Sun, Moon and visible planets, but similar objects do not imply identical meanings, rituals or cosmologies.'],['Ethical modern reflection','Use historical sky traditions to ask better questions, never to claim ownership of living traditions, diagnose a person or promise fixed outcomes.']],
  el:[['Χρονικά πλαίσια των Μάγια','Τα Tzolk’in, Haab, Ημερολογιακός Γύρος και Μακρά Αρίθμηση είχαν διαφορετικές τελετουργικές, πολιτικές και ιστορικές λειτουργίες· δεν αποτελούν δυτικό ζωδιακό προσωπικότητας.'],['Μεσοποταμιακές καταγραφές','Σουμεριακά, βαβυλωνιακά και ασσυριακά τεκμήρια ανήκουν σε διαφορετικές περιόδους. Οι σειρές οιωνών, οι κατάλογοι άστρων και τα μεταγενέστερα ωροσκόπια δείχνουν μακρά εξέλιξη.'],['Σελήνη, εποχή και τόπος','Η παρατήρηση της Σελήνης και των εποχών αποκτά νόημα μέσα από το πραγματικό τοπικό κλίμα, τη γεωργία και την κοινωνική πρακτική.'],['Κοινός ουρανός, διαφορετικοί πολιτισμοί','Η παρατήρηση Ήλιου, Σελήνης και πλανητών δεν σημαίνει ταυτόσημες έννοιες, τελετές ή κοσμολογίες.'],['Ηθικός σύγχρονος στοχασμός','Οι ιστορικές παραδόσεις βοηθούν να θέτουμε καλύτερα ερωτήματα, όχι να οικειοποιούμαστε ζωντανές παραδόσεις ή να υποσχόμαστε βέβαια αποτελέσματα.']]
};
const ancientGuides={
  tr:{
    '/maya-zaman-donguleri':{tag:'TZOLK’IN · HAAB · UZUN SAYIM',title:'Maya Zaman Döngüleri',description:'Tzolk’in, Haab, Takvim Turu ve Uzun Sayımın tarihsel işlevlerini öğren; Maya takvimlerini modern “burç” listelerinden ayır.',cards:[['260 GÜN','Tzolk’in','20 gün adı ile 1’den 13’e kadar sayıların birleşiminden oluşan 260 günlük kutsal döngüdür. Gün adları ve sayılar birlikte bir tarih verir.'],['365 GÜN','Haab','18 adet 20 günlük ay ile beş günlük Wayeb bölümünden oluşur; güneş yılına yaklaşık bir uzunluk sunar.'],['52 YIL','Takvim Turu','Tzolk’in ve Haab tarihlerinin aynı birleşimi yaklaşık 52 Haab yılı geçmeden yeniden oluşmaz.'],['TARİH','Uzun Sayım','52 yıllık döngünün ötesindeki tarihsel ve mitik olayları doğrusal olarak kaydetmek için kullanılan daha uzun sayım sistemidir.']],sections:[['Bir “Maya burcu” değildir','Maya takvimleri doğum tarihini tek bir kişilik etiketine indiren Batı tipi burç sistemiyle aynı şey değildir. Bir tarihi okumak; hangi takvimden söz edildiğini, kullanılan dil ve topluluk bağlamını ve tarihsel kaynağı açık tutmayı gerektirir.'],['Bir tarih nasıl okunur?','Bir tarih Tzolk’in günü ile Haab gününü birlikte taşıyabilir; daha uzun olaylar için Long Count eklenir. Örneğin bir dönüştürücü yalnızca “karakter” üretmek yerine hangi takvim katmanını hesapladığını ve kullandığı korelasyon varsayımını açıklamalıdır.'],['2012 anlatısını doğru kurmak','13.0.0.0.0 tarihinin 21 Aralık 2012’ye denk gelmesi bir takvim döngüsünün dönüm noktasıdır; dünyanın sonu iddiası değildir. Tarihi sansasyon yerine kayıt, döngü ve günümüz Maya topluluklarının devam eden pratikleriyle birlikte okumak gerekir.'],['Bugün yaşayan bağlam','Maya takvimleri yalnızca arkeolojik bir merak değildir. Smithsonian’ın kaynaklarında gün tutucuların ve toplulukların takvim döngülerini günümüzde de yaşattığı anlatılır. Bu nedenle sayfa, yaşayan gelenekleri “eski bir kehanet sistemi” gibi paketlemez.']],faq:[['Maya takvimleri astroloji midir?','Bazı tarihsel kullanımlar gökyüzü gözlemi ve ritüelle ilişkilidir; fakat Tzolk’in, Haab ve Long Count tek bir modern kişilik astrolojisi değildir.'],['Maya burcumu nasıl hesaplarım?','Bir tarih dönüştürülebilir; ancak sonuç seçilen korelasyon, dil ve takvim geleneğine göre açıklanmalıdır. Mythborn bu nedenle kişilik teşhisi yerine tarihsel zaman bilgisini öne çıkarır.'],['Haab neden 365 gündür?','Haab, 18 adet 20 günlük dönem ve Wayeb adı verilen beş günlük bölümden oluşur: 18×20+5=365.']],sources:[['Smithsonian National Museum of the American Indian — The Calendar System','https://maya.nmai.si.edu/calendar/calendar-system']],related:[['Kadim Gökyüzü Merkezi','/kadim-gokyuzu'],['Mezopotamya Astrolojisi','/mezopotamya-astrolojisi']]},
    '/mezopotamya-astrolojisi':{tag:'SÜMER · BABİL · ASUR',title:'Mezopotamya Astrolojisi',description:'Sümer, Babil ve Asur gökyüzü kayıtlarını; alamet serileri, MUL.APIN, zodyak ve kişisel horoskopların tarihsel gelişimiyle incele.',cards:[['ALAMETLER','Enūma Anu Enlil','Ay, Güneş, gezegenler ve hava olaylarını krallık, toplum ve zaman düzeniyle ilişkilendiren geniş alamet geleneğidir.'],['YILDIZ LİSTELERİ','MUL.APIN','Yıldızların ve takımyıldızların görünür hareketleri, mevsimler, aylar ve göksel yönlerle ilgili derlemelerden biridir.'],['ZODYAK','12 eşit bölüm','Babil döneminin daha geç matematiksel uygulamalarında ekliptiğin 12 eşit bölüme ayrılması, sonraki zodyak tarihini etkiledi.'],['HOROSKOP','Kişisel kayıtlar','Geç Babil döneminde doğum anındaki gezegen konumlarını kaydeden kişisel horoskop örnekleri ortaya çıktı.']],sections:[['Tek bir Mezopotamya astrolojisi yoktu','Sümer, Babil ve Asur adları aynı coğrafi-kültürel dünyanın farklı dönemlerini ve arşivlerini anlatır. Alamet metinleri, yıldız listeleri, gözlem günlükleri ve horoskoplar aynı işleve sahip tek bir kitap değildir.'],['Astronomi ve alamet birlikte, ama aynı şey değil','Gökyüzünü düzenli gözlemek, bir yıldızın doğuş zamanını kaydetmek veya gezegen hareketini hesaplamak astronomik bir pratiktir. Bu verilerden kral ya da ülke hakkında işaret çıkarmak ise alamet yorumunun farklı katmanıdır.'],['MUL.APIN’i bir “burç listesi”ne çevirmemek','MUL.APIN, modern internet listelerinde dolaşan “Sümer burçları” gibi 12 kişilik tipinden ibaret değildir. Penn Museum’daki bir Neo-Babil tablet kaydı, MUL.APIN başlığı altında astronomik/aylık listeler ve alamet bağlamı gösterir.'],['Kişisel horoskopların ortaya çıkışı','Geç Babil dönemindeki kişisel horoskoplar, göksel konumların tek bir evrensel kişilik testi olarak değil, belirli tarihsel ve yazı arşivi bağlamlarında kaydedildiğini gösterir.']],faq:[['Sümer burçları gerçek mi?','İnternetteki 12 maddelik “Sümer burcu” listeleri, Mezopotamya kaynaklarının dönem, dil ve işlev çeşitliliğini çoğu zaman düzleştirir; doğrudan tarihsel bir eşdeğer olarak sunulmamalıdır.'],['MUL.APIN ne anlatır?','MUL.APIN, yıldızlar, takımyıldızlar, göksel hareketler, aylar ve gözlem düzeniyle ilgili Babil derlemelerinden biridir; tek başına modern burç yorumu değildir.'],['Mezopotamya astrolojisi ile astronomi aynı mı?','Hayır. Gözlem ve hesaplama astronomik bilgi üretirken alamet ve horoskop yorumları göksel olaylara kültürel anlam yükleyen farklı pratiklerdir.']],sources:[['Penn Museum — Neo-Babylonian MUL.APIN tablet record','https://collections.penn.museum/collections/object/570158'],['British Museum — MUL.APIN tablet record','https://www.britishmuseum.org/collection/object/W_1899-0610-108']],related:[['Kadim Gökyüzü Merkezi','/kadim-gokyuzu'],['Maya Zaman Döngüleri','/maya-zaman-donguleri']]},
    '/doga-gokyuzu-donguleri':{tag:'MEVSİM · YÖN · AY · TOPRAK',title:'Doğa ve Gökyüzü Döngüleri',description:'Mevsim, yön, Ay ve yerel doğa gözlemlerini kültürel genelleme yapmadan, kişisel farkındalık için güvenli bir çerçevede ele al.',cards:[['MEVSİMLER','Döngüsel zaman','Gündönümü, ekinoks ve yerel mevsim geçişlerini yaşam ritmini gözlemlemek için kullan; her coğrafyanın takvimi ve iklimi farklıdır.'],['YÖNLER','Mekân farkındalığı','Yön sembolleri kültürden kültüre değişir. Tek ve evrensel anlamlar yerine bulunduğun yerin tarihini ve deneyimini sor.'],['AY','Gözlem pratiği','Ay fazını uyku, enerji veya kararların tek nedeni gibi değil; düzenli gözlem ve günlük tutma için sakin bir zaman işareti olarak kullan.'],['TOPRAK','Yerel bağlam','Doğa gözlemi yaşadığın coğrafyanın gerçek iklimi, bitkileri, suyu ve mevsim geçişleriyle başlar.']],sections:[['Bu sayfa neyi iddia etmiyor?','Dünyadaki yerli ve halk geleneklerini tek bir “şaman astrolojisi” altında birleştirmiyoruz. Her topluluğun gökyüzü, mevsim, yön ve ritüel ilişkisi kendi tarihsel ve yaşayan bağlamında ele alınmalıdır.'],['Kişisel gözlem için dört adım','Önce bulunduğun yeri ve tarihi yaz. Sonra gökyüzünde gerçekten ne gördüğünü kaydet. Bedensel ve duygusal deneyimini ayrı bir satıra ekle. Son olarak sembolik anlamı kesin hüküm değil, sorulabilecek bir soru olarak formüle et.'],['Ayı ve mevsimi gerçek verilerle birlikte oku','Ay fazı veya mevsim, tek başına bir davranışın nedeni değildir. Uyku, sağlık, iklim, iş yükü ve sosyal koşullar gibi gerçek yaşam verileri sembolik gözlemden ayrı tutulmalıdır.'],['Kültürel saygı','Yaşayan toplulukların kutsal uygulamalarını izinsiz yeniden üretmek, isimlerini dekoratif bir “ritüel” paketine çevirmek veya tek bir otantik yöntem iddia etmek yerine kaynak, sınır ve belirsizliği açıkça belirtmek gerekir.']],faq:[['Bu bir şaman astrolojisi rehberi mi?','Hayır. Tek bir evrensel şaman astrolojisi yoktur. Bu sayfa belirli bir yaşayan kültürün kutsal uygulamasını öğretmez; yerel doğa gözlemi ve kişisel günlük tutma için genel bir etik çerçeve sunar.'],['Ay fazları davranışımı belirler mi?','Hayır. Ay fazı gözlem için bir zaman işareti olabilir; kişisel kararların yerine geçmez ve tek başına nedensel açıklama sunmaz.'],['Kendi gözlem günlüğümü nasıl başlatırım?','Tarih, konum, gökyüzü gözlemi, hava/mevsim, beden-duygu notu ve günün açık sorusunu beş kısa satırda kaydet.']],sources:[['Mythborn — Today’s Sky','/bugunun-gokyuzu'],['Mythborn — Moon Calendar','/ay-takvimi']],related:[['Kadim Gökyüzü Merkezi','/kadim-gokyuzu'],['Travma-Bilinçli Astrolojik Farkındalık','/travma-bilincli-astroloji']]},
    '/travma-bilincli-astroloji':{tag:'GÜVENLİK · SEÇİM · SINIR',title:'Travma-Bilinçli Astrolojik Farkındalık',description:'Astrolojik sembolleri tanı veya tedavi yerine güvenlik, seçim, sınır ve öz-refleksiyon çerçevesinde kullan.',cards:[['GÜVENLİK','Önce durabilmek','Bir yorum seni yükseltiyor, korkutuyor veya kontrolünü azaltıyorsa okumayı durdurmak her zaman geçerli bir seçimdir.'],['ŞEFFAFLIK','Ne yaptığını bilmek','Mythborn astrolojiyi terapi, tanı veya travma tedavisi olarak sunmaz; sembolik bir düşünme aracı olarak sınırlarını açıklar.'],['SEÇİM','Kendi sesin','Sembol, senin deneyiminin yerine geçmez. “Bu bende ne çağrıştırıyor?” sorusu, kesin hükümden daha güvenli bir başlangıçtır.'],['SINIR','Gerçek desteğe yönelmek','Kriz, kendine zarar riski, şiddet veya yoğun psikolojik sıkıntı varsa astrolojik içerik yerine yerel acil ve profesyonel destek tercih edilmelidir.']],sections:[['Travma-bilinçli yaklaşım ne demektir?','SAMHSA ve benzeri çerçeveler güvenlik, güven ve şeffaflık, akran desteği, iş birliği, güçlendirme ve kültürel/toplumsal konulara duyarlılık gibi ilkeleri öne çıkarır. Mythborn bu ilkeleri klinik bakım sunduğunu iddia etmeden, metin ve araç diline uyarlamaya çalışır.'],['Astroloji burada ne yapabilir?','Bir sembolü yaşadığın konu hakkında açık uçlu bir soru üretmek için kullanabilir. Örneğin “Bu açı ayrılığı kesinleştirir mi?” yerine “Bu ilişkide hangi sınırı daha açık ifade etmem gerekiyor?” sorusunu deneyebilirsin.'],['Ne yapamaz?','Astroloji travma tanısı koyamaz, tedavi sağlayamaz, güvenlik riskini ölçemez, bir kişinin davranışını kesin olarak açıklayamaz ve tıbbi/hukuki/finansal kararların yerine geçemez.'],['Güvenli çıkış planı','Yoğunluk yükselirse ekranı kapat, bulunduğun mekânda yönünü ve nefesini fark et, güvendiğin bir kişiye ulaş ve gerektiğinde bulunduğun ülkedeki acil veya ruh sağlığı hizmetlerinden destek al.']],faq:[['Travma-bilinçli astroloji terapi midir?','Hayır. Mythborn terapi, tanı veya travma tedavisi sunmaz. Bu sayfa sembolik öz-refleksiyon için güvenlik ve seçim odaklı bir dil çerçevesidir.'],['Haritam travmamı gösterir mi?','Hayır. Bir doğum haritası travma tanısı veya psikolojik değerlendirme aracı değildir. Yaşantını ve desteğe ihtiyaç duyup duymadığını yalnızca yetkin profesyonellerle değerlendirmelisin.'],['Yorum beni kötü hissettirirse ne yapmalıyım?','Okumayı durdur, güvenli bir ortama dön, güvendiğin birine ulaş ve ihtiyaç varsa yerel profesyonel/acil destek kaynaklarını kullan.']],sources:[['SAMHSA — Six Guiding Principles to a Trauma-Informed Approach','https://www.samhsa.gov/resource/dbhis/infographic-6-guiding-principles-trauma-informed-approach']],related:[['Doğa ve Gökyüzü Döngüleri','/doga-gokyuzu-donguleri'],['Kullanım Koşulları','/kullanim-kosullari']]}
  }
};
ancientGuides.en={
  '/maya-zaman-donguleri':{tag:'TZOLK’IN · HAAB · CALENDAR ROUND · LONG COUNT',title:'Maya Time Cycles',description:'Learn how Tzolk’in, Haab, the Calendar Round and Long Count worked in historical context, without reducing Maya calendars to a modern zodiac.',cards:[['260 DAYS','Tzolk’in','A 260-day cycle made from 20 day names combined with numbers 1 through 13. The day name and number form one date.'],['365 DAYS','Haab','A 365-day cycle made from 18 periods of 20 days plus the five-day Wayeb section, approximating the solar year.'],['52 YEARS','Calendar Round','A Tzolk’in and Haab combination does not repeat until roughly 52 Haab years have passed.'],['HISTORY','Long Count','A linear count for dates beyond the Calendar Round; a complete date can also include Tzolk’in and Haab information.']],sections:[['Not a “Maya zodiac”','Maya calendars are not equivalent to a Western-style horoscope that reduces a birth date to one personality label. Reading a date requires the calendar layer, language, community context and historical source to remain visible.'],['How a date is read','A date can combine a Tzolk’in day with a Haab day, while the Long Count places longer events in sequence. A responsible converter should explain which correlation assumption it uses instead of producing an unexplained personality verdict.'],['2012 without the apocalypse story','The 13.0.0.0.0 date reached on 21 December 2012 marked a calendrical turning point, not the end of the world. Read it as a record of cycles and continuity, not a sensational prediction.'],['Living context today','Smithsonian material describes contemporary Maya calendar keepers and communities who continue to maintain and use calendar knowledge. This guide therefore avoids packaging living traditions as an extinct prediction system.']],faq:[['Are Maya calendars astrology?','Some historical uses relate to sky observation and ritual, but Tzolk’in, Haab and Long Count are not one modern personality astrology system.'],['Can I calculate my Maya sign?','A date can be converted, but the result should state the chosen correlation, language and calendar tradition. Mythborn emphasizes historical time knowledge rather than personality diagnosis.'],['Why does Haab have 365 days?','It contains 18 periods of 20 days plus the five-day Wayeb section: 18×20+5=365.']],sources:[['Smithsonian National Museum of the American Indian — The Calendar System','https://maya.nmai.si.edu/calendar/calendar-system']],related:[['Ancient Sky Traditions','/kadim-gokyuzu'],['Mesopotamian Astrology','/mezopotamya-astrolojisi']]},
  '/mezopotamya-astrolojisi':{tag:'SUMER · BABYLON · ASSYRIA',title:'Mesopotamian Astrology',description:'Study Sumerian, Babylonian and Assyrian sky records through omen series, MUL.APIN, the zodiac and early personal horoscopes.',cards:[['OMENS','Enūma Anu Enlil','A large omen tradition connecting the Moon, Sun, planets and weather phenomena with kingship, society and time.'],['STAR LISTS','MUL.APIN','A Babylonian compilation concerning visible stars and constellations, seasons, months and patterns of celestial observation.'],['ZODIAC','12 equal signs','Later Babylonian mathematical practice divided the ecliptic into 12 equal signs, influencing the history of the zodiac.'],['HOROSCOPES','Personal records','Late Babylonian examples recorded planetary positions at birth in specific historical and archival contexts.']],sections:[['Not one Mesopotamian astrology','Sumerian, Babylonian and Assyrian materials belong to different periods and archives. Omen series, star catalogues, astronomical diaries and horoscopes were not one book with one function.'],['Astronomy and omen are related but distinct','Recording a star’s rising or calculating a planetary position is an astronomical practice. Drawing a sign about a king or country from a celestial event belongs to a different interpretive layer.'],['MUL.APIN is not a modern zodiac list','MUL.APIN is not equivalent to internet lists of “Sumerian signs.” The Penn Museum’s Neo-Babylonian tablet record places MUL.APIN in a context of astronomical or calendrical lists and omen material.'],['The emergence of personal horoscopes','Late Babylonian personal horoscopes show that planetary positions were recorded in specific historical contexts, not as one universal personality test.']],faq:[['Are Sumerian zodiac signs historically real?','Modern 12-item “Sumerian sign” lists often flatten differences of period, language and function. They should not be presented as a direct historical equivalent without evidence.'],['What is MUL.APIN?','MUL.APIN is a Babylonian compilation associated with stars, constellations, celestial movements, months and observation; it is not a modern horoscope guide.'],['Are Mesopotamian astrology and astronomy the same?','No. Observation and calculation produced astronomical knowledge, while omen and horoscope interpretation added cultural meaning to celestial events.']],sources:[['Penn Museum — Neo-Babylonian MUL.APIN tablet record','https://collections.penn.museum/collections/object/570158'],['British Museum — MUL.APIN tablet record','https://www.britishmuseum.org/collection/object/W_1899-0610-108']],related:[['Ancient Sky Traditions','/kadim-gokyuzu'],['Maya Time Cycles','/maya-zaman-donguleri']]},
  '/doga-gokyuzu-donguleri':{tag:'SEASON · DIRECTION · MOON · PLACE',title:'Nature and Sky Cycles',description:'Use seasons, directions, the Moon and local nature observation as a respectful reflection framework without claiming one universal shamanic tradition.',cards:[['SEASONS','Cyclical time','Observe solstices, equinoxes and local seasonal transitions while remembering that climate and calendars differ by place.'],['DIRECTIONS','Place awareness','Directional symbols vary across cultures. Start with the history and experience of the place where you actually live.'],['MOON','Observation practice','Use lunar phases as a gentle prompt for journaling and review, not as the sole cause of a mood, decision or event.'],['GROUND','Local context','Nature observation begins with the real climate, plants, water and seasonal transitions of your own region.']],sections:[['What this guide does not claim','We do not combine Indigenous and folk traditions into one universal “shamanic astrology.” Each community’s relationship with sky, seasons, directions and ritual belongs to its own living context.'],['A four-step observation practice','Write the date and location. Record what you actually observe in the sky. Add a separate note for body and emotion. Finally, turn the symbol into an open question rather than a fixed conclusion.'],['Read the Moon and season with real data','A lunar phase or season is not, by itself, a causal explanation for behaviour. Sleep, health, climate, workload and social conditions should remain distinct from symbolic reflection.'],['Cultural respect','Do not reproduce sacred practices without permission, turn community names into decorative “ritual” packages, or claim one authentic method. State sources, boundaries and uncertainty clearly.']],faq:[['Is this a guide to shamanic astrology?','No. There is no single universal shamanic astrology. This page does not teach a living community’s sacred practice; it offers a general ethical framework for local observation and journaling.'],['Do lunar phases determine behaviour?','No. A lunar phase can be a time marker for observation, but it does not replace personal decisions or provide a single causal explanation.'],['How do I start a nature journal?','Record the date, location, sky observation, weather/season, body-emotion note and one open question in six short lines.']],sources:[['Mythborn — Today’s Sky','/bugunun-gokyuzu'],['Mythborn — Moon Calendar','/ay-takvimi']],related:[['Ancient Sky Traditions','/kadim-gokyuzu'],['Trauma-Informed Astrology','/travma-bilincli-astroloji']]},
  '/travma-bilincli-astroloji':{tag:'SAFETY · CHOICE · BOUNDARIES',title:'Trauma-Informed Astrological Reflection',description:'Use astrological symbols for reflection rather than diagnosis or treatment, with safety, choice, boundaries and uncertainty at the centre.',cards:[['SAFETY','Permission to stop','If a reading increases fear, overwhelm or loss of control, stopping is always a valid choice.'],['TRANSPARENCY','Know the limits','Mythborn does not present astrology as therapy, diagnosis or trauma treatment; it states the limits of symbolic reflection.'],['CHOICE','Keep your voice','A symbol does not replace your experience. “What does this bring up for me?” is safer than a deterministic verdict.'],['BOUNDARIES','Real support matters','If there is crisis, self-harm risk, violence or severe distress, use local emergency and professional support rather than astrology content.']],sections:[['What does trauma-informed mean here?','SAMHSA and related frameworks emphasize safety, trust and transparency, peer support, collaboration, empowerment and cultural awareness. Mythborn adapts the language principles without claiming to provide clinical care.'],['What can astrology do?','It can turn a symbol into an open question about a lived topic. Instead of “Does this aspect guarantee a breakup?”, try “Which boundary or communication habit needs more clarity in this relationship?”'],['What can it not do?','Astrology cannot diagnose trauma, provide treatment, measure safety risk, explain a person with certainty or replace medical, legal or financial advice.'],['A safe exit plan','If intensity rises, close the page, orient yourself to the room, contact someone you trust and use local emergency or mental-health support when needed.']],faq:[['Is trauma-informed astrology therapy?','No. Mythborn does not provide therapy, diagnosis or trauma treatment. This page is a safety- and choice-centred language framework for symbolic reflection.'],['Can my birth chart show my trauma?','No. A birth chart is not a trauma diagnosis or psychological assessment. Discuss lived experience and support needs with a qualified professional.'],['What should I do if a reading makes me feel worse?','Stop reading, return to a safer environment, contact someone you trust and use local professional or emergency support if needed.']],sources:[['SAMHSA — Six Guiding Principles to a Trauma-Informed Approach','https://www.samhsa.gov/resource/dbhis/infographic-6-guiding-principles-trauma-informed-approach']],related:[['Nature and Sky Cycles','/doga-gokyuzu-donguleri'],['Terms of Use','/kullanim-kosullari']]}
};
ancientGuides.el={
  '/maya-zaman-donguleri':{tag:'TZOLK’IN · HAAB · ΗΜΕΡΟΛΟΓΙΑΚΟΣ ΓΥΡΟΣ · ΜΑΚΡΑ ΑΡΙΘΜΗΣΗ',title:'Κύκλοι Χρόνου των Μάγια',description:'Μάθε πώς λειτουργούσαν τα Tzolk’in, Haab, ο Ημερολογιακός Γύρος και η Μακρά Αρίθμηση στο ιστορικό τους πλαίσιο, χωρίς να μετατρέπεις τα ημερολόγια των Μάγια σε σύγχρονο ζώδιο.',cards:[['260 ΗΜΕΡΕΣ','Tzolk’in','Ένας κύκλος 260 ημερών που συνδυάζει 20 ονόματα ημερών με τους αριθμούς 1 έως 13.'],['365 ΗΜΕΡΕΣ','Haab','Κύκλος 365 ημερών με 18 περιόδους των 20 ημερών και το πενθήμερο Wayeb, κοντά στο ηλιακό έτος.'],['52 ΧΡΟΝΙΑ','Ημερολογιακός Γύρος','Ο ίδιος συνδυασμός Tzolk’in και Haab επανέρχεται περίπου μετά από 52 έτη Haab.'],['ΙΣΤΟΡΙΑ','Μακρά Αρίθμηση','Γραμμική καταμέτρηση για ημερομηνίες πέρα από τον Ημερολογιακό Γύρο, μαζί με Tzolk’in και Haab.']],sections:[['Δεν είναι «ζώδιο των Μάγια»','Τα ημερολόγια των Μάγια δεν ισοδυναμούν με δυτικό ωροσκόπιο που μειώνει την ημερομηνία γέννησης σε ένα χαρακτηριστικό προσωπικότητας.'],['Πώς διαβάζεται μια ημερομηνία','Μια ημερομηνία μπορεί να συνδυάζει ημέρα Tzolk’in και ημέρα Haab, ενώ η Μακρά Αρίθμηση τοποθετεί μεγαλύτερα γεγονότα σε ακολουθία. Ένας υπεύθυνος μετατροπέας πρέπει να εξηγεί την επιλογή συσχέτισης.'],['Το 2012 χωρίς την ιστορία της αποκάλυψης','Η ημερομηνία 13.0.0.0.0 στις 21 Δεκεμβρίου 2012 ήταν σημείο ημερολογιακής μετάβασης, όχι το τέλος του κόσμου.'],['Ζωντανό πλαίσιο σήμερα','Οι πηγές του Smithsonian περιγράφουν σύγχρονους φύλακες ημερολογίων και κοινότητες των Μάγια που συνεχίζουν να διατηρούν αυτή τη γνώση.']],faq:[['Είναι τα ημερολόγια των Μάγια αστρολογία;','Ορισμένες ιστορικές χρήσεις συνδέονται με την παρατήρηση του ουρανού και τελετουργίες, αλλά τα Tzolk’in, Haab και Μακρά Αρίθμηση δεν είναι ένα σύγχρονο σύστημα προσωπικότητας.'],['Μπορώ να υπολογίσω το ζώδιό μου των Μάγια;','Μια ημερομηνία μπορεί να μετατραπεί, αλλά το αποτέλεσμα πρέπει να αναφέρει τη συσχέτιση, τη γλώσσα και την παράδοση που χρησιμοποιεί.'],['Γιατί το Haab έχει 365 ημέρες;','Αποτελείται από 18 περιόδους των 20 ημερών και το πενθήμερο Wayeb: 18×20+5=365.']],sources:[['Smithsonian National Museum of the American Indian — The Calendar System','https://maya.nmai.si.edu/calendar/calendar-system']],related:[['Αρχαίες Ουράνιες Παραδόσεις','/kadim-gokyuzu'],['Μεσοποταμιακή Αστρολογία','/mezopotamya-astrolojisi']]},
  '/mezopotamya-astrolojisi':{tag:'ΣΟΥΜΕΡΙΟΙ · ΒΑΒΥΛΩΝΙΟΙ · ΑΣΣΥΡΙΟΙ',title:'Μεσοποταμιακή Αστρολογία',description:'Μελέτησε τα ουράνια αρχεία των Σουμερίων, των Βαβυλωνίων και των Ασσυρίων μέσα από οιωνούς, MUL.APIN, τον ζωδιακό και τα πρώιμα προσωπικά ωροσκόπια.',cards:[['ΟΙΩΝΟΙ','Enūma Anu Enlil','Μια μεγάλη παράδοση οιωνών που συνδέει Σελήνη, Ήλιο, πλανήτες και καιρικά φαινόμενα με την κοινωνία και την εξουσία.'],['ΚΑΤΑΛΟΓΟΙ ΑΣΤΡΩΝ','MUL.APIN','Βαβυλωνιακή συλλογή για άστρα, αστερισμούς, εποχές, μήνες και παρατήρηση του ουρανού.'],['ΖΩΔΙΑΚΟΣ','12 ίσα τμήματα','Μεταγενέστερη βαβυλωνιακή μαθηματική πρακτική χώρισε την εκλειπτική σε 12 ίσα τμήματα.'],['ΩΡΟΣΚΟΠΙΑ','Προσωπικές καταγραφές','Στα ύστερα βαβυλωνιακά χρόνια καταγράφηκαν θέσεις πλανητών κατά τη γέννηση σε συγκεκριμένο ιστορικό πλαίσιο.']],sections:[['Δεν υπήρχε μία μεσοποταμιακή αστρολογία','Τα σουμεριακά, βαβυλωνιακά και ασσυριακά τεκμήρια ανήκουν σε διαφορετικές περιόδους και αρχεία. Οι σειρές οιωνών, οι κατάλογοι άστρων, τα ημερολόγια παρατηρήσεων και τα ωροσκόπια δεν είχαν μία ενιαία λειτουργία.'],['Η αστρονομία και ο οιωνός είναι συγγενή αλλά διαφορετικά','Η καταγραφή της ανατολής ενός άστρου ή ο υπολογισμός μιας πλανητικής θέσης είναι αστρονομική πρακτική. Η εξαγωγή οιωνού για έναν βασιλιά ή μια χώρα είναι διαφορετικό ερμηνευτικό επίπεδο.'],['Το MUL.APIN δεν είναι σύγχρονος κατάλογος ζωδίων','Το MUL.APIN δεν ισοδυναμεί με τις διαδικτυακές λίστες «σουμεριακών ζωδίων». Το τεκμήριο του Penn Museum το τοποθετεί σε πλαίσιο αστρονομικών ή ημερολογιακών καταλόγων και οιωνών.'],['Η εμφάνιση προσωπικών ωροσκοπίων','Τα ύστερα βαβυλωνιακά προσωπικά ωροσκόπια δείχνουν ότι οι θέσεις των πλανητών καταγράφονταν σε συγκεκριμένα ιστορικά πλαίσια, όχι ως ένα καθολικό τεστ προσωπικότητας.']],faq:[['Υπήρχαν ιστορικά σουμεριακά ζώδια;','Οι σύγχρονες λίστες με 12 «σουμεριακά ζώδια» συχνά ισοπεδώνουν διαφορές περιόδου, γλώσσας και λειτουργίας. Δεν πρέπει να παρουσιάζονται ως άμεσο ιστορικό ισοδύναμο χωρίς τεκμηρίωση.'],['Τι είναι το MUL.APIN;','Το MUL.APIN είναι βαβυλωνιακή συλλογή για άστρα, αστερισμούς, ουράνιες κινήσεις, μήνες και παρατήρηση· δεν είναι σύγχρονος οδηγός ωροσκοπίου.'],['Είναι ίδια η αστρονομία και η μεσοποταμιακή αστρολογία;','Όχι. Η παρατήρηση και ο υπολογισμός παρήγαγαν αστρονομική γνώση, ενώ οι οιωνοί και τα ωροσκόπια πρόσθεταν πολιτισμικό νόημα στα ουράνια γεγονότα.']],sources:[['Penn Museum — Neo-Babylonian MUL.APIN tablet record','https://collections.penn.museum/collections/object/570158'],['British Museum — MUL.APIN tablet record','https://www.britishmuseum.org/collection/object/W_1899-0610-108']],related:[['Αρχαίες Ουράνιες Παραδόσεις','/kadim-gokyuzu'],['Κύκλοι Χρόνου των Μάγια','/maya-zaman-donguleri']]},
  '/doga-gokyuzu-donguleri':{tag:'ΕΠΟΧΗ · ΚΑΤΕΥΘΥΝΣΗ · ΣΕΛΗΝΗ · ΤΟΠΟΣ',title:'Κύκλοι Φύσης και Ουρανού',description:'Χρησιμοποίησε εποχές, κατευθύνσεις, Σελήνη και τοπική παρατήρηση της φύσης ως πλαίσιο στοχασμού χωρίς να υποστηρίζεις μία καθολική σαμανική παράδοση.',cards:[['ΕΠΟΧΕΣ','Κυκλικός χρόνος','Παρατήρησε ηλιοστάσια, ισημερίες και τοπικές μεταβάσεις των εποχών, θυμούμενος ότι το κλίμα διαφέρει ανά τόπο.'],['ΚΑΤΕΥΘΥΝΣΕΙΣ','Επίγνωση τόπου','Τα σύμβολα των κατευθύνσεων διαφέρουν ανά πολιτισμό. Ξεκίνα από την ιστορία του τόπου όπου ζεις.'],['ΣΕΛΗΝΗ','Πρακτική παρατήρησης','Χρησιμοποίησε τις φάσεις της Σελήνης ως αφορμή για ημερολόγιο και ανασκόπηση, όχι ως μοναδική αιτία μιας συμπεριφοράς.'],['ΓΗ','Τοπικό πλαίσιο','Η παρατήρηση της φύσης αρχίζει από το πραγματικό κλίμα, τα φυτά, το νερό και τις εποχικές μεταβολές της περιοχής σου.']],sections:[['Τι δεν υποστηρίζει αυτός ο οδηγός','Δεν ενώνουμε τις αυτόχθονες και λαϊκές παραδόσεις σε μία καθολική «σαμανική αστρολογία». Κάθε κοινότητα έχει το δικό της ζωντανό πλαίσιο.'],['Πρακτική παρατήρησης σε τέσσερα βήματα','Γράψε ημερομηνία και τόπο. Κατέγραψε ό,τι πραγματικά παρατηρείς στον ουρανό. Πρόσθεσε ξεχωριστή σημείωση για σώμα και συναίσθημα. Τέλος, μετέτρεψε το σύμβολο σε ανοιχτό ερώτημα.'],['Σελήνη και εποχή μαζί με πραγματικά δεδομένα','Μια φάση της Σελήνης ή μια εποχή δεν αποτελεί μόνη της αιτιώδη εξήγηση για τη συμπεριφορά. Ύπνος, υγεία, κλίμα, εργασία και κοινωνικές συνθήκες μένουν ξεχωριστά από τον συμβολικό στοχασμό.'],['Πολιτισμικός σεβασμός','Μην αναπαράγεις ιερές πρακτικές χωρίς άδεια, μην μετατρέπεις ονόματα κοινοτήτων σε διακοσμητικά πακέτα και δήλωνε καθαρά πηγές, όρια και αβεβαιότητα.']],faq:[['Είναι αυτό οδηγός σαμανικής αστρολογίας;','Όχι. Δεν υπάρχει μία καθολική σαμανική αστρολογία. Η σελίδα δεν διδάσκει ιερή πρακτική ζωντανής κοινότητας· προσφέρει γενικό πλαίσιο ηθικής παρατήρησης και ημερολογίου.'],['Καθορίζουν οι φάσεις της Σελήνης τη συμπεριφορά;','Όχι. Μια φάση μπορεί να λειτουργήσει ως χρονικός δείκτης παρατήρησης, αλλά δεν αντικαθιστά τις αποφάσεις ούτε δίνει μία μοναδική αιτία.'],['Πώς αρχίζω ημερολόγιο φύσης;','Σημείωσε ημερομηνία, τόπο, παρατήρηση ουρανού, καιρό/εποχή, σώμα-συναίσθημα και ένα ανοιχτό ερώτημα.']],sources:[['Mythborn — Ο Σημερινός Ουρανός','/bugunun-gokyuzu'],['Mythborn — Σεληνιακό Ημερολόγιο','/ay-takvimi']],related:[['Αρχαίες Ουράνιες Παραδόσεις','/kadim-gokyuzu'],['Αστρολογία με Επίγνωση Τραύματος','/travma-bilincli-astroloji']]},
  '/travma-bilincli-astroloji':{tag:'ΑΣΦΑΛΕΙΑ · ΕΠΙΛΟΓΗ · ΟΡΙΑ',title:'Αστρολογικός Στοχασμός με Επίγνωση Τραύματος',description:'Χρησιμοποίησε τα αστρολογικά σύμβολα για στοχασμό και όχι για διάγνωση ή θεραπεία, με επίκεντρο την ασφάλεια, την επιλογή, τα όρια και την αβεβαιότητα.',cards:[['ΑΣΦΑΛΕΙΑ','Άδεια να σταματήσεις','Αν μια ανάγνωση αυξάνει φόβο, ένταση ή απώλεια ελέγχου, το να σταματήσεις είναι πάντα έγκυρη επιλογή.'],['ΔΙΑΦΑΝΕΙΑ','Γνώρισε τα όρια','Το Mythborn δεν παρουσιάζει την αστρολογία ως θεραπεία, διάγνωση ή θεραπεία τραύματος· εξηγεί τα όρια του συμβολικού στοχασμού.'],['ΕΠΙΛΟΓΗ','Κράτησε τη φωνή σου','Ένα σύμβολο δεν αντικαθιστά την εμπειρία σου. Το «τι μου προκαλεί αυτό;» είναι ασφαλέστερο από ένα ντετερμινιστικό συμπέρασμα.'],['ΟΡΙΑ','Η πραγματική υποστήριξη έχει σημασία','Σε κρίση, κίνδυνο αυτοτραυματισμού, βία ή έντονη δυσφορία, χρησιμοποίησε τοπική επαγγελματική ή επείγουσα υποστήριξη.']],sections:[['Τι σημαίνει εδώ «με επίγνωση τραύματος»;','Τα σχετικά πλαίσια τονίζουν την ασφάλεια, την εμπιστοσύνη και τη διαφάνεια, την αλληλοϋποστήριξη, τη συνεργασία, την ενδυνάμωση και την πολιτισμική επίγνωση. Το Mythborn προσαρμόζει αυτές τις αρχές στη γλώσσα χωρίς να ισχυρίζεται ότι παρέχει κλινική φροντίδα.'],['Τι μπορεί να κάνει η αστρολογία;','Μπορεί να μετατρέψει ένα σύμβολο σε ανοιχτό ερώτημα για μια εμπειρία. Αντί για «εγγυάται αυτή η όψη χωρισμό;», ρώτησε «ποιο όριο ή ποια συνήθεια επικοινωνίας χρειάζεται περισσότερη σαφήνεια;».'],['Τι δεν μπορεί να κάνει;','Η αστρολογία δεν διαγιγνώσκει τραύμα, δεν παρέχει θεραπεία, δεν μετρά κίνδυνο ασφάλειας, δεν εξηγεί ένα άτομο με βεβαιότητα και δεν αντικαθιστά ιατρικές, νομικές ή οικονομικές συμβουλές.'],['Σχέδιο ασφαλούς εξόδου','Αν αυξηθεί η ένταση, κλείσε τη σελίδα, προσανατολίσου στον χώρο, επικοινώνησε με άνθρωπο εμπιστοσύνης και χρησιμοποίησε τοπική επαγγελματική ή επείγουσα βοήθεια όταν χρειάζεται.']],faq:[['Είναι θεραπεία η αστρολογία με επίγνωση τραύματος;','Όχι. Το Mythborn δεν παρέχει θεραπεία, διάγνωση ή θεραπεία τραύματος. Η σελίδα είναι πλαίσιο συμβολικού στοχασμού με επίκεντρο την ασφάλεια και την επιλογή.'],['Μπορεί ο γενέθλιος χάρτης να δείξει το τραύμα μου;','Όχι. Ο γενέθλιος χάρτης δεν είναι διάγνωση τραύματος ή ψυχολογική αξιολόγηση. Για εμπειρίες ζωής και ανάγκες υποστήριξης απευθύνσου σε κατάλληλο επαγγελματία.'],['Τι να κάνω αν μια ανάγνωση με κάνει να νιώσω χειρότερα;','Σταμάτησε, επέστρεψε σε ασφαλέστερο περιβάλλον, επικοινώνησε με πρόσωπο εμπιστοσύνης και χρησιμοποίησε τοπική επαγγελματική ή επείγουσα υποστήριξη.']],sources:[['SAMHSA — Six Guiding Principles to a Trauma-Informed Approach','https://www.samhsa.gov/resource/dbhis/infographic-6-guiding-principles-trauma-informed-approach']],related:[['Κύκλοι Φύσης και Ουρανού','/doga-gokyuzu-donguleri'],['Όροι Χρήσης','/kullanim-kosullari']]}
};
const ancientSections=locale=>`<section class="editorial-section ancient-depth"><p class="eyebrow">${locale==='tr'?'YORUMDAN ÖNCE BAĞLAM':locale==='en'?'CONTEXT BEFORE INTERPRETATION':'ΠΛΑΙΣΙΟ ΠΡΙΝ ΑΠΟ ΤΗΝ ΕΡΜΗΝΕΙΑ'}</p><div class="editorial-grid">${ancientDepth[locale].map(([title,text])=>`<article class="editorial-card"><h3>${title}</h3><p>${text}</p></article>`).join('')}</div></section>`;
const sourceBlock=(locale,sources)=>`<section class="editorial-section guide-sources"><p class="eyebrow">${locale==='tr'?'KAYNAKLAR VE İLERİ OKUMA':locale==='en'?'SOURCES AND FURTHER READING':'ΠΗΓΕΣ ΚΑΙ ΠΕΡΑΙΤΕΡΩ ΑΝΑΓΝΩΣΗ'}</p><div class="editorial-links">${sources.map(([label,url])=>url.startsWith('/')?`<a href="${path(locale,url)}"><strong>${label}</strong><span>${locale==='tr'?'Mythborn sayfası':locale==='en'?'Mythborn guide':'Οδηγός Mythborn'}</span></a>`:`<a href="${url}" target="_blank" rel="noopener noreferrer"><strong>${label}</strong><span>${locale==='tr'?'Dış kaynak ↗':locale==='en'?'External source ↗':'Εξωτερική πηγή ↗'}</span></a>`).join('')}</div></section>`;
const faqBlock=(locale,faq)=>`<section class="editorial-section guide-faq"><p class="eyebrow">${locale==='tr'?'SIK SORULAN SORULAR':locale==='en'?'FREQUENT QUESTIONS':'ΣΥΧΝΕΣ ΕΡΩΤΗΣΕΙΣ'}</p><div class="faq-list">${faq.map(([q,a])=>`<details><summary>${q}</summary><p>${a}</p></details>`).join('')}</div></section>`;
const guidePage=(locale,guide)=>wrap([guide.tag,guide.title,guide.description],`<div class="editorial-grid ancient-guide-cards">${guide.cards.map(([tag,title,text])=>`<article class="editorial-card"><small>${tag}</small><h2>${title}</h2><p>${text}</p></article>`).join('')}</div><div class="guide-sections">${guide.sections.map(([title,text])=>`<section class="editorial-section"><div class="editorial-head"><div><p class="eyebrow">${locale==='tr'?'MYTHBORN YAKLAŞIMI':locale==='en'?'MYTHBORN APPROACH':'ΠΡΟΣΕΓΓΙΣΗ MYTHBORN'}</p><h2>${title}</h2></div><p>${text}</p></div></section>`).join('')}</div>${faqBlock(locale,guide.faq)}${sourceBlock(locale,guide.sources)}<section class="editorial-links related-guides"><p class="eyebrow">${locale==='tr'?'İLGİLİ REHBERLER':locale==='en'?'RELATED GUIDES':'ΣΧΕΤΙΚΟΙ ΟΔΗΓΟΙ'}</p>${guide.related.map(([label,url])=>`<a href="${path(locale,url)}"><strong>${label}</strong><span>${locale==='tr'?'Keşfet →':locale==='en'?'Explore →':'Εξερεύνησε →'}</span></a>`).join('')}</section>`);
export function discoveryPage(locale,route){
  const t=locales[locale],f=t.form,place=locale==='tr'?'İstanbul, Türkiye':locale==='en'?'London, United Kingdom':'Αθήνα, Ελλάδα';
  if(route==='/bugunun-gokyuzu')return wrap(t.sky,`<div class="discovery-tool sky-tool" data-current-sky><p>${t.sky[3]}</p></div>`);
  if(route==='/ay-takvimi')return wrap(t.moon,`<div class="discovery-tool moon-tool" data-moon-calendar><p>${t.moon[3]}</p></div>`);
  if(route==='/sinastri')return wrap(t.synastry,`<form class="discovery-tool synastry-tool" data-synastry-form>${person(f,place,'first',f.first)}${person(f,place,'second',f.second)}<button class="btn btn-primary" type="submit">${f.calculate}</button><p class="form-message" data-synastry-message aria-live="polite"></p></form><div class="discovery-result" data-synastry-result hidden aria-live="polite" tabindex="-1"></div>`);
  if(route==='/numeroloji')return wrap(t.numerology,`<form class="discovery-tool compact-tool" data-numerology-form><label>${f.name}<input required name="name" maxlength="100"></label><label>${f.date}<input required type="date" name="birthDate"></label><button class="btn btn-primary" type="submit">${f.numbers}</button></form><div class="discovery-result" data-numerology-result hidden aria-live="polite" tabindex="-1"></div>`);
  if(route==='/ruya-yorumlari')return wrap(t.dream,`<form class="discovery-tool dream-depth-form" data-dream-form><label>${f.dream}<textarea required name="dream" minlength="40" maxlength="5000"></textarea></label><label>${f.emotion}<input name="emotion" maxlength="120"></label><label>${f.context}<input name="wakingContext" maxlength="300"></label><button class="btn btn-primary" type="submit">${f.interpret}</button></form><div class="discovery-result" data-dream-result hidden aria-live="polite"></div>`);
  if(route==='/burc-uyumu')return wrap(t.compatibility,`<form class="discovery-tool compact-tool" data-compatibility-form><label>${f.yourSign}<select name="first"></select></label><label>${f.otherSign}<select name="second"></select></label><button class="btn btn-primary" type="submit">${f.compare}</button></form><div class="discovery-result" data-compatibility-result hidden aria-live="polite"></div>`);
  if(route==='/kadim-gokyuzu')return wrap(t.ancient,`<div class="ancient-hub-grid"><div class="editorial-grid">${ancientCards[locale].map(([tag,title,text,url])=>`<article class="editorial-card"><small>${tag}</small><h2>${title}</h2><p>${text}</p><a href="${path(locale,url)}">${locale==='tr'?'Rehberi aç':locale==='en'?'Read guide':'Άνοιγμα οδηγού'}</a></article>`).join('')}</div></div>${ancientSections(locale)}`);
  const guide=ancientGuides[locale]?.[route];
  return guide?guidePage(locale,guide):null;
}
export function discoveryMeta(locale,route){
  const key={'/bugunun-gokyuzu':'sky','/sinastri':'synastry','/ay-takvimi':'moon','/ruya-yorumlari':'dream','/numeroloji':'numerology','/burc-uyumu':'compatibility','/kadim-gokyuzu':'ancient'}[route];
  const guide=ancientGuides[locale]?.[route];
  if(guide)return {title:`${guide.title} — Mythborn`,description:guide.description};
  if(!key)return null;
  const t=locales[locale][key];
  return {title:`${t[1]} — Mythborn`,description:t[2]};
}
export function discoverySchema(locale,route){
  const guide=ancientGuides[locale]?.[route];
  if(!guide)return [];
  const questions=guide.faq.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}));
  return [
    {'@context':'https://schema.org','@type':'Article',headline:guide.title,description:guide.description,inLanguage:locale==='tr'?'tr-TR':locale==='en'?'en':'el',about:{'@type':'Thing',name:guide.title}},
    {'@context':'https://schema.org','@type':'FAQPage',mainEntity:questions}
  ];
}
