import finalRouter from './final-router.js';

const hotfixHead=`<link rel="stylesheet" href="/mobile-menu-clean.css"><style>
.topbar{position:sticky!important;top:0!important;z-index:110!important;width:100%!important;background:rgba(8,7,11,.95)!important;border-bottom:1px solid rgba(255,255,255,.07)!important;backdrop-filter:blur(18px)!important;transform:none!important;opacity:1!important;visibility:visible!important}
@media(min-width:761px){.topbar .shell{min-height:76px!important;display:flex!important;align-items:center!important;gap:24px!important}.topbar .nav{margin-left:auto!important;display:flex!important;align-items:center!important;gap:7px!important;white-space:nowrap!important}.topbar .nav>a,.desktop-explore>summary{display:flex!important;align-items:center!important;min-height:40px!important;padding:0 11px!important;border-radius:999px!important;color:#aaa2b0!important;font-size:12px!important;cursor:pointer!important;list-style:none!important}.desktop-account{background:#f4eee5!important;color:#09070c!important;font-weight:850!important}.desktop-explore{position:relative!important}.desktop-explore-panel{position:absolute;top:48px;right:0;width:560px;padding:16px;border:1px solid rgba(255,255,255,.12);border-radius:22px;background:#0c0a10;display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.desktop-explore-panel a{padding:12px;border-radius:14px;color:#aaa2b0;font-size:12px;white-space:normal}.desktop-explore-panel a:hover{background:rgba(255,255,255,.06);color:#fff}}
@media(max-width:760px){.mobile-nav a{border-bottom:0!important}.mobile-nav-group,.mobile-nav-knowledge{border:1px solid rgba(255,255,255,.08)!important;border-radius:20px!important;background:rgba(255,255,255,.025)!important;padding:16px!important;margin-bottom:12px!important}.mobile-nav-grid{gap:8px 10px!important}.mobile-nav-grid a,.mobile-nav-knowledge a{min-height:44px!important;padding:11px 12px!important;border:0!important;border-radius:13px!important;background:rgba(255,255,255,.035)!important}.mobile-menu-close{position:fixed;right:18px;top:82px;z-index:130;width:46px;height:46px;border:1px solid rgba(255,255,255,.14);border-radius:50%;background:#f4eee5;color:#09070c;font-size:28px;display:none;align-items:center;justify-content:center}.mobile-nav.is-open .mobile-menu-close{display:flex!important}}
</style>`;

const hotfixScript=`<script>(()=>{const current=location.pathname.startsWith('/en')?'en':location.pathname.startsWith('/gr')?'gr':'tr';const p=current==='tr'?'':'/'+current;const labels={tr:['Günlük Kart','Tarot','Astroloji','Haftalık','Keşfet','Hesabım'],en:['Daily Card','Tarot','Astrology','Weekly','Explore','My Account'],gr:['Ημερήσια Κάρτα','Ταρώ','Αστρολογία','Εβδομαδιαίο','Εξερεύνηση','Ο Λογαριασμός μου']}[current];const apply=()=>{document.querySelectorAll('.language-switcher a').forEach(a=>{if(a.textContent.trim()==='EL')a.textContent='GR';const h=a.getAttribute('href');if(h&&h.startsWith('/el'))a.setAttribute('href','/gr'+h.slice(3))});const nav=document.querySelector('.topbar .nav');if(nav){nav.innerHTML='<a href="'+p+'/gunluk-kart">'+labels[0]+'</a><a href="'+p+'/tarot">'+labels[1]+'</a><a href="'+p+'/astroloji">'+labels[2]+'</a><a href="'+p+'/haftalik-burc">'+labels[3]+'</a><details class="desktop-explore"><summary>'+labels[4]+'</summary><div class="desktop-explore-panel"><a href="'+p+'/bugunun-gokyuzu">Sky</a><a href="'+p+'/sinastri">Synastry</a><a href="'+p+'/kadim-gokyuzu">Ancient Sky</a><a href="'+p+'/ruya-yorumlari">Dreams</a><a href="'+p+'/numeroloji">Numerology</a><a href="'+p+'/blog">Journal</a></div></details><a class="desktop-account" href="'+p+'/hesabim">'+labels[5]+'</a>'}const mobile=document.querySelector('.mobile-nav');if(mobile&&!mobile.querySelector('.mobile-menu-close')){const b=document.createElement('button');b.className='mobile-menu-close';b.type='button';b.textContent='×';b.setAttribute('aria-label',current==='tr'?'Kapat':current==='en'?'Close':'Κλείσιμο');b.onclick=()=>document.querySelector('.mobile-menu-button')?.click();mobile.appendChild(b)}const header=document.querySelector('.topbar');if(header){header.style.position='sticky';header.style.top='0';header.style.zIndex='110'}};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',apply):apply();setTimeout(apply,300);document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector('.mobile-nav.is-open .mobile-menu-close')?.click()})})()</script>`;

export default{async fetch(request,env,ctx){const incoming=new URL(request.url);if(incoming.pathname==='/el'||incoming.pathname.startsWith('/el/')){incoming.pathname='/gr'+incoming.pathname.slice(3);return Response.redirect(incoming.toString(),301)}let forwarded=request;if(incoming.pathname==='/gr'||incoming.pathname.startsWith('/gr/')){const internal=new URL(request.url);internal.pathname='/el'+internal.pathname.slice(3);forwarded=new Request(internal.toString(),request)}const response=await finalRouter.fetch(forwarded,env,ctx);const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;let html=await response.text();if(incoming.pathname==='/gr'||incoming.pathname.startsWith('/gr/'))html=html.replaceAll('/el','/gr').replaceAll('>EL<','>GR<');html=html.replace('</head>',hotfixHead+'</head>').replace('</body>',hotfixScript+'</body>');return new Response(html,{status:response.status,headers:response.headers})}};