const layout=(title,body)=>`<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#08070b"><meta name="description" content="Mythborn, arzularını seçimlere ve kişisel arketiplere dönüştüren Türkçe dijital deneyim platformudur."><link rel="canonical" href="https://mythborn.co/"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/app.css"><title>${title} — Mythborn</title></head><body><div class="shell"><header class="topbar"><a class="brand" href="/"><img src="/images/mythborn-emblem.png" alt=""><span>MYTHBORN</span></a><nav class="nav"><a href="/deneyim">Deneyim</a><a href="/arketipler">Arketipler</a><a href="/manifesto">Manifesto</a><a href="/uyelik">Üyelik</a><a href="/hesabim" data-account-link>Hesabım</a></nav></header>${body}<footer class="footer"><span>© 2026 Mythborn</span><span><a href="/gizlilik">Gizlilik</a> · <a href="/kvkk">KVKK</a> · <a href="/kullanim-kosullari">Koşullar</a></span></footer></div><script src="/app.js" defer></script></body></html>`;

const home=()=>layout('Arzunun bir adı var',`<main class="home"><section class="hero"><div><img class="hero-mark" src="/images/mythborn-emblem.png" alt="Mythborn amblemi"><p class="eyebrow">TÜRKİYE'NİN İLK ARZU DENEYİMİ</p><h1>Ne istediğini biliyorsun.<em>Neden istediğini bilmiyorsun.</em></h1><p class="lead">Seç. Vazgeç. Sahip ol. Mythborn, arzularının altında yatan kişiyi ortaya çıkarır.</p><div class="actions"><button class="btn btn-primary" data-start>Deneyime gir</button><a class="btn btn-ghost" href="/uyelik">Üyeliği keşfet</a></div></div></section><section class="section"><p class="eyebrow">SİSTEM SENİ OKUR</p><h2>Her seçim bir iz bırakır.</h2><div class="grid"><article class="card"><small>01</small><h3>Seç</h3><p>Statü, güç, aşk, kaçış, özgürlük ve kontrol arasında içgüdüsel kararlar ver.</p></article><article class="card"><small>02</small><h3>Ortaya çık</h3><p>Kararların ağırlıklandırılır; arzu değerin ve baskın Mythborn arketipin hesaplanır.</p></article><article class="card"><small>03</small><h3>Arşivle</h3><p>Üyeliğinle sonuçlarını sakla, yeni deneyimleri aç ve değişimini gör.</p></article></div></section><section class="section"><p class="eyebrow">TEK ÜYELİK</p><h2>Bir paket sigara parası. Bir ay boyunca kendinle yüzleş.</h2><div class="grid"><article class="card"><div class="price">115 TL <span>/ ay</span></div><p>Tüm deneyimler, kişisel sonuç arşivi, özel arketipler ve paylaşılabilir sonuç kartları.</p><a class="btn btn-primary" href="/kayit">Üyeliği başlat</a></article></div></section></main><main class="experience"><section class="section" id="experienceBody"><div class="progress"><span id="progress"></span></div><p class="eyebrow" style="margin-top:30px">İÇGÜDÜSEL SEÇ</p><h2 id="question"></h2><div class="choices" id="choices"></div></section></main>`);

const membership=()=>layout('Üyelik',`<main><section class="section"><p class="eyebrow">MYTHBORN ÜYELİĞİ</p><h2>Bir ay. Sınırsız yüzleşme.</h2><div class="grid"><article class="card"><div class="price">115 TL <span>/ ay</span></div><p>Tüm deneyimler, tam arketip sonuçları, geçmiş kayıtları, özel bölümler ve paylaşılabilir kartlar.</p><a class="btn btn-primary" href="/kayit">Üye ol</a></article><article class="card"><small>DAHİL</small><h3>Tek paket. Gizli ücret yok.</h3><p>İstediğin zaman iptal, hesap silme ve üyelik durumunu hesabından yönetme.</p></article></div></section></main>`);

const auth=(mode)=>layout(mode==='giris'?'Giriş':'Kayıt',`<main><section class="section"><p class="eyebrow">${mode==='giris'?'GERİ DÖN':'İÇERİ GİR'}</p><h2>${mode==='giris'?'Hesabına giriş yap.':'Mythborn hesabını oluştur.'}</h2><form class="card auth-form" data-auth-form="${mode}" style="max-width:560px;margin-top:36px"><label>E-posta<input required autocomplete="email" name="email" type="email"></label><label>Şifre<input required autocomplete="${mode==='giris'?'current-password':'new-password'}" name="password" type="password" minlength="10"></label>${mode==='kayit'?'<label class="consent"><input required name="terms" type="checkbox"> Kullanım koşullarını ve KVKK aydınlatma metnini okudum.</label>':''}<p class="form-message" data-form-message role="alert"></p><button class="btn btn-primary" type="submit">${mode==='giris'?'Giriş yap':'Hesap oluştur'}</button><p class="muted">${mode==='giris'?'<a href="/kayit">Hesabın yok mu? Kayıt ol.</a>':'Hesap oluşturmak ücretsizdir. 115 TL üyelik ödemesi ayrı onay adımında başlatılır.'}</p></form></section></main>`);

const account=()=>layout('Hesabım',`<main><section class="section" data-account><p class="eyebrow">ÜYE ALANI</p><h2>Hesabım</h2><div class="grid account-grid"><article class="card"><small>PROFİL</small><h3 data-account-email>Kontrol ediliyor…</h3><p data-account-status>Üyelik durumu yükleniyor.</p><div class="actions"><a class="btn btn-primary" href="/uyelik">Üyeliği yönet</a><button class="btn btn-ghost" data-logout>Çıkış yap</button></div></article><article class="card"><small>SONUÇ GEÇMİŞİ</small><div data-result-history><p>Sonuçların yükleniyor.</p></div></article></div></section></main>`);

const simple=(title,kicker,copy)=>layout(title,`<main><section class="section"><p class="eyebrow">${kicker}</p><h2>${title}</h2><p class="lead" style="margin-left:0">${copy}</p></section></main>`);

export default{async fetch(request){const p=new URL(request.url).pathname;let html;if(p==='/'||p==='/deneyim')html=home();else if(p==='/uyelik')html=membership();else if(p==='/giris'||p==='/kayit')html=auth(p.slice(1));else if(p==='/hesabim')html=account();else if(p==='/arketipler')html=simple('Arketipler','ARŞİV','Hükümdar, Kaçak, Taç, Yankı, Mimar, Gezgin ve Ateş. Her biri bir arzunun ardındaki gerçek ihtiyacı temsil eder.');else if(p==='/manifesto')html=simple('İnsan istediği şeyi satın almaz.','MANİFESTO','Kontrol, görünürlük, aidiyet, kaçış ve özgürlük satın almaya çalışır. Mythborn nesneleri değil, onların ardındaki dürtüyü görünür kılar.');else if(p==='/hakkinda')html=simple('Mythborn nedir?','HAKKINDA','Mythborn, insanın ne istediğinden çok neden istediğini araştıran bağımsız bir dijital deneyim platformudur.');else html=simple('Yasal Bilgilendirme','ŞEFFAFLIK','Ayrıntılı hukuki metinler ödeme altyapısı yayına alınmadan önce tamamlanacaktır.');return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','cache-control':'no-store'}})}};
