import base from './router.js';

const SITE='https://mythborn.co';
const locales={
  tr:{prefix:'',html:'tr-TR',label:'TR'},
  en:{prefix:'/en',html:'en',label:'EN'},
  el:{prefix:'/gr',html:'el',label:'GR'}
};

const dictionaries={
  en:{
    'Günlük Kart':'Daily Card','3 Kart Tarot':'3-Card Tarot','Aşk & Geri Dönüş':'Love & Reconnection','Kariyer & Para':'Career & Money','30 Gün':'30-Day Reading','Katina':'Katina','Astroloji':'Astrology','Astroloji Merkezi':'Astrology Centre','Haftalık Burç':'Weekly Horoscope','Gökyüzü':'Sky Now','Bugünün Gökyüzü':'Today’s Sky','Sinastri':'Synastry','Kadim':'Ancient Sky','Kadim Gökyüzü':'Ancient Sky','Rüya':'Dreams','Rüya Yorumları':'Dream Interpretation','Numeroloji':'Numerology','Ay Takvimi':'Moon Calendar','Blog':'Journal','Hesabım':'My Account','Giriş Yap':'Sign In','Üye Ol':'Join Free','Ücretsiz Üye Ol':'Join Free','Çıkış yap':'Sign Out',
    'TAMAMEN ÜCRETSİZ':'COMPLETELY FREE','Tüm açılımları aç.':'Unlock every reading.','E-posta':'Email','Şifre':'Password','Kullanım koşullarını ve KVKK metnini okudum.':'I have read the Terms of Use and Privacy Notice.','ÜCRETSİZ HESAP OLUŞTUR':'CREATE FREE ACCOUNT','Google ile devam et':'Continue with Google','veya e-posta ile':'or continue with email','TEKRAR HOŞ GELDİN':'WELCOME BACK','Hesabına giriş yap.':'Sign in to your account.','GİRİŞ YAP':'SIGN IN',
    'HER GÜN YENİ BİR İŞARET':'A NEW SIGNAL EVERY DAY','Kartını seç.':'Choose your card.','Mesajını gör.':'Read your message.','Tek kartımı aç':'Draw my daily card','Haftalık burcumu gör':'Read my weekly horoscope','ÖDEME KAPALI · TÜM DENEYİMLER ÜCRETSİZ':'NO PAYWALL · EVERY EXPERIENCE IS FREE','DENEYİMLER':'EXPERIENCES','Merak ettiğin konuya göre alanını seç.':'Choose the space that matches your question.','Keşfet':'Explore','ÜYE OLMADAN':'NO ACCOUNT NEEDED','ÜCRETSİZ ÜYELİK':'FREE MEMBERSHIP','HERKESE AÇIK':'OPEN TO EVERYONE',
    'MYTHBORN · GÖKYÜZÜ VE SEMBOL MERKEZİ':'MYTHBORN · SKY & SYMBOL CENTRE','Gökyüzünü oku.':'Read the sky.','Kendini keşfet.':'Discover yourself.','Bugünün gökyüzünü gör':'See today’s sky','Doğum haritamı çıkar':'Calculate my birth chart','Günlük kartımı aç':'Draw my daily card','TÜM DENEYİMLER ÜCRETSİZ':'ALL EXPERIENCES ARE FREE','BUGÜN MYTHBORN’DA':'TODAY ON MYTHBORN','Her gün geri dönmek için dört güçlü neden.':'Four meaningful reasons to return every day.','Güncel, hızlı ve gerçekten çalışan deneyimler.':'Current, fast and genuinely useful experiences.','EN ÇOK İLGİ GÖRENLER':'MOST EXPLORED','Platformun en güçlü araçları.':'The platform’s most powerful tools.',
    'Doğduğun anın gökyüzü haritasını keşfet.':'Explore the sky map of your birth moment.','Doğum bilgilerini gir.':'Enter your birth details.','Doğum tarihi':'Birth date','Doğum saati':'Birth time','Doğum yeri':'Birth place','Doğum saatimi bilmiyorum':'I do not know my birth time','Doğum haritamı yorumla':'Interpret my birth chart','Güneş Burcu':'Sun Sign','Ay Burcu':'Moon Sign','Yükselen':'Ascendant','Evler':'Houses','Gezegenler':'Planets','Açılar':'Aspects','Transitler':'Transits','Uyum Analizi':'Compatibility Analysis',
    'Bu hafta gökyüzü senin burcuna ne söylüyor?':'What is the sky saying to your sign this week?','12 BURÇ · HER HAFTA YENİ':'12 SIGNS · UPDATED WEEKLY','Aşk':'Love','Kariyer':'Career','Para':'Money','Enerji':'Energy','Dikkat':'Watch for','Güçlü gün':'Power day',
    'Bugünün merakını, yarının arşivine dönüştür.':'Turn today’s curiosity into tomorrow’s archive.','GÖKYÜZÜ GÜNDEMİ · DERİN REHBERLER':'SKY JOURNAL · IN-DEPTH GUIDES','Güncel gökyüzü olayları, ilişki astrolojisi, etik ve kişisel farkındalık üzerine özgün uzun form içerikler.':'Original long-form guides on current celestial events, relationship astrology, ethics and self-reflection.','Yazıyı oku →':'Read article →','Tüm yazılar':'All articles','SIK SORULANLAR':'FREQUENTLY ASKED QUESTIONS','Konuyla ilgili kısa yanıtlar.':'Clear answers to common questions.',
    'Çerezler':'Cookies','Zorunlu çerezleri oturum ve güvenlik için kullanıyoruz.':'We use essential cookies for sessions and security.','Detaylar':'Details','Reddet':'Reject','Kabul et':'Accept','Gizlilik':'Privacy','KVKK':'Privacy Notice','Kullanım Koşulları':'Terms of Use','Eğlence, eğitim ve kişisel farkındalık amaçlıdır.':'For entertainment, education and personal reflection.','Tüm hakları saklıdır.':'All rights reserved.'
  },
  el:{
    'Günlük Kart':'Ημερήσια Κάρτα','3 Kart Tarot':'Ταρώ 3 Καρτών','Aşk & Geri Dönüş':'Αγάπη & Επανασύνδεση','Kariyer & Para':'Καριέρα & Χρήματα','30 Gün':'Άνοιγμα 30 Ημερών','Katina':'Κατίνα','Astroloji':'Αστρολογία','Astroloji Merkezi':'Κέντρο Αστρολογίας','Haftalık Burç':'Εβδομαδιαίο Ωροσκόπιο','Gökyüzü':'Ουρανός Τώρα','Bugünün Gökyüzü':'Ο Σημερινός Ουρανός','Sinastri':'Συναστρία','Kadim':'Αρχαίος Ουρανός','Kadim Gökyüzü':'Αρχαίος Ουρανός','Rüya':'Όνειρα','Rüya Yorumları':'Ερμηνεία Ονείρων','Numeroloji':'Αριθμολογία','Ay Takvimi':'Σεληνιακό Ημερολόγιο','Blog':'Περιοδικό','Hesabım':'Ο Λογαριασμός μου','Giriş Yap':'Σύνδεση','Üye Ol':'Δωρεάν Εγγραφή','Ücretsiz Üye Ol':'Δωρεάν Εγγραφή','Çıkış yap':'Αποσύνδεση',
    'TAMAMEN ÜCRETSİZ':'ΕΝΤΕΛΩΣ ΔΩΡΕΑΝ','Tüm açılımları aç.':'Ξεκλείδωσε όλες τις αναγνώσεις.','E-posta':'Email','Şifre':'Κωδικός','Kullanım koşullarını ve KVKK metnini okudum.':'Έχω διαβάσει τους Όρους Χρήσης και την Πολιτική Απορρήτου.','ÜCRETSİZ HESAP OLUŞTUR':'ΔΗΜΙΟΥΡΓΙΑ ΔΩΡΕΑΝ ΛΟΓΑΡΙΑΣΜΟΥ','Google ile devam et':'Συνέχεια με Google','veya e-posta ile':'ή συνέχεια με email','TEKRAR HOŞ GELDİN':'ΚΑΛΩΣ ΗΡΘΕΣ ΞΑΝΑ','Hesabına giriş yap.':'Συνδέσου στον λογαριασμό σου.','GİRİŞ YAP':'ΣΥΝΔΕΣΗ',
    'HER GÜN YENİ BİR İŞARET':'ΕΝΑ ΝΕΟ ΣΗΜΑ ΚΑΘΕ ΜΕΡΑ','Kartını seç.':'Διάλεξε την κάρτα σου.','Mesajını gör.':'Διάβασε το μήνυμά σου.','Tek kartımı aç':'Τράβηξε την ημερήσια κάρτα','Haftalık burcumu gör':'Διάβασε το εβδομαδιαίο ωροσκόπιο','ÖDEME KAPALI · TÜM DENEYİMLER ÜCRETSİZ':'ΧΩΡΙΣ ΣΥΝΔΡΟΜΗ · ΟΛΕΣ ΟΙ ΕΜΠΕΙΡΙΕΣ ΔΩΡΕΑΝ','DENEYİMLER':'ΕΜΠΕΙΡΙΕΣ','Merak ettiğin konuya göre alanını seç.':'Διάλεξε τον χώρο που ταιριάζει στην ερώτησή σου.','Keşfet':'Εξερεύνηση','ÜYE OLMADAN':'ΧΩΡΙΣ ΛΟΓΑΡΙΑΣΜΟ','ÜCRETSİZ ÜYELİK':'ΔΩΡΕΑΝ ΜΕΛΟΣ','HERKESE AÇIK':'ΑΝΟΙΧΤΟ ΣΕ ΟΛΟΥΣ',
    'MYTHBORN · GÖKYÜZÜ VE SEMBOL MERKEZİ':'MYTHBORN · ΚΕΝΤΡΟ ΟΥΡΑΝΟΥ & ΣΥΜΒΟΛΩΝ','Gökyüzünü oku.':'Διάβασε τον ουρανό.','Kendini keşfet.':'Ανακάλυψε τον εαυτό σου.','Bugünün gökyüzünü gör':'Δες τον σημερινό ουρανό','Doğum haritamı çıkar':'Υπολόγισε τον γενέθλιο χάρτη','Günlük kartımı aç':'Τράβηξε την ημερήσια κάρτα','TÜM DENEYİMLER ÜCRETSİZ':'ΟΛΕΣ ΟΙ ΕΜΠΕΙΡΙΕΣ ΕΙΝΑΙ ΔΩΡΕΑΝ','BUGÜN MYTHBORN’DA':'ΣΗΜΕΡΑ ΣΤΟ MYTHBORN','Her gün geri dönmek için dört güçlü neden.':'Τέσσερις ουσιαστικοί λόγοι για να επιστρέφεις καθημερινά.','Güncel, hızlı ve gerçekten çalışan deneyimler.':'Επίκαιρες, γρήγορες και πραγματικά χρήσιμες εμπειρίες.','EN ÇOK İLGİ GÖRENLER':'ΔΗΜΟΦΙΛΕΣ ΕΠΙΛΟΓΕΣ','Platformun en güçlü araçları.':'Τα ισχυρότερα εργαλεία της πλατφόρμας.',
    'Doğduğun anın gökyüzü haritasını keşfet.':'Ανακάλυψε τον ουρανό της στιγμής που γεννήθηκες.','Doğum bilgilerini gir.':'Συμπλήρωσε τα στοιχεία γέννησης.','Doğum tarihi':'Ημερομηνία γέννησης','Doğum saati':'Ώρα γέννησης','Doğum yeri':'Τόπος γέννησης','Doğum saatimi bilmiyorum':'Δεν γνωρίζω την ώρα γέννησης','Doğum haritamı yorumla':'Ερμηνεία γενέθλιου χάρτη','Güneş Burcu':'Ζώδιο Ήλιου','Ay Burcu':'Ζώδιο Σελήνης','Yükselen':'Ωροσκόπος','Evler':'Οίκοι','Gezegenler':'Πλανήτες','Açılar':'Όψεις','Transitler':'Διελεύσεις','Uyum Analizi':'Ανάλυση Συμβατότητας',
    'Bu hafta gökyüzü senin burcuna ne söylüyor?':'Τι λέει ο ουρανός στο ζώδιό σου αυτή την εβδομάδα;','12 BURÇ · HER HAFTA YENİ':'12 ΖΩΔΙΑ · ΝΕΟ ΚΑΘΕ ΕΒΔΟΜΑΔΑ','Aşk':'Αγάπη','Kariyer':'Καριέρα','Para':'Χρήματα','Enerji':'Ενέργεια','Dikkat':'Προσοχή','Güçlü gün':'Δυνατή ημέρα',
    'Bugünün merakını, yarının arşivine dönüştür.':'Μετέτρεψε τη σημερινή περιέργεια στο αυριανό αρχείο.','GÖKYÜZÜ GÜNDEMİ · DERİN REHBERLER':'ΟΥΡΑΝΙΟ ΠΕΡΙΟΔΙΚΟ · ΑΝΑΛΥΤΙΚΟΙ ΟΔΗΓΟΙ','Güncel gökyüzü olayları, ilişki astrolojisi, etik ve kişisel farkındalık üzerine özgün uzun form içerikler.':'Πρωτότυποι αναλυτικοί οδηγοί για ουράνια γεγονότα, αστρολογία σχέσεων, ηθική και αυτογνωσία.','Yazıyı oku →':'Διάβασε το άρθρο →','Tüm yazılar':'Όλα τα άρθρα','SIK SORULANLAR':'ΣΥΧΝΕΣ ΕΡΩΤΗΣΕΙΣ','Konuyla ilgili kısa yanıtlar.':'Σαφείς απαντήσεις σε συχνές ερωτήσεις.',
    'Çerezler':'Cookies','Zorunlu çerezleri oturum ve güvenlik için kullanıyoruz.':'Χρησιμοποιούμε απαραίτητα cookies για σύνδεση και ασφάλεια.','Detaylar':'Λεπτομέρειες','Reddet':'Απόρριψη','Kabul et':'Αποδοχή','Gizlilik':'Απόρρητο','KVKK':'Πολιτική Απορρήτου','Kullanım Koşulları':'Όροι Χρήσης','Eğlence, eğitim ve kişisel farkındalık amaçlıdır.':'Για ψυχαγωγία, εκπαίδευση και προσωπικό στοχασμό.','Tüm hakları saklıdır.':'Με επιφύλαξη παντός δικαιώματος.'
  }
};

const meta={
  en:{
    '/':['Free Tarot, Birth Chart & Astrology — Mythborn','Free daily Tarot, real birth chart calculations, synastry, weekly horoscopes, dream interpretation and ancient sky traditions.'],
    '/gizlilik':['Privacy Policy — Mythborn','Mythborn privacy policy and personal data protection principles.'],
    '/kvkk':['Turkish Data Protection Notice — Mythborn','Processing governed by Turkey’s Personal Data Protection Law No. 6698 (KVKK).'],
    '/kullanim-kosullari':['Terms of Use — Mythborn','Mythborn platform terms of use and legal disclaimers.'],
    '/cerezler':['Cookie Policy — Mythborn','Mythborn cookie policy and essential cookie management.']
  },
  el:{
    '/':['Δωρεάν Ταρώ, Γενέθλιος Χάρτης & Αστρολογία — Mythborn','Δωρεάν ημερήσιο Ταρώ, πραγματικός γενέθλιος χάρτης, συναστρία, εβδομαδιαία ωροσκόπια, όνειρα και αρχαίες ουράνιες παραδόσεις.'],
    '/gizlilik':['Πολιτική Απορρήτου — Mythborn','Πολιτική απορρήτου Mythborn και προστασία προσωπικών δεδομένων.'],
    '/kvkk':['Ενημέρωση Προστασίας Δεδομένων — Mythborn','Ενημέρωση βάσει του τουρκικού Νόμου 6698 (KVKK).'],
    '/kullanim-kosullari':['Όροι Χρήσης — Mythborn','Όροι χρήσης της πλατφόρμας Mythborn.'],
    '/cerezler':['Πολιτική Cookies — Mythborn','Πολιτική cookies και διαχείριση προτιμήσεων.']
  }
};

function localeFrom(path){if(path==='/en'||path.startsWith('/en/'))return'en';if(path==='/gr'||path.startsWith('/gr/')||path==='/el'||path.startsWith('/el/'))return'el';return'tr'}
function basePath(path,locale){if(locale==='tr')return path;const prefixes=locale==='el'?['/gr','/el']:[`/${locale}`];const prefix=prefixes.find(value=>path===value||path.startsWith(`${value}/`))||prefixes[0];if(path===prefix)return'/';return path.slice(prefix.length)||'/'}
function localizedPath(path,locale){const clean=path==='/'?'':path;return locale==='tr'?(clean||'/'):`/${locale==='el'?'gr':locale}${clean}`}
function replaceAllSafe(html,map){for(const[from,to]of Object.entries(map||{}))html=html.split(from).join(to);return html}
function prefixLinks(html,locale){if(locale==='tr')return html;const prefix=locale==='el'?'gr':locale;return html.replace(/(href|action)="\/(?!\/|api\/|images\/|app\.|final\.|oracle\.|favicon|menu\.|content\.|account-menu\.|weekly\.|sky\.|synastry\.|reflection\.|social-auth\.|discover\.|tarot-deck\.)/g,`$1="/${prefix}/`)}
function localizeHtml(html,locale,path){
  if(locale==='tr')return injectLanguageUi(html,locale,path);
  html=replaceAllSafe(html,dictionaries[locale]);
  html=prefixLinks(html,locale);
  html=html.replace(/<html lang="[^"]*"/,'<html lang="'+locales[locale].html+'"');
  const base=basePath(path,locale);
  const m=meta[locale]?.[base]||meta[locale]?.['/'];
  if(m){
    html=html.replace(/<title>.*?<\/title>/,`<title>${m[0]}</title>`).replace(/<meta name="description" content="[^"]*">/,`<meta name="description" content="${m[1]}">`);
  }
  return injectLanguageUi(html,locale,path);
}
function injectLanguageUi(html,locale,path){const base=basePath(path,locale);const alternates=`<link rel="alternate" hreflang="tr" href="${SITE}${localizedPath(base,'tr')}"><link rel="alternate" hreflang="en" href="${SITE}${localizedPath(base,'en')}"><link rel="alternate" hreflang="el" href="${SITE}${localizedPath(base,'el')}"><link rel="alternate" hreflang="x-default" href="${SITE}${localizedPath(base,'tr')}">`;
 const switcher=`<nav class="language-switcher" aria-label="Language"><a href="${localizedPath(base,'tr')}"${locale==='tr'?' aria-current="page"':''}>TR</a><a href="${localizedPath(base,'en')}"${locale==='en'?' aria-current="page"':''}>EN</a><a href="${localizedPath(base,'el')}"${locale==='el'?' aria-current="page"':''}>EL</a></nav><style>.language-switcher{position:fixed;z-index:90;right:14px;bottom:82px;display:flex;gap:4px;padding:5px;border:1px solid rgba(255,255,255,.13);border-radius:999px;background:rgba(9,7,13,.92);backdrop-filter:blur(14px)}.language-switcher a{display:grid;place-items:center;min-width:34px;min-height:34px;border-radius:999px;color:#aaa2b0;font:800 10px/1 system-ui;letter-spacing:.08em}.language-switcher a[aria-current=page]{background:#f4eee5;color:#09070c}@media(max-width:760px){.language-switcher{right:12px;bottom:76px}}</style>`;
 html=html.replace('</head>',`${alternates}</head>`);return html.replace('</body>',`${switcher}<script src="/i18n-client.js" defer></script></body>`)}
function localizedSitemap(){const routes=['/','/gunluk-kart','/tarot','/ask','/kariyer','/otuz-gun','/katina','/astroloji','/haftalik-burc','/ruya-yorumlari','/burc-uyumu','/numeroloji','/ay-takvimi','/bugunun-gokyuzu','/sinastri','/kadim-gokyuzu','/maya-zaman-donguleri','/mezopotamya-astrolojisi','/doga-gokyuzu-donguleri','/travma-bilincli-astroloji','/blog','/gizlilik','/kullanim-kosullari','/cerezler'];return`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">${routes.flatMap(path=>Object.keys(locales).map(locale=>`<url><loc>${SITE}${localizedPath(path,locale)}</loc>${Object.keys(locales).map(alt=>`<xhtml:link rel="alternate" hreflang="${alt}" href="${SITE}${localizedPath(path,alt)}"/>`).join('')}<xhtml:link rel="alternate" hreflang="x-default" href="${SITE}${localizedPath(path,'tr')}"/></url>`)).join('')}</urlset>`}

export default{async fetch(request,env,ctx){const url=new URL(request.url);if(url.pathname==='/sitemap.xml')return new Response(localizedSitemap(),{headers:{'content-type':'application/xml; charset=utf-8','cache-control':'public, max-age=300'}});const locale=localeFrom(url.pathname);const originalPath=url.pathname;const clean=basePath(originalPath,locale);if(locale!=='tr')url.pathname=clean;const proxied=new Request(url.toString(),request);const response=await base.fetch(proxied,env,ctx);const type=response.headers.get('content-type')||'';if(!type.includes('text/html'))return response;const html=await response.text();const headers=new Headers(response.headers);headers.set('content-language',locales[locale].html);headers.set('vary','Accept-Language');return new Response(localizeHtml(html,locale,originalPath),{status:response.status,headers})}};
