import multilingual from './multilingual-router.js';
import {premiumGuideRoutes,premiumGuidePage,advancedAstrologyIndex} from './premium-guides.js';
import {localizedBlogSlugs,localizedBlogPage} from './localized-blog.js';
import {blogDates} from './blog.js';
import {tarotCardSlugs,tarotLibraryPage} from './tarot-library.js';
import {libraryRoutes,libraryPage} from './astrology-library.js';
import {dreamSlugs,glossarySlugs,dreamPage,glossaryPage} from './dream-glossary.js';
const SITE='https://mythborn.co';
const localeFrom=path=>path==='/en'||path.startsWith('/en/')?'en':path==='/gr'||path.startsWith('/gr/')||path==='/el'||path.startsWith('/el/')?'el':'tr';
const cleanPath=(path,locale)=>locale==='tr'?path:(path===`/${locale}`?'/':path.slice(3)||'/');
const localized=(path,locale)=>locale==='tr'?path:`/${locale==='el'?'gr':locale}${path==='/'?'':path}`;
function decorate(html,path,locale){
 const robotsTag=html.includes('name="robots"')?'':`<meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1">`;
 const alt=`${robotsTag}<link rel="alternate" hreflang="tr" href="${SITE}${localized(path,'tr')}"><link rel="alternate" hreflang="en" href="${SITE}${localized(path,'en')}"><link rel="alternate" hreflang="el" href="${SITE}${localized(path,'el')}"><link rel="alternate" hreflang="x-default" href="${SITE}${localized(path,'tr')}">`;
 const switcher=`<nav class="language-switcher" aria-label="Language"><a href="${localized(path,'tr')}"${locale==='tr'?' aria-current="page"':''}>TR</a><a href="${localized(path,'en')}"${locale==='en'?' aria-current="page"':''}>EN</a><a href="${localized(path,'el')}"${locale==='el'?' aria-current="page"':''}>EL</a></nav><style>.language-switcher{position:fixed;z-index:90;right:14px;bottom:82px;display:flex;gap:4px;padding:5px;border:1px solid rgba(255,255,255,.13);border-radius:999px;background:rgba(9,7,13,.94);backdrop-filter:blur(14px)}.language-switcher a{display:grid;place-items:center;min-width:34px;min-height:34px;border-radius:999px;color:#aaa2b0;font:800 10px/1 system-ui}.language-switcher a[aria-current=page]{background:#f4eee5;color:#09070c}.premium-guide{width:min(900px,100%);margin:auto;padding:72px 0}.premium-guide h1{font-family:Georgia,serif;font-size:clamp(42px,6vw,76px);line-height:.98;font-weight:400}.article-lead{font-size:19px;color:#aaa2b0;line-height:1.7}.article-body{margin-top:38px}.article-body section{padding:30px 0;border-top:1px solid rgba(255,255,255,.12)}.article-body h2{font-family:Georgia,serif;font-size:clamp(28px,3.5vw,42px);font-weight:400}.article-body p{color:#aaa2b0;line-height:1.8}.article-faq details{padding:16px 0;border-top:1px solid rgba(255,255,255,.1)}.article-note{padding:18px;border:1px solid rgba(232,200,131,.25);border-radius:16px}@media(max-width:760px){.language-switcher{right:12px;bottom:76px}.premium-guide{padding-top:42px}.article-lead{font-size:17px}}</style>`;
 return html.replace('</head>',`${alt}</head>`).replace('</body>',`${switcher}</body>`);
}
function expandSitemap(xml){const guidePaths=['/advanced-astrology',...premiumGuideRoutes],blogPaths=['/blog',...localizedBlogSlugs.map(slug=>`/blog/${slug}`)],tarotPaths=['/tarot-kartlari',...tarotCardSlugs.map(slug=>`/tarot-kartlari/${slug}`)],dreamPaths=['/ruya-sembolleri',...dreamSlugs.map(slug=>`/ruya-sembolleri/${slug}`)],glossaryPaths=['/astroloji-sozlugu',...glossarySlugs.map(slug=>`/astroloji-sozlugu/${slug}`)],additions=[...guidePaths,...blogPaths,...tarotPaths,...libraryRoutes,...dreamPaths,...glossaryPaths].flatMap(path=>['tr','en','el'].map(locale=>`<url><loc>${SITE}${localized(path,locale)}</loc>${blogDates[path]?`<lastmod>${blogDates[path]}</lastmod>`:''}${['tr','en','el'].map(alt=>`<xhtml:link rel="alternate" hreflang="${alt}" href="${SITE}${localized(path,alt)}"/>`).join('')}<xhtml:link rel="alternate" hreflang="x-default" href="${SITE}${localized(path,'tr')}"/></url>`)).join('');return xml.replace('</urlset>',`${additions}</urlset>`)}
export default{async fetch(request,env,ctx){const url=new URL(request.url),locale=localeFrom(url.pathname),clean=cleanPath(url.pathname,locale);if(clean==='/ruya-sembolleri'||dreamSlugs.some(slug=>clean===`/ruya-sembolleri/${slug}`)){const html=dreamPage(locale,clean);return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','content-language':locale==='tr'?'tr-TR':locale,'cache-control':'public, max-age=300'}})}if(clean==='/astroloji-sozlugu'||glossarySlugs.some(slug=>clean===`/astroloji-sozlugu/${slug}`)){const html=glossaryPage(locale,clean);return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','content-language':locale==='tr'?'tr-TR':locale,'cache-control':'public, max-age=300'}})}if(libraryRoutes.includes(clean)){const html=libraryPage(clean,locale);return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','content-language':locale==='tr'?'tr-TR':locale,'cache-control':'public, max-age=300'}})}if(clean==='/tarot-kartlari'||tarotCardSlugs.some(slug=>clean===`/tarot-kartlari/${slug}`)){const html=tarotLibraryPage(locale,clean);return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','content-language':locale==='tr'?'tr-TR':locale,'cache-control':'public, max-age=300'}})}if(locale!=='tr'&&(clean==='/blog'||localizedBlogSlugs.some(slug=>clean===`/blog/${slug}`))){const html=localizedBlogPage(locale,clean);return new Response(html,{headers:{'content-type':'text/html; charset=utf-8','content-language':locale,'cache-control':'public, max-age=300'}})}if(clean==='/advanced-astrology'||premiumGuideRoutes.includes(clean)){const html=clean==='/advanced-astrology'?advancedAstrologyIndex(locale):premiumGuidePage(clean,locale);return new Response(decorate(html,clean,locale),{headers:{'content-type':'text/html; charset=utf-8','content-language':locale==='tr'?'tr-TR':locale,'cache-control':'public, max-age=300'}})}if(url.pathname==='/sitemap.xml'){const response=await multilingual.fetch(request,env,ctx),xml=await response.text();return new Response(expandSitemap(xml),{status:response.status,headers:response.headers})}return multilingual.fetch(request,env,ctx)}};
